import { View, Text, Pressable, ScrollView, FlatList, StyleSheet, ImageBackground } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { resolveHomeTiles, translateLabel } from '@nova/core';
import { useTheme } from '../theme/ThemeProvider';
import { MoonToggle } from '../components/MoonToggle';
import { space, radius, type } from '../theme/tokens';
import { useT, useLocaleLanguage } from '../i18n/LocaleContext';
const GLYPH:Record<string,string>={home:'⌂',car:'◇',sofa:'▱',services:'✦',work:'▣',electronics:'◉',hobby:'✧',more:'•••'};
export function HomeScreen({onOpenCategory,onOpenSystem,place}:{onOpenCategory:(path:string)=>void;onOpenSystem:()=>void;place:string}){
 const {theme}=useTheme(); const t=useT(); const language=useLocaleLanguage(); const tiles=resolveHomeTiles();
 return <SafeAreaView style={[s.root,{backgroundColor:theme.bg}]}>
  <View style={s.top}><Text style={[type.brand,{color:theme.ink}]}>NOVA</Text><View style={s.topRight}><Pressable onPress={onOpenSystem}><Text style={{color:theme.muted,fontSize:12}}>⌖ {place}</Text></Pressable><MoonToggle/></View></View>
  <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
   <View style={[s.search,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={{color:theme.muted,fontSize:17}}>⌕</Text><Text style={{color:theme.muted,flex:1}}>Найти на Nova</Text><View style={[s.filter,{borderColor:theme.line}]}><Text style={{color:theme.ink}}>☷</Text></View></View>
   <ImageBackground source={require('../../assets/hero.jpg')} style={s.hero} imageStyle={s.heroImage}><View style={s.heroShade}><Text style={s.kicker}>NOVA SELECT</Text><Text style={s.heroTitle}>Находи лучшее рядом</Text><Text style={s.heroText}>Вещи, авто, недвижимость и услуги — в одном месте.</Text><View style={s.heroButton}><Text style={{fontWeight:'800',color:'#101412'}}>Смотреть предложения</Text></View></View></ImageBackground>
   <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:theme.ink}]}>Категории</Text><Text style={{color:theme.accentText,fontSize:12,fontWeight:'700'}}>Все</Text></View>
   <FlatList data={tiles} keyExtractor={x=>x.label} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:space.sm}} renderItem={({item:tile})=><Pressable onPress={()=>tile.available&&onOpenCategory(tile.to)} disabled={!tile.available} style={({pressed})=>[s.tile,{backgroundColor:pressed?theme.surface2:theme.surface,borderColor:theme.line,opacity:tile.available?1:.45}]}><View style={[s.tileIcon,{backgroundColor:theme.accentSoft}]}><Text style={{fontSize:19,color:theme.accentText}}>{GLYPH[tile.icon]??'◇'}</Text></View><Text style={[s.tileLabel,{color:theme.ink2}]} numberOfLines={2}>{tile.categoryId?translateLabel(tile.label,language):t('app.allCategories')}</Text></Pressable>}/>
   <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:theme.ink}]}>Популярное сегодня</Text><Text style={{color:theme.muted,fontSize:12}}>Подборка Nova</Text></View>
   <View style={[s.promo,{backgroundColor:theme.surface,borderColor:theme.line}]}><Text style={[s.promoTitle,{color:theme.ink}]}>Объявления с фотографиями</Text><Text style={{color:theme.muted,lineHeight:19}}>Карточки на телефоне теперь показывают реальные фото товаров, авто и недвижимости.</Text></View>
  </ScrollView>
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:space.lg,paddingVertical:space.md},topRight:{flexDirection:'row',alignItems:'center',gap:space.md},scroll:{paddingHorizontal:space.lg,paddingBottom:space.xxl},search:{height:48,borderWidth:1,borderRadius:16,flexDirection:'row',alignItems:'center,gap:10,paddingLeft:14,paddingRight:7,marginBottom:14},filter:{width:36,height:36,borderWidth:1,borderRadius:11,alignItems:'center',justifyContent:'center'},hero:{height:238,borderRadius:22,overflow:'hidden',justifyContent:'flex-end'},heroImage:{borderRadius:22},heroShade:{flex:1,justifyContent:'flex-end',padding:20,backgroundColor:'rgba(5,10,8,.42)'},kicker:{color:'#a8ffbf',fontSize:10,fontWeight:'800',letterSpacing:1.5},heroTitle:{color:'white',fontSize:27,fontWeight:'850',letterSpacing:-.7,marginTop:7,maxWidth:260},heroText:{color:'rgba(255,255,255,.82)',fontSize:13,lineHeight:18,maxWidth:280,marginTop:7},heroButton:{alignSelf:'flex-start',marginTop:14,paddingHorizontal:15,paddingVertical:10,borderRadius:12,backgroundColor:'#fff'},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:22,marginBottom:11},sectionTitle:{fontSize:18,fontWeight:'800'},tile:{width:112,minHeight:106,borderWidth:1,borderRadius:16,padding:11,justifyContent:'space-between'},tileIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},tileLabel:{fontSize:11.5,fontWeight:'700',lineHeight:14},promo:{borderWidth:1,borderRadius:18,padding:17},promoTitle:{fontSize:15,fontWeight:'800',marginBottom:5}});
