export const labels: Record<string, string> = {
  "0–1 год": "0–1 Jahr",
  "0–6 мес.": "0–6 Mon.",
  "1": "1",
  "1 ТБ": "1 TB",
  "100% от аренды": "100 % der Miete",
  "12+": "12+",
  "128 ГБ": "128 GB",
  "16 ГБ": "16 GB",
  "1–3 года": "1–3 Jahre",
  "1–4 года": "1–4 Jahre",
  "2": "2",
  "2/2": "2/2",
  "256 ГБ": "256 GB",
  "3": "3",
  "3 и более": "3 und mehr",
  "32 ГБ": "32 GB",
  "36": "36",
  "37": "37",
  "38": "38",
  "39": "39",
  "3–5 лет": "3–5 Jahre",
  "3–6 лет": "3–6 Jahre",
  "3–7 лет": "3–7 Jahre",
  "4 ГБ": "4 GB",
  "4+": "4+",
  "40": "40",
  "41": "41",
  "42": "42",
  "43": "43",
  "44": "44",
  "45": "45",
  "4–7 лет": "4–7 Jahre",
  "5/2": "5/2",
  "50% от аренды": "50 % der Miete",
  "512 ГБ": "512 GB",
  "6/1": "6/1",
  "64 ГБ": "64 GB",
  "6–18 мес.": "6–18 Mon.",
  "7–12 лет": "7–12 Jahre",
  "8 ГБ": "8 GB",
  "IT и интернет": "IT und Internet",
  "IT, реклама и дизайн": "IT, Werbung und Design",
  "L": "L",
  "M": "M",
  "Nintendo": "Nintendo",
  "PC": "PC",
  "PlayStation": "PlayStation",
  "S": "S",
  "SMM и реклама": "SMM und Werbung",
  "Smart TV": "Smart-TV",
  "VIN или госномер": "FIN oder Kennzeichen",
  "VR-гарнитура": "VR-Headset",
  "Wi-Fi": "WLAN",
  "XL": "XL",
  "XS": "XS",
  "XXL": "XXL",
  "Xbox": "Xbox",
  "Ёмкости и баки": "Behälter und Tanks",
  "Ёмкость аккумулятора": "Akkukapazität",
  "Авто": "Auto",
  "Авто и спецтехника напрокат": "Auto- und Baumaschinenverleih",
  "Автобус": "Bus",
  "Автокресло": "Kindersitz",
  "Автомат": "Automatik",
  "Адрес": "Adresse",
  "Адрес или район": "Adresse oder Bezirk",
  "Аквариумные": "Aquarientiere",
  "Аквариумы": "Aquarien",
  "Аксессуары": "Zubehör",
  "Аксессуары и часы": "Zubehör und Uhren",
  "Амуниция": "Ausrüstung",
  "Английский язык": "Englisch",
  "Антиквариат": "Antiquitäten",
  "Апартаменты": "Apartment",
  "Аренда жилья и помещений": "Vermietung von Wohnungen und Räumen",
  "Арест": "Pfändung",
  "Асфальт": "Asphalt",
  "Б/у": "Gebraucht",
  "База отдыха": "Ferienanlage",
  "Балкон или лоджия": "Balkon oder Loggia",
  "Без комиссии": "Ohne Provision",
  "Без мебели": "Unmöbliert",
  "Без опыта": "Ohne Erfahrung",
  "Без оформления": "Ohne offizielle Anstellung",
  "Без предоплаты": "Ohne Vorauszahlung",
  "Без ремонта": "Ohne Renovierung",
  "Без транспорта": "Ohne eigenes Fahrzeug",
  "Бездорожье": "Offroad",
  "Белый": "Weiß",
  "Бензин": "Benzin",
  "Билеты на события": "Eventtickets",
  "Бокс": "Boxen",
  "Более 15 человек": "Mehr als 15 Personen",
  "Более 5 лет": "Mehr als 5 Jahre",
  "Более 6 лет": "Mehr als 6 Jahre",
  "Бренд": "Marke",
  "Бригада": "Team",
  "Брови и ресницы": "Augenbrauen und Wimpern",
  "Брюки": "Hosen",
  "Брюки и джинсы": "Hosen und Jeans",
  "Бустер": "Sitzerhöhung",
  "Бытовая техника": "Haushaltsgeräte",
  "В вакансии — что предлагаете, в резюме — что ожидаете.": "In der Stellenanzeige: was Sie bieten. Im Lebenslauf: was Sie erwarten.",
  "В добрые руки с договором": "In gute Hände mit Vertrag",
  "В месяц": "Pro Monat",
  "В офисе заказчика": "Beim Auftraggeber vor Ort",
  "В салоне": "Im Salon",
  "В собственности": "Im Eigentum",
  "Вариатор": "CVT-Getriebe",
  "Вахта": "Rotationsarbeit",
  "Велосипеды": "Fahrräder",
  "Верхняя одежда": "Oberbekleidung",
  "Взрослые": "Erwachsene",
  "Взять в аренду": "Mieten",
  "Вид животного": "Tierart",
  "Вид работ": "Art der Arbeiten",
  "Вид разрешённого использования": "Art der zulässigen Nutzung",
  "Вид услуги": "Art der Dienstleistung",
  "Видеокамера": "Videokamera",
  "Владельцев по ПТС": "Vorbesitzer laut Fahrzeugschein",
  "Внедорожник": "Geländewagen",
  "Водительские права": "Führerschein",
  "Возможна доставка": "Lieferung möglich",
  "Возможна ипотека": "Finanzierung möglich",
  "Возраст": "Alter",
  "Возраст водителя от": "Mindestalter des Fahrers",
  "Возрастная группа": "Altersgruppe",
  "Все вакансии": "Alle Stellenangebote",
  "Все комнаты, санузел и кухня. Минимум 5 фото.": "Alle Zimmer, Bad und Küche. Mindestens 5 Fotos.",
  "Все объекты в продаже": "Alle Objekte zum Verkauf",
  "Все объявления": "Alle Anzeigen",
  "Все предложения услуг": "Alle Dienstleistungsangebote",
  "Все резюме": "Alle Lebensläufe",
  "Все центральные": "Alle zentralen",
  "Встроенная память": "Interner Speicher",
  "Вывоз мусора": "Müllentsorgung",
  "Выезд к заказчику": "Anfahrt zum Kunden",
  "Выплаты": "Zahlungen",
  "Высота": "Höhe",
  "Высота потолков": "Deckenhöhe",
  "Выставки": "Ausstellungen",
  "Высшее": "Hochschulabschluss",
  "Газ": "Gas",
  "Газель": "Transporter",
  "Газоблок": "Gasbeton",
  "Газовое": "Gas",
  "Гараж": "Garage",
  "Гараж и машиноместо": "Garage und Stellplatz",
  "Гаражи и машиноместа": "Garagen und Stellplätze",
  "Гарантия действует": "Garantie gültig",
  "Гарантия на работы": "Garantie auf die Arbeiten",
  "Гастротур": "Kulinarische Tour",
  "Где принимаете": "Empfangsort",
  "Геймпад": "Gamepad",
  "Генеральная уборка": "Grundreinigung",
  "Гибрид": "Hybrid",
  "Гитары": "Gitarren",
  "Глубина": "Tiefe",
  "Год выпуска": "Baujahr",
  "Год постройки": "Baujahr",
  "Головные уборы": "Kopfbedeckungen",
  "Горелки и посуда": "Kocher und Geschirr",
  "Город": "Stadt",
  "Город отправления": "Abfahrtsort",
  "Гостей": "Gäste",
  "Готов к переезду": "Umzugsbereit",
  "График": "Arbeitszeit",
  "Грузовик": "LKW",
  "Грузовик до 5 т": "LKW bis 5 t",
  "Грузовик свыше 5 т": "LKW über 5 t",
  "Грузовики и спецтехника": "LKW und Baumaschinen",
  "Грузоподъёмность": "Tragfähigkeit",
  "Грузчики": "Umzugshelfer",
  "Грунт": "Boden",
  "Грызуны": "Nagetiere",
  "Да": "Ja",
  "Дата события": "Datum der Veranstaltung",
  "Два раза в месяц": "Zweimal im Monat",
  "Двери": "Türen",
  "Двигатель": "Motor",
  "Девочка": "Mädchen",
  "Дерево": "Holz",
  "Дети и детские услуги": "Kinder und Kinderbetreuung",
  "Детская мебель": "Kindermöbel",
  "Детская одежда и обувь": "Kinderkleidung und -schuhe",
  "Детское": "Für Kinder",
  "Диагональ": "Diagonale",
  "Диагональ экрана": "Bildschirmdiagonale",
  "Диван": "Sofa",
  "Дизайн": "Design",
  "Дизайнерский": "Designerausbau",
  "Дизель": "Diesel",
  "Длительно (от года)": "Langfristig (ab einem Jahr)",
  "Длительность занятия": "Dauer der Unterrichtseinheit",
  "Для дома": "Für Zuhause",
  "Для кого": "Für wen",
  "Для марки": "Für Marke",
  "До 15 человек": "Bis 15 Personen",
  "До 5 человек": "Bis 5 Personen",
  "До года": "Bis zu einem Jahr",
  "Договор ГПХ": "Werkvertrag",
  "Долевая собственность": "Miteigentum",
  "Дом": "Haus",
  "Дом, дача, таунхаус": "Haus, Datscha, Reihenhaus",
  "Дома и дачи": "Häuser und Datschen",
  "Домашний кинотеатр": "Heimkino",
  "Домашний персонал": "Haushaltspersonal",
  "Домики и лежанки": "Häuschen und Schlafplätze",
  "Допустимый вес ребёнка": "Zulässiges Kindergewicht",
  "Дорожный": "Für unterwegs",
  "Доставка мебели": "Möbeltransport",
  "Дошкольники": "Vorschulkinder",
  "Другая": "Sonstige",
  "Другие языки": "Andere Sprachen",
  "Духовые": "Blasinstrumente",
  "Евроремонт": "Hochwertige Renovierung",
  "Единица расчёта": "Abrechnungseinheit",
  "Единоборства": "Kampfsport",
  "Ежедневно": "Täglich",
  "Еженедельно": "Wöchentlich",
  "Есть": "Vorhanden",
  "Есть автомобиль": "Auto vorhanden",
  "Есть документы и родословная": "Papiere und Stammbaum vorhanden",
  "Есть сертификат или диплом": "Zertifikat oder Diplom vorhanden",
  "ЖКХ и благоустройство": "Hausverwaltung und Grünpflege",
  "Женское": "Damen",
  "Животные": "Tiere",
  "Живые фото питомца, а не изображения породы из интернета.": "Echte Fotos des Tieres, keine Rasse-Bilder aus dem Internet.",
  "За два месяца": "Für zwei Monate",
  "За заказ": "Pro Auftrag",
  "За км": "Pro km",
  "За м²": "Pro m²",
  "За месяц": "Pro Monat",
  "За метр погонный": "Pro laufendem Meter",
  "За проект": "Pro Projekt",
  "За услугу": "Pro Leistung",
  "За час": "Pro Stunde",
  "Задний": "Hinterradantrieb",
  "Залог": "Kaution",
  "Занятость": "Beschäftigungsart",
  "Заполним марку, модель, год и двигатель автоматически. Можно ввести данные вручную.": "Marke, Modell, Baujahr und Motor werden automatisch ausgefüllt. Manuelle Eingabe ist möglich.",
  "Запчасти и аксессуары": "Ersatzteile und Zubehör",
  "Зарплата от": "Gehalt ab",
  "Земельные участки": "Grundstücke",
  "Земельный участок": "Grundstück",
  "Зимний спорт": "Wintersport",
  "Значки": "Abzeichen",
  "ИЖС": "Einzelhausbebauung",
  "Игра": "Spiel",
  "Игровая приставка": "Spielkonsole",
  "Игрушки": "Spielzeug",
  "Игрушки и товары для игр": "Spielzeug und Spielwaren",
  "Игры и приставки": "Spiele und Konsolen",
  "Индивидуально": "Einzeln",
  "Индивидуальный гид": "Privater Reiseführer",
  "Инструменты": "Werkzeuge",
  "Информатика": "Informatik",
  "Ипотека": "Hypothek",
  "Искусство и творчество": "Kunst und Kreatives",
  "Кадастровый номер": "Katasternummer",
  "Каркас": "Rahmen",
  "Квартира": "Wohnung",
  "Квартирный переезд": "Wohnungsumzug",
  "Квартиры": "Wohnungen",
  "Кино": "Kino",
  "Кирпич": "Ziegel",
  "Клавишные": "Tasteninstrumente",
  "Клетки и переноски": "Käfige und Transportboxen",
  "Клининговая компания": "Reinigungsfirma",
  "Книги": "Bücher",
  "Книги и коллекционирование": "Bücher und Sammeln",
  "Кожа": "Leder",
  "Количество билетов": "Anzahl der Tickets",
  "Колонки": "Lautsprecher",
  "Коляска 2 в 1": "Kinderwagen 2 in 1",
  "Коляска 3 в 1": "Kinderwagen 3 in 1",
  "Коляска-люлька": "Kinderwagen mit Babywanne",
  "Коляски и автокресла": "Kinderwagen und Kindersitze",
  "Командные виды": "Mannschaftssport",
  "Комбинезоны": "Overalls",
  "Комиссия агента": "Maklerprovision",
  "Коммерческая недвижимость": "Gewerbeimmobilien",
  "Коммерческое": "Gewerblich",
  "Коммунальные включены": "Nebenkosten inklusive",
  "Коммуникации": "Ver- und Entsorgung",
  "Комнат": "Zimmer",
  "Комната": "Zimmer",
  "Комод": "Kommode",
  "Компания": "Unternehmen",
  "Кондиционер": "Klimaanlage",
  "Конструкторы": "Bausätze",
  "Концерты": "Konzerte",
  "Копирайтинг": "Copywriting",
  "Корма": "Futter",
  "Коробка передач": "Getriebe",
  "Коротко и по делу — это первое, что видит покупатель.": "Kurz und knapp — das sieht der Käufer zuerst.",
  "Коротко и по делу — это первое, что видит человек.": "Kurz und knapp — das sieht die Person zuerst.",
  "Косметика": "Kosmetik",
  "Косметический": "Kosmetische Renovierung",
  "Косметология": "Kosmetologie",
  "Кофты и футболки": "Pullover und T-Shirts",
  "Кошки": "Katzen",
  "Кран": "Kran",
  "Красный": "Rot",
  "Красота и здоровье": "Beauty und Gesundheit",
  "Кроватка": "Babybett",
  "Кровать": "Bett",
  "Кровля": "Dach",
  "Кросс": "Cross",
  "Круизер": "Cruiser",
  "Кто оказывает услугу": "Wer bietet die Leistung an",
  "Кузов": "Karosserie",
  "Куклы": "Puppen",
  "Купе": "Coupé",
  "Купить": "Kaufen",
  "Кухонный гарнитур": "Küchenzeile",
  "ЛДСП": "Spanplatte",
  "ЛПХ": "Nebenerwerbslandwirtschaft",
  "Легковые авто": "PKW",
  "Лимит пробега в сутки": "Kilometerlimit pro Tag",
  "Личные вещи": "Persönliche Gegenstände",
  "Макияж": "Make-up",
  "Мальчик": "Junge",
  "Манеж": "Laufgitter",
  "Маникюр и педикюр": "Maniküre und Pediküre",
  "Марка": "Marke",
  "Маркетинг и медиа": "Marketing und Medien",
  "Марки": "Marken",
  "Массаж": "Massage",
  "Математика": "Mathematik",
  "Материал": "Material",
  "Материал стен": "Wandmaterial",
  "Машинки": "Spielzeugautos",
  "Машиноместо": "Stellplatz",
  "Мебель": "Möbel",
  "Мебель и интерьер": "Möbel und Einrichtung",
  "Медиаплеер": "Mediaplayer",
  "Медицинские товары": "Medizinprodukte",
  "Междугородние перевозки": "Überlandtransport",
  "Менее года": "Weniger als ein Jahr",
  "Месяц": "Monat",
  "Металл": "Metall",
  "Механика": "Schaltgetriebe",
  "Микроволновка": "Mikrowelle",
  "Минивэн": "Minivan",
  "Минимальный срок": "Mindestmietdauer",
  "Минимум 3 фото — объявления с фото смотрят в 4 раза чаще.": "Mindestens 3 Fotos — Anzeigen mit Fotos werden 4-mal häufiger angesehen.",
  "Минимум 3 фото, включая экран во включённом состоянии.": "Mindestens 3 Fotos, darunter eines mit eingeschaltetem Bildschirm.",
  "Минимум 3 фото.": "Mindestens 3 Fotos.",
  "Минимум 3 фото: спереди, сзади, салон.": "Mindestens 3 Fotos: von vorne, von hinten, Innenraum.",
  "Многодневный тур": "Mehrtägige Tour",
  "Мобильные приложения": "Mobile Apps",
  "Модели и фигурки": "Modelle und Figuren",
  "Модель": "Modell",
  "Можно без опыта": "Auch ohne Erfahrung",
  "Можно с детьми": "Mit Kindern möglich",
  "Можно с животными": "Haustiere erlaubt",
  "Монеты": "Münzen",
  "Моноблок": "All-in-One-PC",
  "Морская прогулка": "Bootsausflug",
  "Мотоциклы и мототехника": "Motorräder und Motortechnik",
  "Мужское": "Herren",
  "Музыка": "Musik",
  "Музыкальные инструменты": "Musikinstrumente",
  "Муниципальная": "Kommunal",
  "Мытьё окон": "Fensterreinigung",
  "Мягкие игрушки": "Plüschtiere",
  "На дому у мастера": "Beim Anbieter zu Hause",
  "На месте": "Vor Ort",
  "На несколько месяцев": "Für mehrere Monate",
  "Навигация": "Navigation",
  "Навыки": "Fähigkeiten",
  "Название компании": "Firmenname",
  "Название объявления": "Anzeigentitel",
  "Назначение": "Nutzungsart",
  "Найти жильё": "Wohnung finden",
  "Найти исполнителя": "Dienstleister finden",
  "Найти питомца или товар": "Haustier oder Produkt finden",
  "Найти работу": "Job finden",
  "Найти сотрудника": "Mitarbeiter finden",
  "Найти тур или снаряжение": "Tour oder Ausrüstung finden",
  "Найти человека в команду": "Teammitglied finden",
  "Накопитель": "Speicherlaufwerk",
  "Напольные покрытия": "Bodenbeläge",
  "Направление": "Richtung",
  "Например: 15 октября 2026": "Zum Beispiel: 15. Oktober 2026",
  "Населённый пункт": "Ort",
  "Настольные игры": "Brettspiele",
  "Настольный компьютер": "Desktop-PC",
  "Настройка сетей": "Netzwerkeinrichtung",
  "Наука и инженерия": "Wissenschaft und Technik",
  "Наушники": "Kopfhörer",
  "Начальная школа": "Grundschule",
  "Недвижимость": "Immobilien",
  "Неделя": "Woche",
  "Незаконченное высшее": "Unvollständiges Hochschulstudium",
  "Необязательно. Требовать возраст в вакансиях запрещено законом.": "Optional. Altersangaben in Stellenanzeigen sind gesetzlich verboten.",
  "Нет": "Nein",
  "Новое": "Neu",
  "Новое без бирки": "Neu ohne Etikett",
  "Новое вскрытое": "Neu, geöffnet",
  "Новое запечатанное": "Neu, versiegelt",
  "Новое с биркой": "Neu mit Etikett",
  "Ноутбук": "Laptop",
  "Ноутбуки и компьютеры": "Laptops und Computer",
  "О себе": "Über mich",
  "О себе и методике": "Über mich und meine Methodik",
  "Образование": "Ausbildung",
  "Обременения": "Belastungen",
  "Обувь": "Schuhe",
  "Обучение и репетиторы": "Unterricht und Nachhilfe",
  "Объектив": "Objektiv",
  "Объём двигателя": "Hubraum",
  "Обязанности": "Aufgaben",
  "Огорожен": "Eingezäunt",
  "Одежда для походов": "Outdoor-Kleidung",
  "Одежда и обувь": "Kleidung und Schuhe",
  "Окна": "Fenster",
  "Окна и двери": "Fenster und Türen",
  "Онлайн": "Online",
  "Оперативная память": "Arbeitsspeicher",
  "Описание": "Beschreibung",
  "Описание маршрута": "Routenbeschreibung",
  "Описание услуги": "Beschreibung der Leistung",
  "Описание услуги и портфолио": "Beschreibung der Leistung und Portfolio",
  "Опыт преподавания": "Unterrichtserfahrung",
  "Опыт работы": "Berufserfahrung",
  "Оставьте пустым, если залога нет.": "Leer lassen, wenn keine Kaution anfällt.",
  "Оставьте пустым, если отдаёте даром.": "Leer lassen, wenn Sie es kostenlos abgeben.",
  "Отдам даром": "Zu verschenken",
  "Отделочные работы": "Ausbauarbeiten",
  "Отдельный вход": "Separater Eingang",
  "Открытки": "Postkarten",
  "Отличное": "Ausgezeichnet",
  "Отопление": "Heizung",
  "Офис": "Büro",
  "Офис и администрация": "Büro und Verwaltung",
  "Офисный переезд": "Büroumzug",
  "Оформление": "Anstellungsart",
  "Оформление, отпуск, что оплачивается.": "Anstellungsart, Urlaub, was bezahlt wird.",
  "Охрана": "Sicherheitsdienst",
  "Охрана и безопасность": "Wach- und Sicherheitsdienst",
  "Очки": "Brillen",
  "Палатки": "Zelte",
  "Панель": "Paneel",
  "Парикмахерские услуги": "Friseurdienstleistungen",
  "Парковка": "Parkplatz",
  "Парта": "Schulschreibtisch",
  "Парфюмерия": "Parfümerie",
  "Пеленальный столик": "Wickeltisch",
  "Первое занятие бесплатно": "Erste Stunde kostenlos",
  "Перевозки и грузчики": "Transport und Umzugshelfer",
  "Передний": "Frontantrieb",
  "Переуступка": "Abtretung",
  "Печное": "Ofenheizung",
  "Планшет": "Tablet",
  "Платформа": "Plattform",
  "Платья": "Kleider",
  "Плита": "Herd",
  "Плитка": "Fliesen",
  "Площадь": "Fläche",
  "Площадь дома": "Hausfläche",
  "Площадь участка": "Grundstücksfläche",
  "По ТК РФ": "Regulärer Arbeitsvertrag",
  "По договорённости": "Nach Vereinbarung",
  "По номеру заполним площадь, вид использования и границы. Можно пропустить.": "Anhand der Nummer füllen wir Fläche, Nutzungsart und Grenzen aus. Kann übersprungen werden.",
  "Погрузчик": "Lader",
  "Подвеска": "Fahrwerk",
  "Подготовка к ЕГЭ и ОГЭ": "Vorbereitung auf Abschlussprüfungen",
  "Поддерживающая уборка": "Unterhaltsreinigung",
  "Подработка": "Nebenjob",
  "Подростковое": "Für Jugendliche",
  "Подходит студентам": "Geeignet für Studenten",
  "Подъездная дорога": "Zufahrtsstraße",
  "Покажите вещь целиком и вблизи — фактуру и возможные дефекты.": "Zeigen Sie den Artikel ganz und aus der Nähe — Struktur und mögliche Mängel.",
  "Покажите крепления и ремни — это первое, что смотрят родители.": "Zeigen Sie Befestigungen und Gurte — das prüfen Eltern zuerst.",
  "Пол": "Geschlecht",
  "Полки": "Regale",
  "Полная": "Vollzeit",
  "Полностью меблирована": "Voll möbliert",
  "Полный": "Allradantrieb",
  "Полный комплект": "Vollständiges Set",
  "Помощь по хозяйству": "Haushaltshilfe",
  "Порода": "Rasse",
  "Портфолио повышает отклик в разы. Минимум 3 фото.": "Ein Portfolio erhöht die Rückmeldungen deutlich. Mindestens 3 Fotos.",
  "Портфолио — главный аргумент в этой категории.": "Das Portfolio ist das wichtigste Argument in dieser Kategorie.",
  "Последнее место работы": "Letzter Arbeitsplatz",
  "Посудомоечная машина": "Geschirrspüler",
  "Посуточная аренда": "Tagesvermietung",
  "Посуточная аренда жилья": "Tageweise Vermietung von Wohnraum",
  "Посуточно": "Pro Tag",
  "Предложить услугу": "Dienstleistung anbieten",
  "Предмет или направление": "Fach oder Richtung",
  "Предоплата": "Vorauszahlung",
  "Приборы для ухода": "Pflegegeräte",
  "Прививки сделаны": "Geimpft",
  "Привод": "Antrieb",
  "Пробег": "Laufleistung",
  "Пробег затвора": "Auslösungszahl",
  "Прогулочная коляска": "Buggy",
  "Продажа": "Verkauf",
  "Продажа или отдам даром": "Verkauf oder zu verschenken",
  "Продажи и торговля": "Verkauf und Handel",
  "Продать": "Verkaufen",
  "Продолжительность": "Dauer",
  "Проектор": "Projektor",
  "Проживание, питание, трансфер, входные билеты.": "Unterkunft, Verpflegung, Transfer, Eintrittskarten.",
  "Производство": "Produktion",
  "Профессия": "Beruf",
  "Процессор": "Prozessor",
  "Птицы": "Vögel",
  "Путешествия": "Reisen",
  "Пылесос": "Staubsauger",
  "Работа": "Arbeit",
  "Работаю круглосуточно": "Rund um die Uhr im Einsatz",
  "Работаю по договору": "Arbeite auf Vertragsbasis",
  "Раз в месяц": "Einmal im Monat",
  "Развивающие": "Lernspielzeug",
  "Размер": "Größe",
  "Размер группы": "Gruppengröße",
  "Разместить вакансию": "Stellenanzeige aufgeben",
  "Разместить объявление": "Anzeige aufgeben",
  "Разместить объявление о продаже": "Verkaufsanzeige aufgeben",
  "Разместить объявление об аренде": "Mietanzeige aufgeben",
  "Разместить предложение": "Angebot einstellen",
  "Разместить резюме": "Lebenslauf veröffentlichen",
  "Разместить своё объявление": "Eigene Anzeige aufgeben",
  "Разработка сайтов": "Webentwicklung",
  "Растения и саженцы": "Pflanzen und Setzlinge",
  "Ремни": "Gurte",
  "Ремонт": "Renovierung",
  "Ремонт и строительство": "Renovierung und Bau",
  "Ремонт и стройматериалы": "Renovierung und Baumaterialien",
  "Ремонт компьютеров": "Computerreparatur",
  "Ремонт под ключ": "Renovierung schlüsselfertig",
  "Рента": "Leibrente",
  "Рестораны и гостиницы": "Restaurants und Hotels",
  "Робот": "Roboter",
  "Рубашки и блузки": "Hemden und Blusen",
  "Русский язык": "Russisch",
  "Рыбалка": "Angeln",
  "Рыбы": "Fische",
  "Рюкзаки": "Rucksäcke",
  "С водителем": "Mit Fahrer",
  "С выездом к клиенту": "Mit Anfahrt zum Kunden",
  "С выездом к ученику": "Mit Anfahrt zum Schüler",
  "Сад и огород": "Garten und Gemüsegarten",
  "Садовая мебель": "Gartenmöbel",
  "Садовая техника": "Gartengeräte",
  "Садоводство (СНТ)": "Kleingarten (Gartengenossenschaft)",
  "Салон": "Innenraum",
  "Самозанятость": "Selbstständigkeit",
  "Сантехника": "Sanitär",
  "Сборка мебели": "Möbelmontage",
  "Свет": "Licht",
  "Свитеры и кофты": "Pullover und Strickjacken",
  "Свободное назначение": "Freie Nutzung",
  "Свободный": "Frei",
  "Сдать": "Vermieten",
  "Сдать в аренду": "Vermieten",
  "Сдать жильё": "Wohnung vermieten",
  "Седан": "Limousine",
  "Сельское хозяйство": "Landwirtschaft",
  "Сельхозживотные": "Nutztiere",
  "Сельхозназначение": "Landwirtschaftliche Nutzung",
  "Серебристый": "Silber",
  "Серый": "Grau",
  "Синий": "Blau",
  "Склад": "Lager",
  "Скутер": "Roller",
  "Сменный": "Schichtdienst",
  "Снимите со всех сторон — так вещь продаётся быстрее.": "Fotografieren Sie von allen Seiten — so verkauft sich der Artikel schneller.",
  "Снять": "Mieten",
  "Со своими средствами и техникой": "Mit eigenen Mitteln und Geräten",
  "Собаки": "Hunde",
  "Собственность": "Eigentum",
  "Состояние": "Zustand",
  "Состояние, история обслуживания, что менялось.": "Zustand, Wartungshistorie, was ausgetauscht wurde.",
  "Спальники": "Schlafsäcke",
  "Сплав и походы": "Rafting und Wandern",
  "Спорт": "Sport",
  "Спорт и отдых": "Sport und Freizeit",
  "Спорт и фитнес": "Sport und Fitness",
  "Спортивная одежда": "Sportbekleidung",
  "Среднее": "Mittlerer Abschluss",
  "Среднее специальное": "Fachschulabschluss",
  "Средний срок выполнения": "Durchschnittliche Ausführungsdauer",
  "Средняя школа": "Mittelschule",
  "Срок аренды": "Mietdauer",
  "Стаж вождения от": "Fahrpraxis ab",
  "Стажировка": "Praktikum",
  "Старшие классы": "Oberstufe",
  "Стекло": "Glas",
  "Стерилизован": "Sterilisiert",
  "Стиральная машина": "Waschmaschine",
  "Стол": "Tisch",
  "Строительство и ремонт": "Bau und Renovierung",
  "Стройматериалы": "Baumaterialien",
  "Струнные смычковые": "Streichinstrumente",
  "Студенты": "Studenten",
  "Студийное оборудование": "Studioausrüstung",
  "Студия": "Studio",
  "Стульчик для кормления": "Hochstuhl",
  "Стулья": "Stühle",
  "Сумки": "Taschen",
  "Сутки": "Tag",
  "Театр": "Theater",
  "Телевизор": "Fernseher",
  "Телевизоры и аудио": "Fernseher und Audio",
  "Телефоны": "Telefone",
  "Теплицы": "Gewächshäuser",
  "Тип": "Typ",
  "Тип билета": "Tickettyp",
  "Тип вещи": "Art des Artikels",
  "Тип жилья": "Wohnungstyp",
  "Тип запчасти": "Ersatzteiltyp",
  "Тип игрушки": "Spielzeugtyp",
  "Тип инструмента": "Werkzeugtyp",
  "Тип мебели": "Möbeltyp",
  "Тип объекта": "Objekttyp",
  "Тип снаряжения": "Ausrüstungstyp",
  "Тип техники": "Gerätetyp",
  "Тип товара": "Warentyp",
  "Тип топлива": "Kraftstoffart",
  "Тип устройства": "Gerätetyp",
  "Ткань": "Stoff",
  "Товары для животных": "Tierbedarf",
  "Только грузчики": "Nur Umzugshelfer",
  "Торговое": "Handelsfläche",
  "Транспорт": "Fahrzeuge",
  "Транспорт и логистика": "Transport und Logistik",
  "Трансфер включён": "Transfer inklusive",
  "Требования": "Anforderungen",
  "Требует ремонта": "Renovierungsbedürftig",
  "Тренажёры": "Fitnessgeräte",
  "Тур, экскурсия или снаряжение": "Tour, Ausflug oder Ausrüstung",
  "Туризм и походы": "Tourismus und Wandern",
  "Туристическое снаряжение": "Reiseausrüstung",
  "Туры и экскурсии": "Touren und Ausflüge",
  "Туры, экскурсии, снаряжение": "Touren, Ausflüge, Ausrüstung",
  "Тягач": "Sattelzugmaschine",
  "У преподавателя": "Beim Lehrer",
  "Уборка и помощь по хозяйству": "Reinigung und Haushaltshilfe",
  "Уборка после ремонта": "Reinigung nach Renovierung",
  "Удалённо": "Remote",
  "Удалённость от города": "Entfernung von der Stadt",
  "Ударные": "Schlaginstrumente",
  "Удовлетворительное": "Befriedigend",
  "Украшения": "Schmuck",
  "Уличные игрушки": "Spielzeug für draußen",
  "Универсал": "Kombi",
  "Универсальное": "Universell",
  "Унисекс": "Unisex",
  "Условия": "Bedingungen",
  "Условия передачи": "Übergabebedingungen",
  "Услуги": "Dienstleistungen",
  "Уход и гигиена": "Pflege und Hygiene",
  "Фестивали": "Festivals",
  "Физика": "Physik",
  "Финансы и бухгалтерия": "Finanzen und Buchhaltung",
  "Форма собственности": "Eigentumsform",
  "Формат занятий": "Unterrichtsformat",
  "Формат работы": "Arbeitsformat",
  "Фото выполненных работ": "Fotos abgeschlossener Arbeiten",
  "Фото и видеотехника": "Foto- und Videotechnik",
  "Фото работ": "Fotos der Arbeiten",
  "Фотоаппарат": "Kamera",
  "Фотографии": "Fotos",
  "Фургон": "Kastenwagen",
  "Характер, привычки, к чему приучен, почему передаёте.": "Charakter, Gewohnheiten, was das Tier gewohnt ist, Grund der Abgabe.",
  "Химия": "Chemie",
  "Химчистка мебели": "Polsterreinigung",
  "Хобби и отдых": "Hobby und Freizeit",
  "Холодильник": "Kühlschrank",
  "Хорошее": "Gut",
  "Хостел": "Hostel",
  "Хэтчбек": "Schrägheck",
  "Цвет": "Farbe",
  "Цена": "Preis",
  "Цена за билет": "Preis pro Ticket",
  "Цена за занятие от": "Preis pro Stunde ab",
  "Цена за месяц": "Preis pro Monat",
  "Цена за сутки": "Preis pro Tag",
  "Цена от": "Preis ab",
  "Цена с человека": "Preis pro Person",
  "Час": "Stunde",
  "Частичная": "Teilzeit",
  "Частично": "Teilweise",
  "Частный мастер": "Privater Handwerker",
  "Частный специалист": "Privater Spezialist",
  "Часы": "Uhren",
  "Чем занимались, что умеете, чего ищете.": "Was Sie gemacht haben, was Sie können, wonach Sie suchen.",
  "Что в комплекте, были ли ремонты, есть ли дефекты.": "Was im Lieferumfang ist, ob es repariert wurde, ob es Mängel gibt.",
  "Что включено": "Was ist inklusive",
  "Что делаете, за какой срок, что входит в стоимость.": "Was Sie tun, in welchem Zeitrahmen, was im Preis enthalten ist.",
  "Что продаёте": "Was Sie verkaufen",
  "Что рядом, как заселение, что входит в стоимость.": "Was in der Nähe ist, wie der Check-in funktioniert, was im Preis enthalten ist.",
  "Что человек будет делать каждый день.": "Was die Person täglich tun wird.",
  "Чтобы работа нашла вас": "Damit der Job Sie findet",
  "Чёрный": "Schwarz",
  "Шины и диски": "Reifen und Felgen",
  "Ширина": "Breite",
  "Шкаф": "Schrank",
  "Штатив и стабилизаторы": "Stative und Gimbals",
  "Экскаватор": "Bagger",
  "Экскурсия": "Ausflug",
  "Экшн-камера": "Actionkamera",
  "Электрика": "Elektrik",
  "Электрическое": "Elektrisch",
  "Электричество": "Strom",
  "Электричество, газ": "Strom, Gas",
  "Электро": "Elektro",
  "Электроника": "Elektronik",
  "Эндуро": "Enduro",
  "Эпиляция": "Haarentfernung",
  "Этаж": "Etage",
  "Этажей": "Etagen",
  "Этажей в доме": "Etagen im Haus",
  "Юриспруденция": "Jurisprudenz",

  // Единицы измерения (unit у полей категорий)
  "дней": "Tage",
  "кадров": "Auslösungen",
  "кг": "kg",
  "км": "km",
  "л": "L",
  "лет": "Jahre",
  "м": "m",
  "м²": "m²",
  "мес.": "Mon.",
  "мин": "Min.",
  "см": "cm",
  "см³": "cm³",
  "соток": "Ar",
  "суток": "Tage",
  "т": "t",
  "\"": "\"",
  "%": "%",
  "₽": "₽",
};
