export const labels: Record<string, string> = {
  "0–1 год": "0–1 year",
  "0–6 мес.": "0–6 mo.",
  "1": "1",
  "1 ТБ": "1 TB",
  "100% от аренды": "100% of rent",
  "12+": "12+",
  "128 ГБ": "128 GB",
  "16 ГБ": "16 GB",
  "1–3 года": "1–3 years",
  "1–4 года": "1–4 years",
  "2": "2",
  "2/2": "2/2",
  "256 ГБ": "256 GB",
  "3": "3",
  "3 и более": "3 or more",
  "32 ГБ": "32 GB",
  "36": "36",
  "37": "37",
  "38": "38",
  "39": "39",
  "3–5 лет": "3–5 years",
  "3–6 лет": "3–6 years",
  "3–7 лет": "3–7 years",
  "4 ГБ": "4 GB",
  "4+": "4+",
  "40": "40",
  "41": "41",
  "42": "42",
  "43": "43",
  "44": "44",
  "45": "45",
  "4–7 лет": "4–7 years",
  "5/2": "5/2",
  "50% от аренды": "50% of rent",
  "512 ГБ": "512 GB",
  "6/1": "6/1",
  "64 ГБ": "64 GB",
  "6–18 мес.": "6–18 mo.",
  "7–12 лет": "7–12 years",
  "8 ГБ": "8 GB",
  "IT и интернет": "IT and internet",
  "IT, реклама и дизайн": "IT, advertising and design",
  "L": "L",
  "M": "M",
  "Nintendo": "Nintendo",
  "PC": "PC",
  "PlayStation": "PlayStation",
  "S": "S",
  "SMM и реклама": "SMM and advertising",
  "Smart TV": "Smart TV",
  "VIN или госномер": "VIN or plate number",
  "VR-гарнитура": "VR headset",
  "Wi-Fi": "Wi-Fi",
  "XL": "XL",
  "XS": "XS",
  "XXL": "XXL",
  "Xbox": "Xbox",
  "Ёмкости и баки": "Tanks and containers",
  "Ёмкость аккумулятора": "Battery capacity",
  "Авто": "Cars",
  "Авто и спецтехника напрокат": "Car and equipment rental",
  "Автобус": "Bus",
  "Автокресло": "Car seat",
  "Автомат": "Automatic",
  "Адрес": "Address",
  "Адрес или район": "Address or district",
  "Аквариумные": "Aquarium",
  "Аквариумы": "Aquariums",
  "Аксессуары": "Accessories",
  "Аксессуары и часы": "Accessories and watches",
  "Амуниция": "Tack",
  "Английский язык": "English",
  "Антиквариат": "Antiques",
  "Апартаменты": "Serviced apartments",
  "Аренда жилья и помещений": "Housing and property rental",
  "Арест": "Seized",
  "Асфальт": "Asphalt",
  "Б/у": "Used",
  "База отдыха": "Recreation resort",
  "Балкон или лоджия": "Balcony or loggia",
  "Без комиссии": "No commission",
  "Без мебели": "Unfurnished",
  "Без опыта": "No experience",
  "Без оформления": "Unofficial",
  "Без предоплаты": "No prepayment",
  "Без ремонта": "No renovation",
  "Без транспорта": "No vehicle",
  "Бездорожье": "Off-road",
  "Белый": "White",
  "Бензин": "Gasoline",
  "Билеты на события": "Event tickets",
  "Бокс": "Boxing",
  "Более 15 человек": "More than 15 people",
  "Более 5 лет": "More than 5 years",
  "Более 6 лет": "More than 6 years",
  "Бренд": "Brand",
  "Бригада": "Crew",
  "Брови и ресницы": "Eyebrows and eyelashes",
  "Брюки": "Trousers",
  "Брюки и джинсы": "Trousers and jeans",
  "Бустер": "Booster seat",
  "Бытовая техника": "Home appliances",
  "В вакансии — что предлагаете, в резюме — что ожидаете.": "For a job posting, describe what you offer; for a resume, what you expect.",
  "В добрые руки с договором": "Rehoming with an agreement",
  "В месяц": "Per month",
  "В офисе заказчика": "At client's office",
  "В салоне": "At the salon",
  "В собственности": "Owned",
  "Вариатор": "CVT",
  "Вахта": "Rotational work",
  "Велосипеды": "Bicycles",
  "Верхняя одежда": "Outerwear",
  "Взрослые": "Adults",
  "Взять в аренду": "Rent",
  "Вид животного": "Animal type",
  "Вид работ": "Type of work",
  "Вид разрешённого использования": "Permitted land use",
  "Вид услуги": "Service type",
  "Видеокамера": "Video camera",
  "Владельцев по ПТС": "Owners on record",
  "Внедорожник": "SUV",
  "Водительские права": "Driver's license",
  "Возможна доставка": "Delivery available",
  "Возможна ипотека": "Mortgage available",
  "Возраст": "Age",
  "Возраст водителя от": "Minimum driver age",
  "Возрастная группа": "Age group",
  "Все вакансии": "All jobs",
  "Все комнаты, санузел и кухня. Минимум 5 фото.": "All rooms, bathroom and kitchen. At least 5 photos.",
  "Все объекты в продаже": "All properties for sale",
  "Все объявления": "All listings",
  "Все предложения услуг": "All service listings",
  "Все резюме": "All resumes",
  "Все центральные": "All central areas",
  "Встроенная память": "Built-in storage",
  "Вывоз мусора": "Trash removal",
  "Выезд к заказчику": "On-site visit",
  "Выплаты": "Payouts",
  "Высота": "Height",
  "Высота потолков": "Ceiling height",
  "Выставки": "Exhibitions",
  "Высшее": "Higher education",
  "Газ": "Gas",
  "Газель": "Cargo van (Gazelle)",
  "Газоблок": "Aerated concrete",
  "Газовое": "Gas",
  "Гараж": "Garage",
  "Гараж и машиноместо": "Garage and parking space",
  "Гаражи и машиноместа": "Garages and parking spaces",
  "Гарантия действует": "Under warranty",
  "Гарантия на работы": "Work warranty",
  "Гастротур": "Food tour",
  "Где принимаете": "Where you see clients",
  "Геймпад": "Gamepad",
  "Генеральная уборка": "Deep cleaning",
  "Гибрид": "Hybrid",
  "Гитары": "Guitars",
  "Глубина": "Depth",
  "Год выпуска": "Year of manufacture",
  "Год постройки": "Year built",
  "Головные уборы": "Hats",
  "Горелки и посуда": "Burners and cookware",
  "Город": "City",
  "Город отправления": "Departure city",
  "Гостей": "Guests",
  "Готов к переезду": "Willing to relocate",
  "График": "Schedule",
  "Грузовик": "Truck",
  "Грузовик до 5 т": "Truck up to 5 t",
  "Грузовик свыше 5 т": "Truck over 5 t",
  "Грузовики и спецтехника": "Trucks and heavy equipment",
  "Грузоподъёмность": "Load capacity",
  "Грузчики": "Movers",
  "Грунт": "Soil",
  "Грызуны": "Rodents",
  "Да": "Yes",
  "Дата события": "Event date",
  "Два раза в месяц": "Twice a month",
  "Двери": "Doors",
  "Двигатель": "Engine",
  "Девочка": "Girl",
  "Дерево": "Wood",
  "Дети и детские услуги": "Kids and children's services",
  "Детская мебель": "Kids' furniture",
  "Детская одежда и обувь": "Kids' clothing and shoes",
  "Детское": "Kids'",
  "Диагональ": "Screen size",
  "Диагональ экрана": "Screen diagonal",
  "Диван": "Sofa",
  "Дизайн": "Design",
  "Дизайнерский": "Designer",
  "Дизель": "Diesel",
  "Длительно (от года)": "Long-term (1+ year)",
  "Длительность занятия": "Lesson duration",
  "Для дома": "For home",
  "Для кого": "For whom",
  "Для марки": "For make",
  "До 15 человек": "Up to 15 people",
  "До 5 человек": "Up to 5 people",
  "До года": "Under 1 year",
  "Договор ГПХ": "Civil-law contract",
  "Долевая собственность": "Shared ownership",
  "Дом": "House",
  "Дом, дача, таунхаус": "House, cottage, townhouse",
  "Дома и дачи": "Houses and cottages",
  "Домашний кинотеатр": "Home theater",
  "Домашний персонал": "Domestic staff",
  "Домики и лежанки": "Pet houses and beds",
  "Допустимый вес ребёнка": "Max child weight",
  "Дорожный": "Road",
  "Доставка мебели": "Furniture delivery",
  "Дошкольники": "Preschoolers",
  "Другая": "Other",
  "Другие языки": "Other languages",
  "Духовые": "Wind instruments",
  "Евроремонт": "Euro renovation",
  "Единица расчёта": "Unit of measure",
  "Единоборства": "Martial arts",
  "Ежедневно": "Daily",
  "Еженедельно": "Weekly",
  "Есть": "Available",
  "Есть автомобиль": "Has a car",
  "Есть документы и родословная": "Has papers and pedigree",
  "Есть сертификат или диплом": "Has certificate or diploma",
  "ЖКХ и благоустройство": "Utilities and improvement",
  "Женское": "Women's",
  "Животные": "Animals",
  "Живые фото питомца, а не изображения породы из интернета.": "Real photos of the pet, not breed pictures from the internet.",
  "За два месяца": "For two months",
  "За заказ": "Per order",
  "За км": "Per km",
  "За м²": "Per m²",
  "За месяц": "Per month",
  "За метр погонный": "Per linear meter",
  "За проект": "Per project",
  "За услугу": "Per service",
  "За час": "Per hour",
  "Задний": "Rear-wheel",
  "Залог": "Deposit",
  "Занятость": "Employment type",
  "Заполним марку, модель, год и двигатель автоматически. Можно ввести данные вручную.": "We'll fill in the make, model, year and engine automatically. You can also enter the details manually.",
  "Запчасти и аксессуары": "Parts and accessories",
  "Зарплата от": "Salary from",
  "Земельные участки": "Land plots",
  "Земельный участок": "Land plot",
  "Зимний спорт": "Winter sports",
  "Значки": "Badges",
  "ИЖС": "Residential construction land",
  "Игра": "Game",
  "Игровая приставка": "Game console",
  "Игрушки": "Toys",
  "Игрушки и товары для игр": "Toys and game goods",
  "Игры и приставки": "Games and consoles",
  "Индивидуально": "One-on-one",
  "Индивидуальный гид": "Private guide",
  "Инструменты": "Tools",
  "Информатика": "Computer science",
  "Ипотека": "Mortgage",
  "Искусство и творчество": "Art and creativity",
  "Кадастровый номер": "Cadastral number",
  "Каркас": "Frame",
  "Квартира": "Apartment",
  "Квартирный переезд": "Apartment move",
  "Квартиры": "Apartments",
  "Кино": "Movies",
  "Кирпич": "Brick",
  "Клавишные": "Keyboard instruments",
  "Клетки и переноски": "Cages and carriers",
  "Клининговая компания": "Cleaning company",
  "Книги": "Books",
  "Книги и коллекционирование": "Books and collectibles",
  "Кожа": "Leather",
  "Количество билетов": "Number of tickets",
  "Колонки": "Speakers",
  "Коляска 2 в 1": "Stroller 2-in-1",
  "Коляска 3 в 1": "Stroller 3-in-1",
  "Коляска-люлька": "Bassinet stroller",
  "Коляски и автокресла": "Strollers and car seats",
  "Командные виды": "Team sports",
  "Комбинезоны": "Overalls",
  "Комиссия агента": "Agent commission",
  "Коммерческая недвижимость": "Commercial real estate",
  "Коммерческое": "Commercial",
  "Коммунальные включены": "Utilities included",
  "Коммуникации": "Utilities",
  "Комнат": "Rooms",
  "Комната": "Room",
  "Комод": "Dresser",
  "Компания": "Company",
  "Кондиционер": "Air conditioner",
  "Конструкторы": "Building sets",
  "Концерты": "Concerts",
  "Копирайтинг": "Copywriting",
  "Корма": "Feed",
  "Коробка передач": "Transmission",
  "Коротко и по делу — это первое, что видит покупатель.": "Short and to the point — it's the first thing a buyer sees.",
  "Коротко и по делу — это первое, что видит человек.": "Short and to the point — it's the first thing people see.",
  "Косметика": "Cosmetics",
  "Косметический": "Cosmetic",
  "Косметология": "Cosmetology",
  "Кофты и футболки": "Sweaters and T-shirts",
  "Кошки": "Cats",
  "Кран": "Crane",
  "Красный": "Red",
  "Красота и здоровье": "Beauty and health",
  "Кроватка": "Crib",
  "Кровать": "Bed",
  "Кровля": "Roofing",
  "Кросс": "Motocross",
  "Круизер": "Cruiser",
  "Кто оказывает услугу": "Who provides the service",
  "Кузов": "Body type",
  "Куклы": "Dolls",
  "Купе": "Coupe",
  "Купить": "Buy",
  "Кухонный гарнитур": "Kitchen set",
  "ЛДСП": "Laminated chipboard",
  "ЛПХ": "Personal farming land",
  "Легковые авто": "Passenger cars",
  "Лимит пробега в сутки": "Daily mileage limit",
  "Личные вещи": "Personal items",
  "Макияж": "Makeup",
  "Мальчик": "Boy",
  "Манеж": "Playpen",
  "Маникюр и педикюр": "Manicure and pedicure",
  "Марка": "Make",
  "Маркетинг и медиа": "Marketing and media",
  "Марки": "Stamps",
  "Массаж": "Massage",
  "Математика": "Math",
  "Материал": "Material",
  "Материал стен": "Wall material",
  "Машинки": "Toy cars",
  "Машиноместо": "Parking space",
  "Мебель": "Furniture",
  "Мебель и интерьер": "Furniture and decor",
  "Медиаплеер": "Media player",
  "Медицинские товары": "Medical supplies",
  "Междугородние перевозки": "Intercity transport",
  "Менее года": "Less than a year",
  "Месяц": "Month",
  "Металл": "Metal",
  "Механика": "Manual",
  "Микроволновка": "Microwave",
  "Минивэн": "Minivan",
  "Минимальный срок": "Minimum term",
  "Минимум 3 фото — объявления с фото смотрят в 4 раза чаще.": "At least 3 photos — listings with photos get viewed 4x more often.",
  "Минимум 3 фото, включая экран во включённом состоянии.": "At least 3 photos, including the screen turned on.",
  "Минимум 3 фото.": "At least 3 photos.",
  "Минимум 3 фото: спереди, сзади, салон.": "At least 3 photos: front, back, interior.",
  "Многодневный тур": "Multi-day tour",
  "Мобильные приложения": "Mobile apps",
  "Модели и фигурки": "Models and figurines",
  "Модель": "Model",
  "Можно без опыта": "No experience needed",
  "Можно с детьми": "Kids allowed",
  "Можно с животными": "Pets allowed",
  "Монеты": "Coins",
  "Моноблок": "All-in-one PC",
  "Морская прогулка": "Boat trip",
  "Мотоциклы и мототехника": "Motorcycles and powersports",
  "Мужское": "Men's",
  "Музыка": "Music",
  "Музыкальные инструменты": "Musical instruments",
  "Муниципальная": "Municipal",
  "Мытьё окон": "Window cleaning",
  "Мягкие игрушки": "Plush toys",
  "На дому у мастера": "At the specialist's place",
  "На месте": "On-site",
  "На несколько месяцев": "For a few months",
  "Навигация": "Navigation",
  "Навыки": "Skills",
  "Название компании": "Company name",
  "Название объявления": "Listing title",
  "Назначение": "Zoning",
  "Найти жильё": "Find housing",
  "Найти исполнителя": "Find a pro",
  "Найти питомца или товар": "Find a pet or supplies",
  "Найти работу": "Find a job",
  "Найти сотрудника": "Find an employee",
  "Найти тур или снаряжение": "Find a tour or gear",
  "Найти человека в команду": "Find a team member",
  "Накопитель": "Storage drive",
  "Напольные покрытия": "Flooring",
  "Направление": "Destination",
  "Например: 15 октября 2026": "For example: October 15, 2026",
  "Населённый пункт": "Locality",
  "Настольные игры": "Board games",
  "Настольный компьютер": "Desktop computer",
  "Настройка сетей": "Network setup",
  "Наука и инженерия": "Science and engineering",
  "Наушники": "Headphones",
  "Начальная школа": "Elementary school",
  "Недвижимость": "Real estate",
  "Неделя": "Week",
  "Незаконченное высшее": "Incomplete higher education",
  "Необязательно. Требовать возраст в вакансиях запрещено законом.": "Optional. Requiring age in job postings is prohibited by law.",
  "Нет": "No",
  "Новое": "New",
  "Новое без бирки": "New without tags",
  "Новое вскрытое": "New, opened",
  "Новое запечатанное": "New, sealed",
  "Новое с биркой": "New with tags",
  "Ноутбук": "Laptop",
  "Ноутбуки и компьютеры": "Laptops and computers",
  "О себе": "About me",
  "О себе и методике": "About me and my approach",
  "Образование": "Education",
  "Обременения": "Encumbrances",
  "Обувь": "Shoes",
  "Обучение и репетиторы": "Lessons and tutors",
  "Объектив": "Lens",
  "Объём двигателя": "Engine size",
  "Обязанности": "Responsibilities",
  "Огорожен": "Fenced",
  "Одежда для походов": "Hiking clothing",
  "Одежда и обувь": "Clothing and shoes",
  "Окна": "Windows",
  "Окна и двери": "Windows and doors",
  "Онлайн": "Online",
  "Оперативная память": "RAM",
  "Описание": "Description",
  "Описание маршрута": "Route description",
  "Описание услуги": "Service description",
  "Описание услуги и портфолио": "Service description and portfolio",
  "Опыт преподавания": "Teaching experience",
  "Опыт работы": "Work experience",
  "Оставьте пустым, если залога нет.": "Leave blank if there is no deposit.",
  "Оставьте пустым, если отдаёте даром.": "Leave blank if giving it away for free.",
  "Отдам даром": "Free to a good home",
  "Отделочные работы": "Finishing work",
  "Отдельный вход": "Separate entrance",
  "Открытки": "Postcards",
  "Отличное": "Excellent",
  "Отопление": "Heating",
  "Офис": "Office",
  "Офис и администрация": "Office and admin",
  "Офисный переезд": "Office move",
  "Оформление": "Employment terms",
  "Оформление, отпуск, что оплачивается.": "Employment terms, vacation, what's covered.",
  "Охрана": "Security",
  "Охрана и безопасность": "Security and safety",
  "Очки": "Glasses",
  "Палатки": "Tents",
  "Панель": "Panel",
  "Парикмахерские услуги": "Hairdressing services",
  "Парковка": "Parking",
  "Парта": "Desk",
  "Парфюмерия": "Perfume",
  "Пеленальный столик": "Changing table",
  "Первое занятие бесплатно": "First lesson free",
  "Перевозки и грузчики": "Moving and movers",
  "Передний": "Front-wheel",
  "Переуступка": "Assignment of rights",
  "Печное": "Stove",
  "Планшет": "Tablet",
  "Платформа": "Platform",
  "Платья": "Dresses",
  "Плита": "Stove",
  "Плитка": "Tile",
  "Площадь": "Area",
  "Площадь дома": "House area",
  "Площадь участка": "Plot area",
  "По ТК РФ": "Official employment",
  "По договорённости": "By agreement",
  "По номеру заполним площадь, вид использования и границы. Можно пропустить.": "We'll fill in the area, land use and boundaries from the number. You can skip this.",
  "Погрузчик": "Loader",
  "Подвеска": "Suspension",
  "Подготовка к ЕГЭ и ОГЭ": "Exam prep (state exams)",
  "Поддерживающая уборка": "Maintenance cleaning",
  "Подработка": "Side gig",
  "Подростковое": "Teen",
  "Подходит студентам": "Good for students",
  "Подъездная дорога": "Access road",
  "Покажите вещь целиком и вблизи — фактуру и возможные дефекты.": "Show the item in full and up close — texture and any flaws.",
  "Покажите крепления и ремни — это первое, что смотрят родители.": "Show the straps and fasteners — that's the first thing parents check.",
  "Пол": "Gender",
  "Полки": "Shelves",
  "Полная": "Full-time",
  "Полностью меблирована": "Fully furnished",
  "Полный": "All-wheel",
  "Полный комплект": "Full set",
  "Помощь по хозяйству": "Household help",
  "Порода": "Breed",
  "Портфолио повышает отклик в разы. Минимум 3 фото.": "A portfolio boosts responses significantly. At least 3 photos.",
  "Портфолио — главный аргумент в этой категории.": "A portfolio is the strongest argument in this category.",
  "Последнее место работы": "Last place of work",
  "Посудомоечная машина": "Dishwasher",
  "Посуточная аренда": "Daily rental",
  "Посуточная аренда жилья": "Daily housing rental",
  "Посуточно": "Daily",
  "Предложить услугу": "Offer a service",
  "Предмет или направление": "Subject or field",
  "Предоплата": "Prepayment",
  "Приборы для ухода": "Care devices",
  "Прививки сделаны": "Vaccinated",
  "Привод": "Drivetrain",
  "Пробег": "Mileage",
  "Пробег затвора": "Shutter count",
  "Прогулочная коляска": "Lightweight stroller",
  "Продажа": "Sale",
  "Продажа или отдам даром": "Sale or free",
  "Продажи и торговля": "Sales and retail",
  "Продать": "Sell",
  "Продолжительность": "Duration",
  "Проектор": "Projector",
  "Проживание, питание, трансфер, входные билеты.": "Accommodation, meals, transfer, entrance tickets.",
  "Производство": "Manufacturing",
  "Профессия": "Profession",
  "Процессор": "Processor",
  "Птицы": "Birds",
  "Путешествия": "Travel",
  "Пылесос": "Vacuum cleaner",
  "Работа": "Jobs",
  "Работаю круглосуточно": "Available 24/7",
  "Работаю по договору": "Work under contract",
  "Раз в месяц": "Once a month",
  "Развивающие": "Educational",
  "Размер": "Size",
  "Размер группы": "Group size",
  "Разместить вакансию": "Post a job",
  "Разместить объявление": "Post a listing",
  "Разместить объявление о продаже": "Post a listing for sale",
  "Разместить объявление об аренде": "Post a rental listing",
  "Разместить предложение": "Post an offer",
  "Разместить резюме": "Post a resume",
  "Разместить своё объявление": "Post your listing",
  "Разработка сайтов": "Website development",
  "Растения и саженцы": "Plants and seedlings",
  "Ремни": "Straps",
  "Ремонт": "Renovation",
  "Ремонт и строительство": "Renovation and construction",
  "Ремонт и стройматериалы": "Renovation and building materials",
  "Ремонт компьютеров": "Computer repair",
  "Ремонт под ключ": "Turnkey renovation",
  "Рента": "Annuity agreement",
  "Рестораны и гостиницы": "Restaurants and hotels",
  "Робот": "Robot",
  "Рубашки и блузки": "Shirts and blouses",
  "Русский язык": "Russian",
  "Рыбалка": "Fishing",
  "Рыбы": "Fish",
  "Рюкзаки": "Backpacks",
  "С водителем": "With driver",
  "С выездом к клиенту": "Comes to the client",
  "С выездом к ученику": "Comes to the student",
  "Сад и огород": "Garden and allotment",
  "Садовая мебель": "Garden furniture",
  "Садовая техника": "Garden equipment",
  "Садоводство (СНТ)": "Gardening association land",
  "Салон": "Interior",
  "Самозанятость": "Self-employment",
  "Сантехника": "Plumbing",
  "Сборка мебели": "Furniture assembly",
  "Свет": "Lighting",
  "Свитеры и кофты": "Sweaters and cardigans",
  "Свободное назначение": "Unrestricted use",
  "Свободный": "Vacant",
  "Сдать": "Rent out",
  "Сдать в аренду": "Rent out",
  "Сдать жильё": "Rent out housing",
  "Седан": "Sedan",
  "Сельское хозяйство": "Agriculture",
  "Сельхозживотные": "Farm animals",
  "Сельхозназначение": "Agricultural use",
  "Серебристый": "Silver",
  "Серый": "Gray",
  "Синий": "Blue",
  "Склад": "Warehouse",
  "Скутер": "Scooter",
  "Сменный": "Shift",
  "Снимите со всех сторон — так вещь продаётся быстрее.": "Photograph it from every angle — it sells faster that way.",
  "Снять": "Rent",
  "Со своими средствами и техникой": "With own supplies and equipment",
  "Собаки": "Dogs",
  "Собственность": "Private ownership",
  "Состояние": "Condition",
  "Состояние, история обслуживания, что менялось.": "Condition, service history, what's been replaced.",
  "Спальники": "Sleeping bags",
  "Сплав и походы": "Rafting and hiking",
  "Спорт": "Sports",
  "Спорт и отдых": "Sports and recreation",
  "Спорт и фитнес": "Sports and fitness",
  "Спортивная одежда": "Sportswear",
  "Среднее": "Secondary education",
  "Среднее специальное": "Vocational education",
  "Средний срок выполнения": "Average turnaround time",
  "Средняя школа": "Middle school",
  "Срок аренды": "Rental term",
  "Стаж вождения от": "Minimum driving experience",
  "Стажировка": "Internship",
  "Старшие классы": "High school",
  "Стекло": "Glass",
  "Стерилизован": "Spayed/neutered",
  "Стиральная машина": "Washing machine",
  "Стол": "Table",
  "Строительство и ремонт": "Construction and renovation",
  "Стройматериалы": "Building materials",
  "Струнные смычковые": "Bowed string instruments",
  "Студенты": "Students",
  "Студийное оборудование": "Studio equipment",
  "Студия": "Studio",
  "Стульчик для кормления": "High chair",
  "Стулья": "Chairs",
  "Сумки": "Bags",
  "Сутки": "Per day",
  "Театр": "Theater",
  "Телевизор": "TV",
  "Телевизоры и аудио": "TVs and audio",
  "Телефоны": "Phones",
  "Теплицы": "Greenhouses",
  "Тип": "Type",
  "Тип билета": "Ticket type",
  "Тип вещи": "Item type",
  "Тип жилья": "Housing type",
  "Тип запчасти": "Part type",
  "Тип игрушки": "Toy type",
  "Тип инструмента": "Tool type",
  "Тип мебели": "Furniture type",
  "Тип объекта": "Property type",
  "Тип снаряжения": "Gear type",
  "Тип техники": "Equipment type",
  "Тип товара": "Item type",
  "Тип топлива": "Fuel type",
  "Тип устройства": "Device type",
  "Ткань": "Fabric",
  "Товары для животных": "Pet supplies",
  "Только грузчики": "Movers only",
  "Торговое": "Retail",
  "Транспорт": "Vehicles",
  "Транспорт и логистика": "Transport and logistics",
  "Трансфер включён": "Transfer included",
  "Требования": "Requirements",
  "Требует ремонта": "Needs renovation",
  "Тренажёры": "Exercise equipment",
  "Тур, экскурсия или снаряжение": "Tour, excursion or gear",
  "Туризм и походы": "Tourism and hiking",
  "Туристическое снаряжение": "Camping gear",
  "Туры и экскурсии": "Tours and excursions",
  "Туры, экскурсии, снаряжение": "Tours, excursions, gear",
  "Тягач": "Tractor unit",
  "У преподавателя": "At the tutor's place",
  "Уборка и помощь по хозяйству": "Cleaning and household help",
  "Уборка после ремонта": "Post-renovation cleaning",
  "Удалённо": "Remote",
  "Удалённость от города": "Distance from city",
  "Ударные": "Percussion",
  "Удовлетворительное": "Fair",
  "Украшения": "Jewelry",
  "Уличные игрушки": "Outdoor toys",
  "Универсал": "Wagon",
  "Универсальное": "Universal",
  "Унисекс": "Unisex",
  "Условия": "Terms",
  "Условия передачи": "Handover terms",
  "Услуги": "Services",
  "Уход и гигиена": "Care and hygiene",
  "Фестивали": "Festivals",
  "Физика": "Physics",
  "Финансы и бухгалтерия": "Finance and accounting",
  "Форма собственности": "Ownership type",
  "Формат занятий": "Lesson format",
  "Формат работы": "Work format",
  "Фото выполненных работ": "Photos of completed work",
  "Фото и видеотехника": "Photo and video equipment",
  "Фото работ": "Photos of work",
  "Фотоаппарат": "Camera",
  "Фотографии": "Photos",
  "Фургон": "Van",
  "Характер, привычки, к чему приучен, почему передаёте.": "Temperament, habits, what it's trained for, why you're rehoming it.",
  "Химия": "Chemistry",
  "Химчистка мебели": "Furniture dry cleaning",
  "Хобби и отдых": "Hobbies and leisure",
  "Холодильник": "Refrigerator",
  "Хорошее": "Good",
  "Хостел": "Hostel",
  "Хэтчбек": "Hatchback",
  "Цвет": "Color",
  "Цена": "Price",
  "Цена за билет": "Price per ticket",
  "Цена за занятие от": "Price per lesson from",
  "Цена за месяц": "Price per month",
  "Цена за сутки": "Price per day",
  "Цена от": "Price from",
  "Цена с человека": "Price per person",
  "Час": "Hour",
  "Частичная": "Part-time",
  "Частично": "Partially",
  "Частный мастер": "Private specialist",
  "Частный специалист": "Private specialist",
  "Часы": "Watches",
  "Чем занимались, что умеете, чего ищете.": "What you've done, what you can do, what you're looking for.",
  "Что в комплекте, были ли ремонты, есть ли дефекты.": "What's included, any repairs, any defects.",
  "Что включено": "What's included",
  "Что делаете, за какой срок, что входит в стоимость.": "What you do, how long it takes, what's included in the price.",
  "Что продаёте": "What you're selling",
  "Что рядом, как заселение, что входит в стоимость.": "What's nearby, check-in process, what's included in the price.",
  "Что человек будет делать каждый день.": "What the person will do every day.",
  "Чтобы работа нашла вас": "Let the job find you",
  "Чёрный": "Black",
  "Шины и диски": "Tires and wheels",
  "Ширина": "Width",
  "Шкаф": "Wardrobe",
  "Штатив и стабилизаторы": "Tripods and stabilizers",
  "Экскаватор": "Excavator",
  "Экскурсия": "Excursion",
  "Экшн-камера": "Action camera",
  "Электрика": "Electrical work",
  "Электрическое": "Electric",
  "Электричество": "Electricity",
  "Электричество, газ": "Electricity, gas",
  "Электро": "Electric",
  "Электроника": "Electronics",
  "Эндуро": "Enduro",
  "Эпиляция": "Hair removal",
  "Этаж": "Floor",
  "Этажей": "Floors",
  "Этажей в доме": "Floors in building",
  "Юриспруденция": "Law",

  // Единицы измерения (unit у полей категорий)
  "дней": "days",
  "кадров": "shots",
  "кг": "kg",
  "км": "km",
  "л": "L",
  "лет": "years",
  "м": "m",
  "м²": "m²",
  "мес.": "mo.",
  "мин": "min",
  "см": "cm",
  "см³": "cm³",
  "соток": "ares",
  "суток": "days",
  "т": "t",
  "\"": "\"",
  "%": "%",
  "₽": "₽",
};
