export const labels: Record<string, string> = {
  "0–1 год": "0–1 año",
  "0–6 мес.": "0–6 meses",
  "1": "1",
  "1 ТБ": "1 TB",
  "100% от аренды": "100 % del alquiler",
  "12+": "12+",
  "128 ГБ": "128 GB",
  "16 ГБ": "16 GB",
  "1–3 года": "1–3 años",
  "1–4 года": "1–4 años",
  "2": "2",
  "2/2": "2/2",
  "256 ГБ": "256 GB",
  "3": "3",
  "3 и более": "3 o más",
  "32 ГБ": "32 GB",
  "36": "36",
  "37": "37",
  "38": "38",
  "39": "39",
  "3–5 лет": "3–5 años",
  "3–6 лет": "3–6 años",
  "3–7 лет": "3–7 años",
  "4 ГБ": "4 GB",
  "4+": "4+",
  "40": "40",
  "41": "41",
  "42": "42",
  "43": "43",
  "44": "44",
  "45": "45",
  "4–7 лет": "4–7 años",
  "5/2": "5/2",
  "50% от аренды": "50 % del alquiler",
  "512 ГБ": "512 GB",
  "6/1": "6/1",
  "64 ГБ": "64 GB",
  "6–18 мес.": "6–18 meses",
  "7–12 лет": "7–12 años",
  "8 ГБ": "8 GB",
  "IT и интернет": "TI e internet",
  "IT, реклама и дизайн": "TI, publicidad y diseño",
  "L": "L",
  "M": "M",
  "Nintendo": "Nintendo",
  "PC": "PC",
  "PlayStation": "PlayStation",
  "S": "S",
  "SMM и реклама": "SMM y publicidad",
  "Smart TV": "Smart TV",
  "VIN или госномер": "VIN o matrícula",
  "VR-гарнитура": "Gafas de VR",
  "Wi-Fi": "Wi-Fi",
  "XL": "XL",
  "XS": "XS",
  "XXL": "XXL",
  "Xbox": "Xbox",
  "Ёмкости и баки": "Depósitos y tanques",
  "Ёмкость аккумулятора": "Capacidad de la batería",
  "Авто": "Autos",
  "Авто и спецтехника напрокат": "Alquiler de autos y maquinaria",
  "Автобус": "Autobús",
  "Автокресло": "Silla de auto",
  "Автомат": "Automática",
  "Адрес": "Dirección",
  "Адрес или район": "Dirección o barrio",
  "Аквариумные": "De acuario",
  "Аквариумы": "Acuarios",
  "Аксессуары": "Accesorios",
  "Аксессуары и часы": "Accesorios y relojes",
  "Амуниция": "Arreos y equipamiento",
  "Английский язык": "Inglés",
  "Антиквариат": "Antigüedades",
  "Апартаменты": "Apartamentos",
  "Аренда жилья и помещений": "Alquiler de vivienda y locales",
  "Арест": "Embargo",
  "Асфальт": "Asfalto",
  "Б/у": "Usado",
  "База отдыха": "Centro vacacional",
  "Балкон или лоджия": "Balcón o galería",
  "Без комиссии": "Sin comisión",
  "Без мебели": "Sin muebles",
  "Без опыта": "Sin experiencia",
  "Без оформления": "Sin contrato",
  "Без предоплаты": "Sin adelanto",
  "Без ремонта": "Sin reformar",
  "Без транспорта": "Sin vehículo",
  "Бездорожье": "Todoterreno",
  "Белый": "Blanco",
  "Бензин": "Gasolina",
  "Билеты на события": "Entradas para eventos",
  "Бокс": "Boxeo",
  "Более 15 человек": "Más de 15 personas",
  "Более 5 лет": "Más de 5 años",
  "Более 6 лет": "Más de 6 años",
  "Бренд": "Marca",
  "Бригада": "Cuadrilla",
  "Брови и ресницы": "Cejas y pestañas",
  "Брюки": "Pantalones",
  "Брюки и джинсы": "Pantalones y jeans",
  "Бустер": "Elevador",
  "Бытовая техника": "Electrodomésticos",
  "В вакансии — что предлагаете, в резюме — что ожидаете.": "En la vacante, qué ofreces; en el CV, qué esperas.",
  "В добрые руки с договором": "En adopción, con contrato",
  "В месяц": "Al mes",
  "В офисе заказчика": "En la oficina del cliente",
  "В салоне": "En el salón",
  "В собственности": "En propiedad",
  "Вариатор": "CVT",
  "Вахта": "Turno rotativo",
  "Велосипеды": "Bicicletas",
  "Верхняя одежда": "Ropa de abrigo",
  "Взрослые": "Adultos",
  "Взять в аренду": "Alquilar",
  "Вид животного": "Tipo de animal",
  "Вид работ": "Tipo de trabajo",
  "Вид разрешённого использования": "Uso permitido",
  "Вид услуги": "Tipo de servicio",
  "Видеокамера": "Videocámara",
  "Владельцев по ПТС": "Propietarios según ficha técnica",
  "Внедорожник": "Todoterreno (SUV)",
  "Водительские права": "Carné de conducir",
  "Возможна доставка": "Envío disponible",
  "Возможна ипотека": "Hipoteca disponible",
  "Возраст": "Edad",
  "Возраст водителя от": "Edad mínima del conductor",
  "Возрастная группа": "Grupo de edad",
  "Все вакансии": "Todas las vacantes",
  "Все комнаты, санузел и кухня. Минимум 5 фото.": "Todas las habitaciones, baño y cocina. Mínimo 5 fotos.",
  "Все объекты в продаже": "Todos los inmuebles en venta",
  "Все объявления": "Todos los anuncios",
  "Все предложения услуг": "Todas las ofertas de servicios",
  "Все резюме": "Todos los CV",
  "Все центральные": "Todos los céntricos",
  "Встроенная память": "Almacenamiento interno",
  "Вывоз мусора": "Retiro de basura",
  "Выезд к заказчику": "Desplazamiento al cliente",
  "Выплаты": "Pagos",
  "Высота": "Altura",
  "Высота потолков": "Altura de techos",
  "Выставки": "Exposiciones",
  "Высшее": "Superior",
  "Газ": "Gas",
  "Газель": "Furgoneta (Gazelle)",
  "Газоблок": "Bloque de hormigón celular",
  "Газовое": "A gas",
  "Гараж": "Garaje",
  "Гараж и машиноместо": "Garaje y plaza de aparcamiento",
  "Гаражи и машиноместа": "Garajes y plazas de aparcamiento",
  "Гарантия действует": "En garantía",
  "Гарантия на работы": "Garantía del trabajo",
  "Гастротур": "Ruta gastronómica",
  "Где принимаете": "Dónde atiendes",
  "Геймпад": "Mando de videojuegos",
  "Генеральная уборка": "Limpieza a fondo",
  "Гибрид": "Híbrido",
  "Гитары": "Guitarras",
  "Глубина": "Profundidad",
  "Год выпуска": "Año de fabricación",
  "Год постройки": "Año de construcción",
  "Головные уборы": "Sombreros y gorros",
  "Горелки и посуда": "Hornillos y menaje",
  "Город": "Ciudad",
  "Город отправления": "Ciudad de salida",
  "Гостей": "Huéspedes",
  "Готов к переезду": "Dispuesto a mudarse",
  "График": "Horario",
  "Грузовик": "Camión",
  "Грузовик до 5 т": "Camión hasta 5 t",
  "Грузовик свыше 5 т": "Camión de más de 5 t",
  "Грузовики и спецтехника": "Camiones y maquinaria",
  "Грузоподъёмность": "Capacidad de carga",
  "Грузчики": "Mozos de carga",
  "Грунт": "Tierra",
  "Грызуны": "Roedores",
  "Да": "Sí",
  "Дата события": "Fecha del evento",
  "Два раза в месяц": "Dos veces al mes",
  "Двери": "Puertas",
  "Двигатель": "Motor",
  "Девочка": "Niña",
  "Дерево": "Madera",
  "Дети и детские услуги": "Niños y servicios infantiles",
  "Детская мебель": "Muebles infantiles",
  "Детская одежда и обувь": "Ropa y calzado infantil",
  "Детское": "Infantil",
  "Диагональ": "Diagonal",
  "Диагональ экрана": "Diagonal de pantalla",
  "Диван": "Sofá",
  "Дизайн": "Diseño",
  "Дизайнерский": "De diseño",
  "Дизель": "Diésel",
  "Длительно (от года)": "Larga duración (desde 1 año)",
  "Длительность занятия": "Duración de la clase",
  "Для дома": "Para el hogar",
  "Для кого": "Para quién",
  "Для марки": "Para la marca",
  "До 15 человек": "Hasta 15 personas",
  "До 5 человек": "Hasta 5 personas",
  "До года": "Menos de 1 año",
  "Договор ГПХ": "Contrato civil",
  "Долевая собственность": "Copropiedad",
  "Дом": "Casa",
  "Дом, дача, таунхаус": "Casa, chalet o adosado",
  "Дома и дачи": "Casas y chalets",
  "Домашний кинотеатр": "Cine en casa",
  "Домашний персонал": "Personal doméstico",
  "Домики и лежанки": "Casitas y camas para mascotas",
  "Допустимый вес ребёнка": "Peso máximo del niño",
  "Дорожный": "De carretera",
  "Доставка мебели": "Transporte de muebles",
  "Дошкольники": "Preescolares",
  "Другая": "Otra",
  "Другие языки": "Otros idiomas",
  "Духовые": "Instrumentos de viento",
  "Евроремонт": "Reforma de alta calidad",
  "Единица расчёта": "Unidad de cálculo",
  "Единоборства": "Artes marciales",
  "Ежедневно": "A diario",
  "Еженедельно": "Semanalmente",
  "Есть": "Sí tiene",
  "Есть автомобиль": "Tiene vehículo propio",
  "Есть документы и родословная": "Tiene documentos y pedigrí",
  "Есть сертификат или диплом": "Tiene certificado o diploma",
  "ЖКХ и благоустройство": "Servicios comunitarios y urbanismo",
  "Женское": "Mujer",
  "Животные": "Mascotas",
  "Живые фото питомца, а не изображения породы из интернета.": "Fotos reales de la mascota, no imágenes de la raza sacadas de internet.",
  "За два месяца": "Por dos meses",
  "За заказ": "Por pedido",
  "За км": "Por km",
  "За м²": "Por m²",
  "За месяц": "Por mes",
  "За метр погонный": "Por metro lineal",
  "За проект": "Por proyecto",
  "За услугу": "Por servicio",
  "За час": "Por hora",
  "Задний": "Trasero",
  "Залог": "Depósito",
  "Занятость": "Jornada",
  "Заполним марку, модель, год и двигатель автоматически. Можно ввести данные вручную.": "Completaremos automáticamente la marca, el modelo, el año y el motor. También puedes introducir los datos manualmente.",
  "Запчасти и аксессуары": "Repuestos y accesorios",
  "Зарплата от": "Salario desde",
  "Земельные участки": "Terrenos",
  "Земельный участок": "Terreno",
  "Зимний спорт": "Deportes de invierno",
  "Значки": "Insignias",
  "ИЖС": "Vivienda unifamiliar",
  "Игра": "Juego",
  "Игровая приставка": "Consola de videojuegos",
  "Игрушки": "Juguetes",
  "Игрушки и товары для игр": "Juguetes y artículos de juego",
  "Игры и приставки": "Juegos y consolas",
  "Индивидуально": "Individual",
  "Индивидуальный гид": "Guía privado",
  "Инструменты": "Herramientas",
  "Информатика": "Informática",
  "Ипотека": "Hipoteca",
  "Искусство и творчество": "Arte y manualidades",
  "Кадастровый номер": "Número catastral",
  "Каркас": "Estructura",
  "Квартира": "Piso",
  "Квартирный переезд": "Mudanza de piso",
  "Квартиры": "Pisos",
  "Кино": "Cine",
  "Кирпич": "Ladrillo",
  "Клавишные": "Instrumentos de teclado",
  "Клетки и переноски": "Jaulas y transportines",
  "Клининговая компания": "Empresa de limpieza",
  "Книги": "Libros",
  "Книги и коллекционирование": "Libros y coleccionismo",
  "Кожа": "Cuero",
  "Количество билетов": "Número de entradas",
  "Колонки": "Altavoces",
  "Коляска 2 в 1": "Cochecito 2 en 1",
  "Коляска 3 в 1": "Cochecito 3 en 1",
  "Коляска-люлька": "Cochecito capazo",
  "Коляски и автокресла": "Cochecitos y sillas de auto",
  "Командные виды": "Deportes de equipo",
  "Комбинезоны": "Monos y peleles",
  "Комиссия агента": "Comisión del agente",
  "Коммерческая недвижимость": "Inmuebles comerciales",
  "Коммерческое": "Comercial",
  "Коммунальные включены": "Gastos comunes incluidos",
  "Коммуникации": "Suministros",
  "Комнат": "Habitaciones",
  "Комната": "Habitación",
  "Комод": "Cómoda",
  "Компания": "Empresa",
  "Кондиционер": "Aire acondicionado",
  "Конструкторы": "Juegos de construcción",
  "Концерты": "Conciertos",
  "Копирайтинг": "Redacción publicitaria",
  "Корма": "Piensos",
  "Коробка передач": "Caja de cambios",
  "Коротко и по делу — это первое, что видит покупатель.": "Breve y directo: es lo primero que ve el comprador.",
  "Коротко и по делу — это первое, что видит человек.": "Breve y directo: es lo primero que ve la persona.",
  "Косметика": "Cosmética",
  "Косметический": "Estético",
  "Косметология": "Cosmetología",
  "Кофты и футболки": "Sudaderas y camisetas",
  "Кошки": "Gatos",
  "Кран": "Grúa",
  "Красный": "Rojo",
  "Красота и здоровье": "Belleza y salud",
  "Кроватка": "Cuna",
  "Кровать": "Cama",
  "Кровля": "Cubierta",
  "Кросс": "Cross",
  "Круизер": "Crucero (moto)",
  "Кто оказывает услугу": "Quién presta el servicio",
  "Кузов": "Carrocería",
  "Куклы": "Muñecas",
  "Купе": "Cupé",
  "Купить": "Comprar",
  "Кухонный гарнитур": "Mueble de cocina",
  "ЛДСП": "Aglomerado laminado",
  "ЛПХ": "Explotación familiar",
  "Легковые авто": "Turismos",
  "Лимит пробега в сутки": "Límite de kilometraje diario",
  "Личные вещи": "Objetos personales",
  "Макияж": "Maquillaje",
  "Мальчик": "Niño",
  "Манеж": "Parque infantil",
  "Маникюр и педикюр": "Manicura y pedicura",
  "Марка": "Marca",
  "Маркетинг и медиа": "Marketing y medios",
  "Марки": "Marcas",
  "Массаж": "Masaje",
  "Математика": "Matemáticas",
  "Материал": "Material",
  "Материал стен": "Material de las paredes",
  "Машинки": "Cochecitos de juguete",
  "Машиноместо": "Plaza de aparcamiento",
  "Мебель": "Muebles",
  "Мебель и интерьер": "Muebles y decoración",
  "Медиаплеер": "Reproductor multimedia",
  "Медицинские товары": "Artículos médicos",
  "Междугородние перевозки": "Transporte interurbano",
  "Менее года": "Menos de 1 año",
  "Месяц": "Mes",
  "Металл": "Metal",
  "Механика": "Manual",
  "Микроволновка": "Microondas",
  "Минивэн": "Monovolumen",
  "Минимальный срок": "Duración mínima",
  "Минимум 3 фото — объявления с фото смотрят в 4 раза чаще.": "Mínimo 3 fotos: los anuncios con fotos se ven 4 veces más.",
  "Минимум 3 фото, включая экран во включённом состоянии.": "Mínimo 3 fotos, incluida la pantalla encendida.",
  "Минимум 3 фото.": "Mínimo 3 fotos.",
  "Минимум 3 фото: спереди, сзади, салон.": "Mínimo 3 fotos: delante, detrás e interior.",
  "Многодневный тур": "Tour de varios días",
  "Мобильные приложения": "Aplicaciones móviles",
  "Модели и фигурки": "Modelos y figuras",
  "Модель": "Modelo",
  "Можно без опыта": "Sin experiencia previa",
  "Можно с детьми": "Se admiten niños",
  "Можно с животными": "Se admiten mascotas",
  "Монеты": "Monedas",
  "Моноблок": "Ordenador todo en uno",
  "Морская прогулка": "Paseo en barco",
  "Мотоциклы и мототехника": "Motos y vehículos motorizados",
  "Мужское": "Hombre",
  "Музыка": "Música",
  "Музыкальные инструменты": "Instrumentos musicales",
  "Муниципальная": "Municipal",
  "Мытьё окон": "Limpieza de ventanas",
  "Мягкие игрушки": "Peluches",
  "На дому у мастера": "En casa del profesional",
  "На месте": "En el lugar",
  "На несколько месяцев": "Por varios meses",
  "Навигация": "Navegación",
  "Навыки": "Habilidades",
  "Название компании": "Nombre de la empresa",
  "Название объявления": "Título del anuncio",
  "Назначение": "Uso",
  "Найти жильё": "Buscar vivienda",
  "Найти исполнителя": "Buscar profesional",
  "Найти питомца или товар": "Buscar mascota o producto",
  "Найти работу": "Buscar empleo",
  "Найти сотрудника": "Buscar empleado",
  "Найти тур или снаряжение": "Buscar tour o equipo",
  "Найти человека в команду": "Buscar personal para el equipo",
  "Накопитель": "Almacenamiento",
  "Напольные покрытия": "Revestimientos de suelo",
  "Направление": "Dirección",
  "Например: 15 октября 2026": "Por ejemplo: 15 de octubre de 2026",
  "Населённый пункт": "Localidad",
  "Настольные игры": "Juegos de mesa",
  "Настольный компьютер": "Ordenador de escritorio",
  "Настройка сетей": "Configuración de redes",
  "Наука и инженерия": "Ciencia e ingeniería",
  "Наушники": "Auriculares",
  "Начальная школа": "Primaria",
  "Недвижимость": "Inmuebles",
  "Неделя": "Semana",
  "Незаконченное высшее": "Superior incompleta",
  "Необязательно. Требовать возраст в вакансиях запрещено законом.": "Opcional. La ley prohíbe exigir la edad en las ofertas de empleo.",
  "Нет": "No",
  "Новое": "Nuevo",
  "Новое без бирки": "Nuevo sin etiqueta",
  "Новое вскрытое": "Nuevo abierto",
  "Новое запечатанное": "Nuevo sellado",
  "Новое с биркой": "Nuevo con etiqueta",
  "Ноутбук": "Portátil",
  "Ноутбуки и компьютеры": "Portátiles y ordenadores",
  "О себе": "Sobre mí",
  "О себе и методике": "Sobre mí y mi metodología",
  "Образование": "Educación",
  "Обременения": "Cargas",
  "Обувь": "Calzado",
  "Обучение и репетиторы": "Formación y clases particulares",
  "Объектив": "Objetivo",
  "Объём двигателя": "Cilindrada",
  "Обязанности": "Responsabilidades",
  "Огорожен": "Vallado",
  "Одежда для походов": "Ropa de senderismo",
  "Одежда и обувь": "Ropa y calzado",
  "Окна": "Ventanas",
  "Окна и двери": "Ventanas y puertas",
  "Онлайн": "En línea",
  "Оперативная память": "Memoria RAM",
  "Описание": "Descripción",
  "Описание маршрута": "Descripción de la ruta",
  "Описание услуги": "Descripción del servicio",
  "Описание услуги и портфолио": "Descripción del servicio y portafolio",
  "Опыт преподавания": "Experiencia docente",
  "Опыт работы": "Experiencia laboral",
  "Оставьте пустым, если залога нет.": "Déjalo en blanco si no hay depósito.",
  "Оставьте пустым, если отдаёте даром.": "Déjalo en blanco si lo regalas.",
  "Отдам даром": "Lo regalo",
  "Отделочные работы": "Acabados",
  "Отдельный вход": "Entrada independiente",
  "Открытки": "Postales",
  "Отличное": "Excelente",
  "Отопление": "Calefacción",
  "Офис": "Oficina",
  "Офис и администрация": "Oficina y administración",
  "Офисный переезд": "Mudanza de oficina",
  "Оформление": "Trámites",
  "Оформление, отпуск, что оплачивается.": "Contrato, vacaciones, qué se paga.",
  "Охрана": "Seguridad",
  "Охрана и безопасность": "Seguridad y vigilancia",
  "Очки": "Gafas",
  "Палатки": "Tiendas de campaña",
  "Панель": "Panel",
  "Парикмахерские услуги": "Servicios de peluquería",
  "Парковка": "Aparcamiento",
  "Парта": "Pupitre",
  "Парфюмерия": "Perfumería",
  "Пеленальный столик": "Cambiador",
  "Первое занятие бесплатно": "Primera clase gratis",
  "Перевозки и грузчики": "Mudanzas y mozos de carga",
  "Передний": "Delantero",
  "Переуступка": "Cesión de derechos",
  "Печное": "De estufa",
  "Планшет": "Tableta",
  "Платформа": "Plataforma",
  "Платья": "Vestidos",
  "Плита": "Cocina (electrodoméstico)",
  "Плитка": "Baldosa",
  "Площадь": "Superficie",
  "Площадь дома": "Superficie de la casa",
  "Площадь участка": "Superficie del terreno",
  "По ТК РФ": "Con contrato laboral",
  "По договорённости": "A convenir",
  "По номеру заполним площадь, вид использования и границы. Можно пропустить.": "Con el número completaremos la superficie, el uso y los límites. Puedes omitirlo.",
  "Погрузчик": "Cargadora",
  "Подвеска": "Suspensión",
  "Подготовка к ЕГЭ и ОГЭ": "Preparación de exámenes estatales",
  "Поддерживающая уборка": "Limpieza de mantenimiento",
  "Подработка": "Trabajo extra",
  "Подростковое": "Adolescente",
  "Подходит студентам": "Apto para estudiantes",
  "Подъездная дорога": "Camino de acceso",
  "Покажите вещь целиком и вблизи — фактуру и возможные дефекты.": "Muestra el artículo completo y de cerca: la textura y posibles defectos.",
  "Покажите крепления и ремни — это первое, что смотрят родители.": "Muestra los anclajes y los cinturones: es lo primero que miran los padres.",
  "Пол": "Sexo",
  "Полки": "Estantes",
  "Полная": "Completa",
  "Полностью меблирована": "Totalmente amueblada",
  "Полный": "Completo",
  "Полный комплект": "Juego completo",
  "Помощь по хозяйству": "Ayuda doméstica",
  "Порода": "Raza",
  "Портфолио повышает отклик в разы. Минимум 3 фото.": "El portafolio multiplica las respuestas. Mínimo 3 fotos.",
  "Портфолио — главный аргумент в этой категории.": "El portafolio es el argumento principal en esta categoría.",
  "Последнее место работы": "Último empleo",
  "Посудомоечная машина": "Lavavajillas",
  "Посуточная аренда": "Alquiler por días",
  "Посуточная аренда жилья": "Alquiler de vivienda por días",
  "Посуточно": "Por días",
  "Предложить услугу": "Ofrecer un servicio",
  "Предмет или направление": "Materia o especialidad",
  "Предоплата": "Adelanto",
  "Приборы для ухода": "Aparatos de cuidado personal",
  "Прививки сделаны": "Vacunas al día",
  "Привод": "Tracción",
  "Пробег": "Kilometraje",
  "Пробег затвора": "Disparos del obturador",
  "Прогулочная коляска": "Silla de paseo",
  "Продажа": "Venta",
  "Продажа или отдам даром": "Venta o lo regalo",
  "Продажи и торговля": "Ventas y comercio",
  "Продать": "Vender",
  "Продолжительность": "Duración",
  "Проектор": "Proyector",
  "Проживание, питание, трансфер, входные билеты.": "Alojamiento, comidas, traslado, entradas.",
  "Производство": "Producción",
  "Профессия": "Profesión",
  "Процессор": "Procesador",
  "Птицы": "Aves",
  "Путешествия": "Viajes",
  "Пылесос": "Aspiradora",
  "Работа": "Empleo",
  "Работаю круглосуточно": "Trabajo las 24 horas",
  "Работаю по договору": "Trabajo con contrato",
  "Раз в месяц": "Una vez al mes",
  "Развивающие": "Educativos",
  "Размер": "Talla",
  "Размер группы": "Tamaño del grupo",
  "Разместить вакансию": "Publicar vacante",
  "Разместить объявление": "Publicar anuncio",
  "Разместить объявление о продаже": "Publicar anuncio de venta",
  "Разместить объявление об аренде": "Publicar anuncio de alquiler",
  "Разместить предложение": "Publicar oferta",
  "Разместить резюме": "Publicar CV",
  "Разместить своё объявление": "Publicar tu anuncio",
  "Разработка сайтов": "Desarrollo web",
  "Растения и саженцы": "Plantas y plantones",
  "Ремни": "Cinturones",
  "Ремонт": "Reforma",
  "Ремонт и строительство": "Reforma y construcción",
  "Ремонт и стройматериалы": "Reforma y materiales de construcción",
  "Ремонт компьютеров": "Reparación de ordenadores",
  "Ремонт под ключ": "Reforma llave en mano",
  "Рента": "Renta vitalicia",
  "Рестораны и гостиницы": "Restaurantes y hoteles",
  "Робот": "Robot",
  "Рубашки и блузки": "Camisas y blusas",
  "Русский язык": "Ruso",
  "Рыбалка": "Pesca",
  "Рыбы": "Peces",
  "Рюкзаки": "Mochilas",
  "С водителем": "Con conductor",
  "С выездом к клиенту": "Con desplazamiento al cliente",
  "С выездом к ученику": "Con desplazamiento al alumno",
  "Сад и огород": "Jardín y huerto",
  "Садовая мебель": "Muebles de jardín",
  "Садовая техника": "Maquinaria de jardín",
  "Садоводство (СНТ)": "Uso agrícola (asociación de jardineros)",
  "Салон": "Salón",
  "Самозанятость": "Autónomo",
  "Сантехника": "Fontanería",
  "Сборка мебели": "Montaje de muebles",
  "Свет": "Iluminación",
  "Свитеры и кофты": "Suéteres y sudaderas",
  "Свободное назначение": "Uso libre",
  "Свободный": "Libre",
  "Сдать": "Alquilar (como propietario)",
  "Сдать в аренду": "Poner en alquiler",
  "Сдать жильё": "Alquilar vivienda",
  "Седан": "Sedán",
  "Сельское хозяйство": "Agricultura",
  "Сельхозживотные": "Animales de granja",
  "Сельхозназначение": "Uso agrícola",
  "Серебристый": "Plateado",
  "Серый": "Gris",
  "Синий": "Azul",
  "Склад": "Almacén",
  "Скутер": "Escúter",
  "Сменный": "Por turnos",
  "Снимите со всех сторон — так вещь продаётся быстрее.": "Fotografía el artículo por todos los lados: así se vende más rápido.",
  "Снять": "Alquilar (como inquilino)",
  "Со своими средствами и техникой": "Con productos y equipo propios",
  "Собаки": "Perros",
  "Собственность": "Propiedad",
  "Состояние": "Estado",
  "Состояние, история обслуживания, что менялось.": "Estado, historial de mantenimiento, qué se cambió.",
  "Спальники": "Sacos de dormir",
  "Сплав и походы": "Descenso en balsa y senderismo",
  "Спорт": "Deporte",
  "Спорт и отдых": "Deporte y ocio",
  "Спорт и фитнес": "Deporte y fitness",
  "Спортивная одежда": "Ropa deportiva",
  "Среднее": "Secundaria",
  "Среднее специальное": "Formación profesional",
  "Средний срок выполнения": "Plazo medio de entrega",
  "Средняя школа": "Secundaria",
  "Срок аренды": "Duración del alquiler",
  "Стаж вождения от": "Experiencia de conducción mínima",
  "Стажировка": "Prácticas",
  "Старшие классы": "Bachillerato",
  "Стекло": "Vidrio",
  "Стерилизован": "Esterilizado",
  "Стиральная машина": "Lavadora",
  "Стол": "Mesa",
  "Строительство и ремонт": "Construcción y reforma",
  "Стройматериалы": "Materiales de construcción",
  "Струнные смычковые": "Instrumentos de cuerda frotada",
  "Студенты": "Estudiantes",
  "Студийное оборудование": "Equipo de estudio",
  "Студия": "Estudio",
  "Стульчик для кормления": "Trona",
  "Стулья": "Sillas",
  "Сумки": "Bolsos",
  "Сутки": "Día (24 h)",
  "Театр": "Teatro",
  "Телевизор": "Televisor",
  "Телевизоры и аудио": "Televisores y audio",
  "Телефоны": "Teléfonos",
  "Теплицы": "Invernaderos",
  "Тип": "Tipo",
  "Тип билета": "Tipo de entrada",
  "Тип вещи": "Tipo de artículo",
  "Тип жилья": "Tipo de vivienda",
  "Тип запчасти": "Tipo de repuesto",
  "Тип игрушки": "Tipo de juguete",
  "Тип инструмента": "Tipo de herramienta",
  "Тип мебели": "Tipo de mueble",
  "Тип объекта": "Tipo de inmueble",
  "Тип снаряжения": "Tipo de equipo",
  "Тип техники": "Tipo de maquinaria",
  "Тип товара": "Tipo de producto",
  "Тип топлива": "Tipo de combustible",
  "Тип устройства": "Tipo de dispositivo",
  "Ткань": "Tela",
  "Товары для животных": "Artículos para mascotas",
  "Только грузчики": "Solo mozos de carga",
  "Торговое": "Comercial",
  "Транспорт": "Transporte",
  "Транспорт и логистика": "Transporte y logística",
  "Трансфер включён": "Traslado incluido",
  "Требования": "Requisitos",
  "Требует ремонта": "Necesita reforma",
  "Тренажёры": "Aparatos de gimnasio",
  "Тур, экскурсия или снаряжение": "Tour, excursión o equipo",
  "Туризм и походы": "Turismo y senderismo",
  "Туристическое снаряжение": "Equipo de camping",
  "Туры и экскурсии": "Tours y excursiones",
  "Туры, экскурсии, снаряжение": "Tours, excursiones, equipo",
  "Тягач": "Tractocamión",
  "У преподавателя": "En casa del profesor",
  "Уборка и помощь по хозяйству": "Limpieza y ayuda doméstica",
  "Уборка после ремонта": "Limpieza tras reforma",
  "Удалённо": "A distancia",
  "Удалённость от города": "Distancia a la ciudad",
  "Ударные": "Instrumentos de percusión",
  "Удовлетворительное": "Aceptable",
  "Украшения": "Joyas",
  "Уличные игрушки": "Juguetes de exterior",
  "Универсал": "Familiar (station wagon)",
  "Универсальное": "Universal",
  "Унисекс": "Unisex",
  "Условия": "Condiciones",
  "Условия передачи": "Condiciones de entrega",
  "Услуги": "Servicios",
  "Уход и гигиена": "Cuidado e higiene",
  "Фестивали": "Festivales",
  "Физика": "Física",
  "Финансы и бухгалтерия": "Finanzas y contabilidad",
  "Форма собственности": "Régimen de propiedad",
  "Формат занятий": "Formato de las clases",
  "Формат работы": "Formato de trabajo",
  "Фото выполненных работ": "Fotos de trabajos realizados",
  "Фото и видеотехника": "Fotografía y video",
  "Фото работ": "Fotos de trabajos",
  "Фотоаппарат": "Cámara fotográfica",
  "Фотографии": "Fotografías",
  "Фургон": "Furgón",
  "Характер, привычки, к чему приучен, почему передаёте.": "Carácter, hábitos, a qué está acostumbrado, por qué lo entregas.",
  "Химия": "Química",
  "Химчистка мебели": "Limpieza en seco de muebles",
  "Хобби и отдых": "Aficiones y ocio",
  "Холодильник": "Refrigerador",
  "Хорошее": "Bueno",
  "Хостел": "Hostal",
  "Хэтчбек": "Hatchback",
  "Цвет": "Color",
  "Цена": "Precio",
  "Цена за билет": "Precio por entrada",
  "Цена за занятие от": "Precio por clase desde",
  "Цена за месяц": "Precio por mes",
  "Цена за сутки": "Precio por día",
  "Цена от": "Precio desde",
  "Цена с человека": "Precio por persona",
  "Час": "Hora",
  "Частичная": "Parcial",
  "Частично": "Parcialmente",
  "Частный мастер": "Profesional independiente",
  "Частный специалист": "Especialista independiente",
  "Часы": "Relojes",
  "Чем занимались, что умеете, чего ищете.": "A qué te has dedicado, qué sabes hacer, qué buscas.",
  "Что в комплекте, были ли ремонты, есть ли дефекты.": "Qué incluye, si tuvo reparaciones, si tiene defectos.",
  "Что включено": "Qué incluye",
  "Что делаете, за какой срок, что входит в стоимость.": "Qué haces, en cuánto tiempo, qué incluye el precio.",
  "Что продаёте": "Qué vendes",
  "Что рядом, как заселение, что входит в стоимость.": "Qué hay cerca, cómo es el check-in, qué incluye el precio.",
  "Что человек будет делать каждый день.": "Qué hará la persona cada día.",
  "Чтобы работа нашла вас": "Para que el empleo te encuentre",
  "Чёрный": "Negro",
  "Шины и диски": "Neumáticos y llantas",
  "Ширина": "Ancho",
  "Шкаф": "Armario",
  "Штатив и стабилизаторы": "Trípodes y estabilizadores",
  "Экскаватор": "Excavadora",
  "Экскурсия": "Excursión",
  "Экшн-камера": "Cámara de acción",
  "Электрика": "Electricidad",
  "Электрическое": "Eléctrico",
  "Электричество": "Electricidad",
  "Электричество, газ": "Electricidad, gas",
  "Электро": "Eléctrico",
  "Электроника": "Electrónica",
  "Эндуро": "Enduro",
  "Эпиляция": "Depilación",
  "Этаж": "Piso (planta)",
  "Этажей": "Plantas",
  "Этажей в доме": "Plantas del edificio",
  "Юриспруденция": "Derecho",

  // Единицы измерения (unit у полей категорий)
  "дней": "días",
  "кадров": "disparos",
  "кг": "kg",
  "км": "km",
  "л": "L",
  "лет": "años",
  "м": "m",
  "м²": "m²",
  "мес.": "meses",
  "мин": "min",
  "см": "cm",
  "см³": "cm³",
  "соток": "áreas",
  "суток": "días",
  "т": "t",
  "\"": "\"",
  "%": "%",
  "₽": "₽",
};
