export const labels: Record<string, string> = {
  "0–1 год": "0 à 1 an",
  "0–6 мес.": "0 à 6 mois",
  "1": "1",
  "1 ТБ": "1 To",
  "100% от аренды": "100 % du loyer",
  "12+": "12+",
  "128 ГБ": "128 Go",
  "16 ГБ": "16 Go",
  "1–3 года": "1 à 3 ans",
  "1–4 года": "1 à 4 ans",
  "2": "2",
  "2/2": "2/2",
  "256 ГБ": "256 Go",
  "3": "3",
  "3 и более": "3 et plus",
  "32 ГБ": "32 Go",
  "36": "36",
  "37": "37",
  "38": "38",
  "39": "39",
  "3–5 лет": "3 à 5 ans",
  "3–6 лет": "3 à 6 ans",
  "3–7 лет": "3 à 7 ans",
  "4 ГБ": "4 Go",
  "4+": "4+",
  "40": "40",
  "41": "41",
  "42": "42",
  "43": "43",
  "44": "44",
  "45": "45",
  "4–7 лет": "4 à 7 ans",
  "5/2": "5/2",
  "50% от аренды": "50 % du loyer",
  "512 ГБ": "512 Go",
  "6/1": "6/1",
  "64 ГБ": "64 Go",
  "6–18 мес.": "6 à 18 mois",
  "7–12 лет": "7 à 12 ans",
  "8 ГБ": "8 Go",
  "IT и интернет": "IT et internet",
  "IT, реклама и дизайн": "IT, publicité et design",
  "L": "L",
  "M": "M",
  "Nintendo": "Nintendo",
  "PC": "PC",
  "PlayStation": "PlayStation",
  "S": "S",
  "SMM и реклама": "SMM et publicité",
  "Smart TV": "Smart TV",
  "VIN или госномер": "VIN ou plaque d'immatriculation",
  "VR-гарнитура": "Casque VR",
  "Wi-Fi": "Wi-Fi",
  "XL": "XL",
  "XS": "XS",
  "XXL": "XXL",
  "Xbox": "Xbox",
  "Ёмкости и баки": "Cuves et réservoirs",
  "Ёмкость аккумулятора": "Capacité de la batterie",
  "Авто": "Auto",
  "Авто и спецтехника напрокат": "Location de véhicules et engins",
  "Автобус": "Autobus",
  "Автокресло": "Siège auto",
  "Автомат": "Automatique",
  "Адрес": "Adresse",
  "Адрес или район": "Adresse ou quartier",
  "Аквариумные": "Poissons d'aquarium",
  "Аквариумы": "Aquariums",
  "Аксессуары": "Accessoires",
  "Аксессуары и часы": "Accessoires et montres",
  "Амуниция": "Équipement",
  "Английский язык": "Anglais",
  "Антиквариат": "Antiquités",
  "Апартаменты": "Appartement",
  "Аренда жилья и помещений": "Location de logements et locaux",
  "Арест": "Saisie",
  "Асфальт": "Asphalte",
  "Б/у": "Occasion",
  "База отдыха": "Base de loisirs",
  "Балкон или лоджия": "Balcon ou loggia",
  "Без комиссии": "Sans commission",
  "Без мебели": "Non meublé",
  "Без опыта": "Sans expérience",
  "Без оформления": "Sans contrat",
  "Без предоплаты": "Sans acompte",
  "Без ремонта": "Sans travaux",
  "Без транспорта": "Sans véhicule",
  "Бездорожье": "Tout-terrain",
  "Белый": "Blanc",
  "Бензин": "Essence",
  "Билеты на события": "Billetterie événements",
  "Бокс": "Boxe",
  "Более 15 человек": "Plus de 15 personnes",
  "Более 5 лет": "Plus de 5 ans",
  "Более 6 лет": "Plus de 6 ans",
  "Бренд": "Marque",
  "Бригада": "Équipe",
  "Брови и ресницы": "Sourcils et cils",
  "Брюки": "Pantalons",
  "Брюки и джинсы": "Pantalons et jeans",
  "Бустер": "Réhausseur",
  "Бытовая техника": "Électroménager",
  "В вакансии — что предлагаете, в резюме — что ожидаете.": "Dans une offre, indiquez ce que vous proposez ; dans un CV, ce que vous recherchez.",
  "В добрые руки с договором": "Don à de bonnes mains, avec contrat",
  "В месяц": "Par mois",
  "В офисе заказчика": "Chez le client",
  "В салоне": "En salon",
  "В собственности": "En pleine propriété",
  "Вариатор": "Boîte CVT",
  "Вахта": "Travail en rotation",
  "Велосипеды": "Vélos",
  "Верхняя одежда": "Vêtements d'extérieur",
  "Взрослые": "Adultes",
  "Взять в аренду": "Louer",
  "Вид животного": "Type d'animal",
  "Вид работ": "Type de travaux",
  "Вид разрешённого использования": "Usage autorisé",
  "Вид услуги": "Type de service",
  "Видеокамера": "Caméscope",
  "Владельцев по ПТС": "Nombre de propriétaires (carte grise)",
  "Внедорожник": "SUV",
  "Водительские права": "Permis de conduire",
  "Возможна доставка": "Livraison possible",
  "Возможна ипотека": "Crédit immobilier possible",
  "Возраст": "Âge",
  "Возраст водителя от": "Âge minimum du conducteur",
  "Возрастная группа": "Tranche d'âge",
  "Все вакансии": "Toutes les offres d'emploi",
  "Все комнаты, санузел и кухня. Минимум 5 фото.": "Toutes les pièces, la salle de bain et la cuisine. 5 photos minimum.",
  "Все объекты в продаже": "Tous les biens à vendre",
  "Все объявления": "Toutes les annonces",
  "Все предложения услуг": "Toutes les offres de services",
  "Все резюме": "Tous les CV",
  "Все центральные": "Tous les quartiers centraux",
  "Встроенная память": "Mémoire interne",
  "Вывоз мусора": "Enlèvement des déchets",
  "Выезд к заказчику": "Déplacement chez le client",
  "Выплаты": "Rémunération",
  "Высота": "Hauteur",
  "Высота потолков": "Hauteur sous plafond",
  "Выставки": "Expositions",
  "Высшее": "Supérieur",
  "Газ": "Gaz",
  "Газель": "Fourgon (Gazelle)",
  "Газоблок": "Bloc de béton cellulaire",
  "Газовое": "Au gaz",
  "Гараж": "Garage",
  "Гараж и машиноместо": "Garage et place de parking",
  "Гаражи и машиноместа": "Garages et places de parking",
  "Гарантия действует": "Sous garantie",
  "Гарантия на работы": "Garantie sur les travaux",
  "Гастротур": "Circuit gastronomique",
  "Где принимаете": "Lieu de réception",
  "Геймпад": "Manette de jeu",
  "Генеральная уборка": "Ménage en profondeur",
  "Гибрид": "Hybride",
  "Гитары": "Guitares",
  "Глубина": "Profondeur",
  "Год выпуска": "Année de fabrication",
  "Год постройки": "Année de construction",
  "Головные уборы": "Chapeaux et bonnets",
  "Горелки и посуда": "Réchauds et ustensiles",
  "Город": "Ville",
  "Город отправления": "Ville de départ",
  "Гостей": "Voyageurs",
  "Готов к переезду": "Prêt à déménager",
  "График": "Horaires",
  "Грузовик": "Camion",
  "Грузовик до 5 т": "Camion jusqu'à 5 t",
  "Грузовик свыше 5 т": "Camion de plus de 5 t",
  "Грузовики и спецтехника": "Camions et engins",
  "Грузоподъёмность": "Charge utile",
  "Грузчики": "Déménageurs",
  "Грунт": "Terre végétale",
  "Грызуны": "Rongeurs",
  "Да": "Oui",
  "Дата события": "Date de l'événement",
  "Два раза в месяц": "Deux fois par mois",
  "Двери": "Portes",
  "Двигатель": "Moteur",
  "Девочка": "Fille",
  "Дерево": "Bois",
  "Дети и детские услуги": "Enfants et services pour enfants",
  "Детская мебель": "Mobilier enfant",
  "Детская одежда и обувь": "Vêtements et chaussures enfant",
  "Детское": "Enfant",
  "Диагональ": "Diagonale",
  "Диагональ экрана": "Diagonale de l'écran",
  "Диван": "Canapé",
  "Дизайн": "Design",
  "Дизайнерский": "Design d'auteur",
  "Дизель": "Diesel",
  "Длительно (от года)": "Longue durée (à partir d'un an)",
  "Длительность занятия": "Durée de la séance",
  "Для дома": "Pour la maison",
  "Для кого": "Pour qui",
  "Для марки": "Pour la marque",
  "До 15 человек": "Jusqu'à 15 personnes",
  "До 5 человек": "Jusqu'à 5 personnes",
  "До года": "Moins d'un an",
  "Договор ГПХ": "Contrat de prestation (droit civil)",
  "Долевая собственность": "Copropriété",
  "Дом": "Maison",
  "Дом, дача, таунхаус": "Maison, datcha, maison de ville",
  "Дома и дачи": "Maisons et datchas",
  "Домашний кинотеатр": "Home cinéma",
  "Домашний персонал": "Personnel de maison",
  "Домики и лежанки": "Niches et couchages",
  "Допустимый вес ребёнка": "Poids maximal de l'enfant",
  "Дорожный": "Routier",
  "Доставка мебели": "Livraison de meubles",
  "Дошкольники": "Préscolaire",
  "Другая": "Autre",
  "Другие языки": "Autres langues",
  "Духовые": "Instruments à vent",
  "Евроремонт": "Rénovation haut de gamme",
  "Единица расчёта": "Unité de calcul",
  "Единоборства": "Sports de combat",
  "Ежедневно": "Quotidien",
  "Еженедельно": "Hebdomadaire",
  "Есть": "Oui",
  "Есть автомобиль": "Véhicule personnel",
  "Есть документы и родословная": "Papiers et pedigree",
  "Есть сертификат или диплом": "Certificat ou diplôme",
  "ЖКХ и благоустройство": "Services publics et aménagement",
  "Женское": "Femme",
  "Животные": "Animaux",
  "Живые фото питомца, а не изображения породы из интернета.": "De vraies photos de l'animal, pas des images de la race trouvées en ligne.",
  "За два месяца": "Pour deux mois",
  "За заказ": "Par commande",
  "За км": "Par km",
  "За м²": "Par m²",
  "За месяц": "Par mois",
  "За метр погонный": "Par mètre linéaire",
  "За проект": "Par projet",
  "За услугу": "Par prestation",
  "За час": "Par heure",
  "Задний": "Arrière",
  "Залог": "Dépôt de garantie",
  "Занятость": "Type de contrat",
  "Заполним марку, модель, год и двигатель автоматически. Можно ввести данные вручную.": "La marque, le modèle, l'année et le moteur seront renseignés automatiquement. Vous pouvez aussi les saisir manuellement.",
  "Запчасти и аксессуары": "Pièces et accessoires",
  "Зарплата от": "Salaire à partir de",
  "Земельные участки": "Terrains",
  "Земельный участок": "Terrain",
  "Зимний спорт": "Sports d'hiver",
  "Значки": "Pins et badges",
  "ИЖС": "Terrain constructible (habitat individuel)",
  "Игра": "Jeu",
  "Игровая приставка": "Console de jeux",
  "Игрушки": "Jouets",
  "Игрушки и товары для игр": "Jouets et articles de jeu",
  "Игры и приставки": "Jeux et consoles",
  "Индивидуально": "Individuel",
  "Индивидуальный гид": "Guide privé",
  "Инструменты": "Outils",
  "Информатика": "Informatique",
  "Ипотека": "Crédit immobilier",
  "Искусство и творчество": "Art et créativité",
  "Кадастровый номер": "Numéro cadastral",
  "Каркас": "Ossature",
  "Квартира": "Appartement",
  "Квартирный переезд": "Déménagement d'appartement",
  "Квартиры": "Appartements",
  "Кино": "Cinéma",
  "Кирпич": "Brique",
  "Клавишные": "Instruments à clavier",
  "Клетки и переноски": "Cages et caisses de transport",
  "Клининговая компания": "Entreprise de nettoyage",
  "Книги": "Livres",
  "Книги и коллекционирование": "Livres et objets de collection",
  "Кожа": "Cuir",
  "Количество билетов": "Nombre de billets",
  "Колонки": "Enceintes",
  "Коляска 2 в 1": "Poussette 2 en 1",
  "Коляска 3 в 1": "Poussette 3 en 1",
  "Коляска-люлька": "Poussette nacelle",
  "Коляски и автокресла": "Poussettes et sièges auto",
  "Командные виды": "Sports collectifs",
  "Комбинезоны": "Combinaisons",
  "Комиссия агента": "Commission d'agence",
  "Коммерческая недвижимость": "Immobilier commercial",
  "Коммерческое": "Commercial",
  "Коммунальные включены": "Charges comprises",
  "Коммуникации": "Réseaux",
  "Комнат": "Pièces",
  "Комната": "Chambre",
  "Комод": "Commode",
  "Компания": "Entreprise",
  "Кондиционер": "Climatisation",
  "Конструкторы": "Jeux de construction",
  "Концерты": "Concerts",
  "Копирайтинг": "Rédaction",
  "Корма": "Aliments pour animaux",
  "Коробка передач": "Boîte de vitesses",
  "Коротко и по делу — это первое, что видит покупатель.": "Court et précis : c'est la première chose que voit l'acheteur.",
  "Коротко и по делу — это первое, что видит человек.": "Court et précis : c'est la première chose que voit le visiteur.",
  "Косметика": "Cosmétiques",
  "Косметический": "Rafraîchissement",
  "Косметология": "Cosmétologie",
  "Кофты и футболки": "Pulls et t-shirts",
  "Кошки": "Chats",
  "Кран": "Grue",
  "Красный": "Rouge",
  "Красота и здоровье": "Beauté et santé",
  "Кроватка": "Lit bébé",
  "Кровать": "Lit",
  "Кровля": "Toiture",
  "Кросс": "Moto-cross",
  "Круизер": "Cruiser",
  "Кто оказывает услугу": "Qui propose le service",
  "Кузов": "Carrosserie",
  "Куклы": "Poupées",
  "Купе": "Coupé",
  "Купить": "Acheter",
  "Кухонный гарнитур": "Cuisine équipée",
  "ЛДСП": "Panneau de particules mélaminé",
  "ЛПХ": "Exploitation agricole familiale",
  "Легковые авто": "Voitures particulières",
  "Лимит пробега в сутки": "Kilométrage journalier limité",
  "Личные вещи": "Effets personnels",
  "Макияж": "Maquillage",
  "Мальчик": "Garçon",
  "Манеж": "Parc bébé",
  "Маникюр и педикюр": "Manucure et pédicure",
  "Марка": "Marque",
  "Маркетинг и медиа": "Marketing et médias",
  "Марки": "Marques",
  "Массаж": "Massage",
  "Математика": "Mathématiques",
  "Материал": "Matériau",
  "Материал стен": "Matériau des murs",
  "Машинки": "Petites voitures",
  "Машиноместо": "Place de parking",
  "Мебель": "Meubles",
  "Мебель и интерьер": "Meubles et déco",
  "Медиаплеер": "Lecteur multimédia",
  "Медицинские товары": "Matériel médical",
  "Междугородние перевозки": "Transport interurbain",
  "Менее года": "Moins d'un an",
  "Месяц": "Mois",
  "Металл": "Métal",
  "Механика": "Boîte manuelle",
  "Микроволновка": "Micro-ondes",
  "Минивэн": "Monospace",
  "Минимальный срок": "Durée minimale",
  "Минимум 3 фото — объявления с фото смотрят в 4 раза чаще.": "3 photos minimum — les annonces avec photos sont consultées 4 fois plus souvent.",
  "Минимум 3 фото, включая экран во включённом состоянии.": "3 photos minimum, dont une avec l'écran allumé.",
  "Минимум 3 фото.": "3 photos minimum.",
  "Минимум 3 фото: спереди, сзади, салон.": "3 photos minimum : avant, arrière, intérieur.",
  "Многодневный тур": "Circuit de plusieurs jours",
  "Мобильные приложения": "Applications mobiles",
  "Модели и фигурки": "Modèles réduits et figurines",
  "Модель": "Modèle",
  "Можно без опыта": "Sans expérience possible",
  "Можно с детьми": "Enfants acceptés",
  "Можно с животными": "Animaux acceptés",
  "Монеты": "Pièces de monnaie",
  "Моноблок": "Ordinateur tout-en-un",
  "Морская прогулка": "Balade en mer",
  "Мотоциклы и мототехника": "Motos et deux-roues",
  "Мужское": "Homme",
  "Музыка": "Musique",
  "Музыкальные инструменты": "Instruments de musique",
  "Муниципальная": "Municipale",
  "Мытьё окон": "Nettoyage des vitres",
  "Мягкие игрушки": "Peluches",
  "На дому у мастера": "Au domicile du prestataire",
  "На месте": "Sur place",
  "На несколько месяцев": "Pour plusieurs mois",
  "Навигация": "GPS",
  "Навыки": "Compétences",
  "Название компании": "Nom de l'entreprise",
  "Название объявления": "Titre de l'annonce",
  "Назначение": "Destination",
  "Найти жильё": "Trouver un logement",
  "Найти исполнителя": "Trouver un prestataire",
  "Найти питомца или товар": "Trouver un animal ou un article",
  "Найти работу": "Trouver un emploi",
  "Найти сотрудника": "Trouver un candidat",
  "Найти тур или снаряжение": "Trouver un circuit ou du matériel",
  "Найти человека в команду": "Trouver un coéquipier",
  "Накопитель": "Stockage",
  "Напольные покрытия": "Revêtements de sol",
  "Направление": "Destination",
  "Например: 15 октября 2026": "Par exemple : 15 octobre 2026",
  "Населённый пункт": "Localité",
  "Настольные игры": "Jeux de société",
  "Настольный компьютер": "Ordinateur de bureau",
  "Настройка сетей": "Configuration réseau",
  "Наука и инженерия": "Sciences et ingénierie",
  "Наушники": "Écouteurs",
  "Начальная школа": "École primaire",
  "Недвижимость": "Immobilier",
  "Неделя": "Semaine",
  "Незаконченное высшее": "Supérieur non terminé",
  "Необязательно. Требовать возраст в вакансиях запрещено законом.": "Facultatif. Exiger un âge dans une offre d'emploi est interdit par la loi.",
  "Нет": "Non",
  "Новое": "Neuf",
  "Новое без бирки": "Neuf sans étiquette",
  "Новое вскрытое": "Neuf ouvert",
  "Новое запечатанное": "Neuf scellé",
  "Новое с биркой": "Neuf avec étiquette",
  "Ноутбук": "Ordinateur portable",
  "Ноутбуки и компьютеры": "Ordinateurs portables et fixes",
  "О себе": "À propos de moi",
  "О себе и методике": "À propos de moi et de ma méthode",
  "Образование": "Formation",
  "Обременения": "Charges (hypothèques, servitudes)",
  "Обувь": "Chaussures",
  "Обучение и репетиторы": "Cours et soutien scolaire",
  "Объектив": "Objectif",
  "Объём двигателя": "Cylindrée",
  "Обязанности": "Missions",
  "Огорожен": "Clôturé",
  "Одежда для походов": "Vêtements de randonnée",
  "Одежда и обувь": "Vêtements et chaussures",
  "Окна": "Fenêtres",
  "Окна и двери": "Fenêtres et portes",
  "Онлайн": "En ligne",
  "Оперативная память": "Mémoire vive",
  "Описание": "Description",
  "Описание маршрута": "Description de l'itinéraire",
  "Описание услуги": "Description du service",
  "Описание услуги и портфолио": "Description du service et portfolio",
  "Опыт преподавания": "Expérience d'enseignement",
  "Опыт работы": "Expérience professionnelle",
  "Оставьте пустым, если залога нет.": "Laissez vide en l'absence de dépôt de garantie.",
  "Оставьте пустым, если отдаёте даром.": "Laissez vide si vous donnez l'article.",
  "Отдам даром": "À donner",
  "Отделочные работы": "Travaux de finition",
  "Отдельный вход": "Entrée indépendante",
  "Открытки": "Cartes postales",
  "Отличное": "Excellent",
  "Отопление": "Chauffage",
  "Офис": "Bureau",
  "Офис и администрация": "Bureau et administration",
  "Офисный переезд": "Déménagement de bureau",
  "Оформление": "Statut",
  "Оформление, отпуск, что оплачивается.": "Contrat, congés, ce qui est rémunéré.",
  "Охрана": "Sécurité",
  "Охрана и безопасность": "Sécurité et surveillance",
  "Очки": "Lunettes",
  "Палатки": "Tentes",
  "Панель": "Panneau",
  "Парикмахерские услуги": "Services de coiffure",
  "Парковка": "Parking",
  "Парта": "Bureau d'écolier",
  "Парфюмерия": "Parfumerie",
  "Пеленальный столик": "Table à langer",
  "Первое занятие бесплатно": "Premier cours gratuit",
  "Перевозки и грузчики": "Transport et déménagement",
  "Передний": "Avant",
  "Переуступка": "Cession de droits",
  "Печное": "Poêle",
  "Планшет": "Tablette",
  "Платформа": "Plateforme",
  "Платья": "Robes",
  "Плита": "Cuisinière",
  "Плитка": "Carrelage",
  "Площадь": "Surface",
  "Площадь дома": "Surface de la maison",
  "Площадь участка": "Surface du terrain",
  "По ТК РФ": "Sous contrat de travail",
  "По договорённости": "À négocier",
  "По номеру заполним площадь, вид использования и границы. Можно пропустить.": "À partir du numéro, nous renseignerons la surface, l'usage et les limites. Vous pouvez passer cette étape.",
  "Погрузчик": "Chargeuse",
  "Подвеска": "Suspension",
  "Подготовка к ЕГЭ и ОГЭ": "Préparation aux examens",
  "Поддерживающая уборка": "Ménage d'entretien",
  "Подработка": "Job d'appoint",
  "Подростковое": "Adolescent",
  "Подходит студентам": "Adapté aux étudiants",
  "Подъездная дорога": "Voie d'accès",
  "Покажите вещь целиком и вблизи — фактуру и возможные дефекты.": "Montrez l'objet en entier et de près — la texture et les éventuels défauts.",
  "Покажите крепления и ремни — это первое, что смотрят родители.": "Montrez les fixations et les sangles — c'est la première chose que regardent les parents.",
  "Пол": "Sexe",
  "Полки": "Étagères",
  "Полная": "Temps plein",
  "Полностью меблирована": "Entièrement meublé",
  "Полный": "Complet",
  "Полный комплект": "Ensemble complet",
  "Помощь по хозяйству": "Aide-ménagère",
  "Порода": "Race",
  "Портфолио повышает отклик в разы. Минимум 3 фото.": "Un portfolio multiplie les réponses. Minimum 3 photos.",
  "Портфолио — главный аргумент в этой категории.": "Le portfolio est l'argument principal dans cette catégorie.",
  "Последнее место работы": "Dernier emploi",
  "Посудомоечная машина": "Lave-vaisselle",
  "Посуточная аренда": "Location à la journée",
  "Посуточная аренда жилья": "Location de logement à la journée",
  "Посуточно": "À la journée",
  "Предложить услугу": "Proposer un service",
  "Предмет или направление": "Matière ou discipline",
  "Предоплата": "Acompte",
  "Приборы для ухода": "Appareils de soin",
  "Прививки сделаны": "Vaccins à jour",
  "Привод": "Transmission",
  "Пробег": "Kilométrage",
  "Пробег затвора": "Nombre de déclenchements",
  "Прогулочная коляска": "Poussette canne",
  "Продажа": "Vente",
  "Продажа или отдам даром": "Vente ou don",
  "Продажи и торговля": "Ventes et commerce",
  "Продать": "Vendre",
  "Продолжительность": "Durée",
  "Проектор": "Projecteur",
  "Проживание, питание, трансфер, входные билеты.": "Hébergement, repas, transferts, billets d'entrée.",
  "Производство": "Production",
  "Профессия": "Métier",
  "Процессор": "Processeur",
  "Птицы": "Oiseaux",
  "Путешествия": "Voyages",
  "Пылесос": "Aspirateur",
  "Работа": "Emploi",
  "Работаю круглосуточно": "Disponible 24h/24",
  "Работаю по договору": "Je travaille sous contrat",
  "Раз в месяц": "Une fois par mois",
  "Развивающие": "Jeux éducatifs",
  "Размер": "Taille",
  "Размер группы": "Taille du groupe",
  "Разместить вакансию": "Publier une offre d'emploi",
  "Разместить объявление": "Déposer une annonce",
  "Разместить объявление о продаже": "Déposer une annonce de vente",
  "Разместить объявление об аренде": "Déposer une annonce de location",
  "Разместить предложение": "Publier une offre",
  "Разместить резюме": "Publier un CV",
  "Разместить своё объявление": "Déposer votre annonce",
  "Разработка сайтов": "Création de sites web",
  "Растения и саженцы": "Plantes et semis",
  "Ремни": "Sangles",
  "Ремонт": "Travaux",
  "Ремонт и строительство": "Travaux et construction",
  "Ремонт и стройматериалы": "Bricolage et matériaux",
  "Ремонт компьютеров": "Réparation d'ordinateurs",
  "Ремонт под ключ": "Rénovation clé en main",
  "Рента": "Rente",
  "Рестораны и гостиницы": "Restaurants et hôtels",
  "Робот": "Robot",
  "Рубашки и блузки": "Chemises et chemisiers",
  "Русский язык": "Russe",
  "Рыбалка": "Pêche",
  "Рыбы": "Poissons",
  "Рюкзаки": "Sacs à dos",
  "С водителем": "Avec chauffeur",
  "С выездом к клиенту": "Avec déplacement chez le client",
  "С выездом к ученику": "Avec déplacement chez l'élève",
  "Сад и огород": "Jardin et potager",
  "Садовая мебель": "Mobilier de jardin",
  "Садовая техника": "Matériel de jardinage",
  "Садоводство (СНТ)": "Jardin associatif",
  "Салон": "Salon",
  "Самозанятость": "Auto-entrepreneuriat",
  "Сантехника": "Plomberie",
  "Сборка мебели": "Montage de meubles",
  "Свет": "Éclairage",
  "Свитеры и кофты": "Pulls et gilets",
  "Свободное назначение": "Usage libre",
  "Свободный": "Libre",
  "Сдать": "Louer",
  "Сдать в аренду": "Mettre en location",
  "Сдать жильё": "Louer un logement",
  "Седан": "Berline",
  "Сельское хозяйство": "Agriculture",
  "Сельхозживотные": "Animaux d'élevage",
  "Сельхозназначение": "Usage agricole",
  "Серебристый": "Argent",
  "Серый": "Gris",
  "Синий": "Bleu",
  "Склад": "Entrepôt",
  "Скутер": "Scooter",
  "Сменный": "Par roulement",
  "Снимите со всех сторон — так вещь продаётся быстрее.": "Photographiez sous tous les angles — l'objet se vend plus vite.",
  "Снять": "Louer",
  "Со своими средствами и техникой": "Avec son propre matériel",
  "Собаки": "Chiens",
  "Собственность": "Propriété",
  "Состояние": "État",
  "Состояние, история обслуживания, что менялось.": "État, historique d'entretien, pièces changées.",
  "Спальники": "Sacs de couchage",
  "Сплав и походы": "Rafting et randonnée",
  "Спорт": "Sport",
  "Спорт и отдых": "Sport et loisirs",
  "Спорт и фитнес": "Sport et fitness",
  "Спортивная одежда": "Vêtements de sport",
  "Среднее": "Secondaire",
  "Среднее специальное": "Technique et professionnel",
  "Средний срок выполнения": "Délai moyen d'exécution",
  "Средняя школа": "Collège",
  "Срок аренды": "Durée de location",
  "Стаж вождения от": "Ancienneté du permis à partir de",
  "Стажировка": "Stage",
  "Старшие классы": "Lycée",
  "Стекло": "Verre",
  "Стерилизован": "Stérilisé",
  "Стиральная машина": "Lave-linge",
  "Стол": "Table",
  "Строительство и ремонт": "Construction et rénovation",
  "Стройматериалы": "Matériaux de construction",
  "Струнные смычковые": "Instruments à cordes frottées",
  "Студенты": "Étudiants",
  "Студийное оборудование": "Matériel de studio",
  "Студия": "Studio",
  "Стульчик для кормления": "Chaise haute",
  "Стулья": "Chaises",
  "Сумки": "Sacs",
  "Сутки": "Jour",
  "Театр": "Théâtre",
  "Телевизор": "Téléviseur",
  "Телевизоры и аудио": "Téléviseurs et audio",
  "Телефоны": "Téléphones",
  "Теплицы": "Serres",
  "Тип": "Type",
  "Тип билета": "Type de billet",
  "Тип вещи": "Type d'article",
  "Тип жилья": "Type de logement",
  "Тип запчасти": "Type de pièce",
  "Тип игрушки": "Type de jouet",
  "Тип инструмента": "Type d'outil",
  "Тип мебели": "Type de meuble",
  "Тип объекта": "Type de bien",
  "Тип снаряжения": "Type de matériel",
  "Тип техники": "Type d'équipement",
  "Тип товара": "Type de produit",
  "Тип топлива": "Type de carburant",
  "Тип устройства": "Type d'appareil",
  "Ткань": "Tissu",
  "Товары для животных": "Articles pour animaux",
  "Только грузчики": "Déménageurs seulement",
  "Торговое": "Commerce",
  "Транспорт": "Transport",
  "Транспорт и логистика": "Transport et logistique",
  "Трансфер включён": "Transfert inclus",
  "Требования": "Exigences",
  "Требует ремонта": "À rénover",
  "Тренажёры": "Appareils de musculation",
  "Тур, экскурсия или снаряжение": "Circuit, excursion ou matériel",
  "Туризм и походы": "Tourisme et randonnée",
  "Туристическое снаряжение": "Matériel de randonnée",
  "Туры и экскурсии": "Circuits et excursions",
  "Туры, экскурсии, снаряжение": "Circuits, excursions, matériel",
  "Тягач": "Tracteur routier",
  "У преподавателя": "Chez le professeur",
  "Уборка и помощь по хозяйству": "Ménage et aide à domicile",
  "Уборка после ремонта": "Nettoyage après travaux",
  "Удалённо": "À distance",
  "Удалённость от города": "Distance de la ville",
  "Ударные": "Percussions",
  "Удовлетворительное": "Correct",
  "Украшения": "Bijoux",
  "Уличные игрушки": "Jeux d'extérieur",
  "Универсал": "Break",
  "Универсальное": "Universel",
  "Унисекс": "Unisexe",
  "Условия": "Conditions",
  "Условия передачи": "Conditions de remise",
  "Услуги": "Services",
  "Уход и гигиена": "Soin et hygiène",
  "Фестивали": "Festivals",
  "Физика": "Physique",
  "Финансы и бухгалтерия": "Finance et comptabilité",
  "Форма собственности": "Statut juridique",
  "Формат занятий": "Format des cours",
  "Формат работы": "Mode de travail",
  "Фото выполненных работ": "Photos de réalisations",
  "Фото и видеотехника": "Photo et vidéo",
  "Фото работ": "Photos de réalisations",
  "Фотоаппарат": "Appareil photo",
  "Фотографии": "Photos",
  "Фургон": "Fourgon",
  "Характер, привычки, к чему приучен, почему передаёте.": "Caractère, habitudes, éducation, raison de la cession.",
  "Химия": "Chimie",
  "Химчистка мебели": "Nettoyage à sec de meubles",
  "Хобби и отдых": "Loisirs",
  "Холодильник": "Réfrigérateur",
  "Хорошее": "Bon",
  "Хостел": "Auberge de jeunesse",
  "Хэтчбек": "Compacte",
  "Цвет": "Couleur",
  "Цена": "Prix",
  "Цена за билет": "Prix du billet",
  "Цена за занятие от": "Prix par cours à partir de",
  "Цена за месяц": "Prix par mois",
  "Цена за сутки": "Prix par jour",
  "Цена от": "Prix à partir de",
  "Цена с человека": "Prix par personne",
  "Час": "Heure",
  "Частичная": "Temps partiel",
  "Частично": "Partiellement",
  "Частный мастер": "Artisan indépendant",
  "Частный специалист": "Spécialiste indépendant",
  "Часы": "Montres",
  "Чем занимались, что умеете, чего ищете.": "Ce que vous avez fait, vos compétences, ce que vous recherchez.",
  "Что в комплекте, были ли ремонты, есть ли дефекты.": "Ce qui est inclus, réparations éventuelles, défauts éventuels.",
  "Что включено": "Ce qui est inclus",
  "Что делаете, за какой срок, что входит в стоимость.": "Ce que vous faites, en combien de temps, ce qui est compris dans le prix.",
  "Что продаёте": "Ce que vous vendez",
  "Что рядом, как заселение, что входит в стоимость.": "Ce qu'il y a à proximité, modalités d'arrivée, ce qui est compris dans le prix.",
  "Что человек будет делать каждый день.": "Ce que la personne fera au quotidien.",
  "Чтобы работа нашла вас": "Pour que le travail vous trouve",
  "Чёрный": "Noir",
  "Шины и диски": "Pneus et jantes",
  "Ширина": "Largeur",
  "Шкаф": "Armoire",
  "Штатив и стабилизаторы": "Trépieds et stabilisateurs",
  "Экскаватор": "Excavatrice",
  "Экскурсия": "Excursion",
  "Экшн-камера": "Caméra embarquée",
  "Электрика": "Électricité",
  "Электрическое": "Électrique",
  "Электричество": "Électricité",
  "Электричество, газ": "Électricité, gaz",
  "Электро": "Électrique",
  "Электроника": "Électronique",
  "Эндуро": "Enduro",
  "Эпиляция": "Épilation",
  "Этаж": "Étage",
  "Этажей": "Étages",
  "Этажей в доме": "Nombre d'étages",
  "Юриспруденция": "Droit",

  // Единицы измерения (unit у полей категорий)
  "дней": "jours",
  "кадров": "déclenchements",
  "кг": "kg",
  "км": "km",
  "л": "L",
  "лет": "ans",
  "м": "m",
  "м²": "m²",
  "мес.": "mois",
  "мин": "min",
  "см": "cm",
  "см³": "cm³",
  "соток": "ares",
  "суток": "jours",
  "т": "t",
  "\"": "\"",
  "%": "%",
  "₽": "₽",
};
