export const labels: Record<string, string> = {
  "0–1 год": "0–1 ano",
  "0–6 мес.": "0–6 meses",
  "1": "1",
  "1 ТБ": "1 TB",
  "100% от аренды": "100% do aluguel",
  "12+": "12+",
  "128 ГБ": "128 GB",
  "16 ГБ": "16 GB",
  "1–3 года": "1–3 anos",
  "1–4 года": "1–4 anos",
  "2": "2",
  "2/2": "2/2",
  "256 ГБ": "256 GB",
  "3": "3",
  "3 и более": "3 ou mais",
  "32 ГБ": "32 GB",
  "36": "36",
  "37": "37",
  "38": "38",
  "39": "39",
  "3–5 лет": "3–5 anos",
  "3–6 лет": "3–6 anos",
  "3–7 лет": "3–7 anos",
  "4 ГБ": "4 GB",
  "4+": "4+",
  "40": "40",
  "41": "41",
  "42": "42",
  "43": "43",
  "44": "44",
  "45": "45",
  "4–7 лет": "4–7 anos",
  "5/2": "5/2",
  "50% от аренды": "50% do aluguel",
  "512 ГБ": "512 GB",
  "6/1": "6/1",
  "64 ГБ": "64 GB",
  "6–18 мес.": "6–18 meses",
  "7–12 лет": "7–12 anos",
  "8 ГБ": "8 GB",
  "IT и интернет": "TI e internet",
  "IT, реклама и дизайн": "TI, publicidade e design",
  "L": "L",
  "M": "M",
  "Nintendo": "Nintendo",
  "PC": "PC",
  "PlayStation": "PlayStation",
  "S": "S",
  "SMM и реклама": "SMM e publicidade",
  "Smart TV": "Smart TV",
  "VIN или госномер": "VIN ou placa",
  "VR-гарнитура": "Óculos VR",
  "Wi-Fi": "Wi-Fi",
  "XL": "XL",
  "XS": "XS",
  "XXL": "XXL",
  "Xbox": "Xbox",
  "Ёмкости и баки": "Reservatórios e tanques",
  "Ёмкость аккумулятора": "Capacidade da bateria",
  "Авто": "Carros",
  "Авто и спецтехника напрокат": "Aluguel de carros e máquinas",
  "Автобус": "Ônibus",
  "Автокресло": "Cadeirinha para carro",
  "Автомат": "Automático",
  "Адрес": "Endereço",
  "Адрес или район": "Endereço ou bairro",
  "Аквариумные": "De aquário",
  "Аквариумы": "Aquários",
  "Аксессуары": "Acessórios",
  "Аксессуары и часы": "Acessórios e relógios",
  "Амуниция": "Equipamentos",
  "Английский язык": "Inglês",
  "Антиквариат": "Antiguidades",
  "Апартаменты": "Flats",
  "Аренда жилья и помещений": "Aluguel de imóveis residenciais e comerciais",
  "Арест": "Penhora",
  "Асфальт": "Asfalto",
  "Б/у": "Usado",
  "База отдыха": "Resort",
  "Балкон или лоджия": "Varanda ou sacada",
  "Без комиссии": "Sem comissão",
  "Без мебели": "Sem mobília",
  "Без опыта": "Sem experiência",
  "Без оформления": "Sem registro",
  "Без предоплаты": "Sem pagamento antecipado",
  "Без ремонта": "Sem reforma",
  "Без транспорта": "Sem transporte",
  "Бездорожье": "Fora de estrada",
  "Белый": "Branco",
  "Бензин": "Gasolina",
  "Билеты на события": "Ingressos para eventos",
  "Бокс": "Boxe",
  "Более 15 человек": "Mais de 15 pessoas",
  "Более 5 лет": "Mais de 5 anos",
  "Более 6 лет": "Mais de 6 anos",
  "Бренд": "Marca",
  "Бригада": "Equipe",
  "Брови и ресницы": "Sobrancelhas e cílios",
  "Брюки": "Calças",
  "Брюки и джинсы": "Calças e jeans",
  "Бустер": "Assento de elevação",
  "Бытовая техника": "Eletrodomésticos",
  "В вакансии — что предлагаете, в резюме — что ожидаете.": "Na vaga, diga o que você oferece; no currículo, o que você espera.",
  "В добрые руки с договором": "Doação com contrato",
  "В месяц": "Por mês",
  "В офисе заказчика": "No escritório do cliente",
  "В салоне": "No salão",
  "В собственности": "Próprio",
  "Вариатор": "CVT",
  "Вахта": "Trabalho rotativo",
  "Велосипеды": "Bicicletas",
  "Верхняя одежда": "Casacos e agasalhos",
  "Взрослые": "Adultos",
  "Взять в аренду": "Alugar",
  "Вид животного": "Tipo de animal",
  "Вид работ": "Tipo de serviço",
  "Вид разрешённого использования": "Uso permitido do solo",
  "Вид услуги": "Tipo de serviço",
  "Видеокамера": "Câmera de vídeo",
  "Владельцев по ПТС": "Proprietários no documento",
  "Внедорожник": "SUV",
  "Водительские права": "Carteira de motorista",
  "Возможна доставка": "Entrega disponível",
  "Возможна ипотека": "Aceita financiamento",
  "Возраст": "Idade",
  "Возраст водителя от": "Idade mínima do motorista",
  "Возрастная группа": "Faixa etária",
  "Все вакансии": "Todas as vagas",
  "Все комнаты, санузел и кухня. Минимум 5 фото.": "Todos os cômodos, banheiro e cozinha. Mínimo de 5 fotos.",
  "Все объекты в продаже": "Todos os imóveis à venda",
  "Все объявления": "Todos os anúncios",
  "Все предложения услуг": "Todas as ofertas de serviços",
  "Все резюме": "Todos os currículos",
  "Все центральные": "Todos os centrais",
  "Встроенная память": "Memória interna",
  "Вывоз мусора": "Retirada de lixo",
  "Выезд к заказчику": "Atendimento no local do cliente",
  "Выплаты": "Pagamentos",
  "Высота": "Altura",
  "Высота потолков": "Altura do teto",
  "Выставки": "Exposições",
  "Высшее": "Superior",
  "Газ": "Gás",
  "Газель": "Van de carga",
  "Газоблок": "Bloco de concreto celular",
  "Газовое": "A gás",
  "Гараж": "Garagem",
  "Гараж и машиноместо": "Garagem e vaga de estacionamento",
  "Гаражи и машиноместа": "Garagens e vagas de estacionamento",
  "Гарантия действует": "Garantia válida",
  "Гарантия на работы": "Garantia do serviço",
  "Гастротур": "Turismo gastronômico",
  "Где принимаете": "Onde atende",
  "Геймпад": "Controle de videogame",
  "Генеральная уборка": "Limpeza geral",
  "Гибрид": "Híbrido",
  "Гитары": "Violões e guitarras",
  "Глубина": "Profundidade",
  "Год выпуска": "Ano de fabricação",
  "Год постройки": "Ano de construção",
  "Головные уборы": "Chapéus e bonés",
  "Горелки и посуда": "Fogareiros e utensílios",
  "Город": "Cidade",
  "Город отправления": "Cidade de partida",
  "Гостей": "Hóspedes",
  "Готов к переезду": "Disponível para mudança",
  "График": "Horário de trabalho",
  "Грузовик": "Caminhão",
  "Грузовик до 5 т": "Caminhão até 5 t",
  "Грузовик свыше 5 т": "Caminhão acima de 5 t",
  "Грузовики и спецтехника": "Caminhões e máquinas pesadas",
  "Грузоподъёмность": "Capacidade de carga",
  "Грузчики": "Ajudantes de mudança",
  "Грунт": "Terra",
  "Грызуны": "Roedores",
  "Да": "Sim",
  "Дата события": "Data do evento",
  "Два раза в месяц": "Duas vezes por mês",
  "Двери": "Portas",
  "Двигатель": "Motor",
  "Девочка": "Menina",
  "Дерево": "Madeira",
  "Дети и детские услуги": "Crianças e serviços infantis",
  "Детская мебель": "Móveis infantis",
  "Детская одежда и обувь": "Roupas e calçados infantis",
  "Детское": "Infantil",
  "Диагональ": "Tamanho da tela",
  "Диагональ экрана": "Tamanho da tela",
  "Диван": "Sofá",
  "Дизайн": "Design",
  "Дизайнерский": "De designer",
  "Дизель": "Diesel",
  "Длительно (от года)": "Longo prazo (a partir de 1 ano)",
  "Длительность занятия": "Duração da aula",
  "Для дома": "Para casa",
  "Для кого": "Para quem",
  "Для марки": "Para a marca",
  "До 15 человек": "Até 15 pessoas",
  "До 5 человек": "Até 5 pessoas",
  "До года": "Até 1 ano",
  "Договор ГПХ": "Contrato civil (PJ)",
  "Долевая собственность": "Copropriedade",
  "Дом": "Casa",
  "Дом, дача, таунхаус": "Casa, casa de campo, townhouse",
  "Дома и дачи": "Casas e casas de campo",
  "Домашний кинотеатр": "Home theater",
  "Домашний персонал": "Empregados domésticos",
  "Домики и лежанки": "Casinhas e caminhas",
  "Допустимый вес ребёнка": "Peso máximo da criança",
  "Дорожный": "De estrada",
  "Доставка мебели": "Entrega de móveis",
  "Дошкольники": "Pré-escolares",
  "Другая": "Outra",
  "Другие языки": "Outros idiomas",
  "Духовые": "Instrumentos de sopro",
  "Евроремонт": "Acabamento padrão europeu",
  "Единица расчёта": "Unidade de cálculo",
  "Единоборства": "Lutas e artes marciais",
  "Ежедневно": "Diariamente",
  "Еженедельно": "Semanalmente",
  "Есть": "Tem",
  "Есть автомобиль": "Tem carro próprio",
  "Есть документы и родословная": "Tem documentos e pedigree",
  "Есть сертификат или диплом": "Tem certificado ou diploma",
  "ЖКХ и благоустройство": "Manutenção e conservação",
  "Женское": "Feminino",
  "Животные": "Animais",
  "Живые фото питомца, а не изображения породы из интернета.": "Fotos reais do animal, não imagens da raça tiradas da internet.",
  "За два месяца": "A cada dois meses",
  "За заказ": "Por pedido",
  "За км": "Por km",
  "За м²": "Por m²",
  "За месяц": "Por mês",
  "За метр погонный": "Por metro linear",
  "За проект": "Por projeto",
  "За услугу": "Por serviço",
  "За час": "Por hora",
  "Задний": "Traseiro",
  "Залог": "Caução",
  "Занятость": "Tipo de contratação",
  "Заполним марку, модель, год и двигатель автоматически. Можно ввести данные вручную.": "Preenchemos marca, modelo, ano e motor automaticamente. Você pode inserir os dados manualmente.",
  "Запчасти и аксессуары": "Peças e acessórios",
  "Зарплата от": "Salário a partir de",
  "Земельные участки": "Terrenos",
  "Земельный участок": "Terreno",
  "Зимний спорт": "Esportes de inverno",
  "Значки": "Broches e pins",
  "ИЖС": "Construção residencial individual",
  "Игра": "Jogo",
  "Игровая приставка": "Videogame (console)",
  "Игрушки": "Brinquedos",
  "Игрушки и товары для игр": "Brinquedos e produtos para jogos",
  "Игры и приставки": "Jogos e consoles",
  "Индивидуально": "Individual",
  "Индивидуальный гид": "Guia particular",
  "Инструменты": "Ferramentas",
  "Информатика": "Informática",
  "Ипотека": "Financiamento imobiliário",
  "Искусство и творчество": "Arte e criatividade",
  "Кадастровый номер": "Número cadastral",
  "Каркас": "Estrutura",
  "Квартира": "Apartamento",
  "Квартирный переезд": "Mudança residencial",
  "Квартиры": "Apartamentos",
  "Кино": "Cinema",
  "Кирпич": "Tijolo",
  "Клавишные": "Instrumentos de teclas",
  "Клетки и переноски": "Gaiolas e caixas de transporte",
  "Клининговая компания": "Empresa de limpeza",
  "Книги": "Livros",
  "Книги и коллекционирование": "Livros e colecionáveis",
  "Кожа": "Couro",
  "Количество билетов": "Número de ingressos",
  "Колонки": "Caixas de som",
  "Коляска 2 в 1": "Carrinho de bebê 2 em 1",
  "Коляска 3 в 1": "Carrinho de bebê 3 em 1",
  "Коляска-люлька": "Carrinho tipo moisés",
  "Коляски и автокресла": "Carrinhos e cadeirinhas de bebê",
  "Командные виды": "Esportes coletivos",
  "Комбинезоны": "Macacões",
  "Комиссия агента": "Comissão do corretor",
  "Коммерческая недвижимость": "Imóveis comerciais",
  "Коммерческое": "Comercial",
  "Коммунальные включены": "Contas incluídas",
  "Коммуникации": "Infraestrutura",
  "Комнат": "Quartos",
  "Комната": "Quarto",
  "Комод": "Cômoda",
  "Компания": "Empresa",
  "Кондиционер": "Ar-condicionado",
  "Конструкторы": "Blocos de montar",
  "Концерты": "Shows",
  "Копирайтинг": "Redação publicitária",
  "Корма": "Rações",
  "Коробка передач": "Câmbio",
  "Коротко и по делу — это первое, что видит покупатель.": "Curto e direto — é a primeira coisa que o comprador vê.",
  "Коротко и по делу — это первое, что видит человек.": "Curto e direto — é a primeira coisa que a pessoa vê.",
  "Косметика": "Cosméticos",
  "Косметический": "Reforma leve",
  "Косметология": "Cosmetologia e estética",
  "Кофты и футболки": "Blusas e camisetas",
  "Кошки": "Gatos",
  "Кран": "Guindaste",
  "Красный": "Vermelho",
  "Красота и здоровье": "Beleza e saúde",
  "Кроватка": "Berço",
  "Кровать": "Cama",
  "Кровля": "Telhado",
  "Кросс": "Motocross",
  "Круизер": "Cruiser",
  "Кто оказывает услугу": "Quem presta o serviço",
  "Кузов": "Carroceria",
  "Куклы": "Bonecas",
  "Купе": "Cupê",
  "Купить": "Comprar",
  "Кухонный гарнитур": "Cozinha planejada",
  "ЛДСП": "Aglomerado revestido (MDP)",
  "ЛПХ": "Uso agrícola pessoal",
  "Легковые авто": "Carros de passeio",
  "Лимит пробега в сутки": "Limite de km por dia",
  "Личные вещи": "Itens pessoais",
  "Макияж": "Maquiagem",
  "Мальчик": "Menino",
  "Манеж": "Cercadinho",
  "Маникюр и педикюр": "Manicure e pedicure",
  "Марка": "Marca",
  "Маркетинг и медиа": "Marketing e mídia",
  "Марки": "Marcas",
  "Массаж": "Massagem",
  "Математика": "Matemática",
  "Материал": "Material",
  "Материал стен": "Material das paredes",
  "Машинки": "Carrinhos",
  "Машиноместо": "Vaga de garagem",
  "Мебель": "Móveis",
  "Мебель и интерьер": "Móveis e decoração",
  "Медиаплеер": "Media player",
  "Медицинские товары": "Produtos médicos",
  "Междугородние перевозки": "Fretes interurbanos",
  "Менее года": "Menos de 1 ano",
  "Месяц": "Mês",
  "Металл": "Metal",
  "Механика": "Manual",
  "Микроволновка": "Micro-ondas",
  "Минивэн": "Minivan",
  "Минимальный срок": "Prazo mínimo",
  "Минимум 3 фото — объявления с фото смотрят в 4 раза чаще.": "No mínimo 3 fotos — anúncios com fotos são vistos 4 vezes mais.",
  "Минимум 3 фото, включая экран во включённом состоянии.": "No mínimo 3 fotos, incluindo a tela ligada.",
  "Минимум 3 фото.": "No mínimo 3 fotos.",
  "Минимум 3 фото: спереди, сзади, салон.": "No mínimo 3 fotos: frente, traseira e interior.",
  "Многодневный тур": "Passeio de vários dias",
  "Мобильные приложения": "Aplicativos móveis",
  "Модели и фигурки": "Miniaturas e action figures",
  "Модель": "Modelo",
  "Можно без опыта": "Pode ser sem experiência",
  "Можно с детьми": "Pode levar crianças",
  "Можно с животными": "Aceita animais",
  "Монеты": "Moedas",
  "Моноблок": "Computador all-in-one",
  "Морская прогулка": "Passeio de barco",
  "Мотоциклы и мототехника": "Motos e veículos motorizados",
  "Мужское": "Masculino",
  "Музыка": "Música",
  "Музыкальные инструменты": "Instrumentos musicais",
  "Муниципальная": "Municipal",
  "Мытьё окон": "Limpeza de vidros",
  "Мягкие игрушки": "Pelúcias",
  "На дому у мастера": "Na casa do profissional",
  "На месте": "No local",
  "На несколько месяцев": "Por alguns meses",
  "Навигация": "GPS e navegação",
  "Навыки": "Habilidades",
  "Название компании": "Nome da empresa",
  "Название объявления": "Título do anúncio",
  "Назначение": "Finalidade",
  "Найти жильё": "Encontrar moradia",
  "Найти исполнителя": "Encontrar prestador de serviço",
  "Найти питомца или товар": "Encontrar um pet ou produto",
  "Найти работу": "Encontrar emprego",
  "Найти сотрудника": "Encontrar funcionário",
  "Найти тур или снаряжение": "Encontrar passeio ou equipamento",
  "Найти человека в команду": "Encontrar alguém para a equipe",
  "Накопитель": "Armazenamento",
  "Напольные покрытия": "Revestimentos de piso",
  "Направление": "Destino",
  "Например: 15 октября 2026": "Por exemplo: 15 de outubro de 2026",
  "Населённый пункт": "Localidade",
  "Настольные игры": "Jogos de tabuleiro",
  "Настольный компьютер": "Computador de mesa",
  "Настройка сетей": "Configuração de redes",
  "Наука и инженерия": "Ciência e engenharia",
  "Наушники": "Fones de ouvido",
  "Начальная школа": "Ensino fundamental I",
  "Недвижимость": "Imóveis",
  "Неделя": "Semana",
  "Незаконченное высшее": "Superior incompleto",
  "Необязательно. Требовать возраст в вакансиях запрещено законом.": "Opcional. Exigir idade em vagas de emprego é proibido por lei.",
  "Нет": "Não",
  "Новое": "Novo",
  "Новое без бирки": "Novo sem etiqueta",
  "Новое вскрытое": "Novo, embalagem aberta",
  "Новое запечатанное": "Novo lacrado",
  "Новое с биркой": "Novo com etiqueta",
  "Ноутбук": "Notebook",
  "Ноутбуки и компьютеры": "Notebooks e computadores",
  "О себе": "Sobre mim",
  "О себе и методике": "Sobre mim e minha metodologia",
  "Образование": "Formação",
  "Обременения": "Ônus e restrições",
  "Обувь": "Calçados",
  "Обучение и репетиторы": "Aulas e professores particulares",
  "Объектив": "Lente",
  "Объём двигателя": "Cilindrada",
  "Обязанности": "Responsabilidades",
  "Огорожен": "Cercado",
  "Одежда для походов": "Roupas para trilha e camping",
  "Одежда и обувь": "Roupas e calçados",
  "Окна": "Janelas",
  "Окна и двери": "Janelas e portas",
  "Онлайн": "Online",
  "Оперативная память": "Memória RAM",
  "Описание": "Descrição",
  "Описание маршрута": "Descrição do roteiro",
  "Описание услуги": "Descrição do serviço",
  "Описание услуги и портфолио": "Descrição do serviço e portfólio",
  "Опыт преподавания": "Experiência de ensino",
  "Опыт работы": "Experiência profissional",
  "Оставьте пустым, если залога нет.": "Deixe em branco se não houver caução.",
  "Оставьте пустым, если отдаёте даром.": "Deixe em branco se estiver doando.",
  "Отдам даром": "Doação",
  "Отделочные работы": "Serviços de acabamento",
  "Отдельный вход": "Entrada independente",
  "Открытки": "Cartões postais",
  "Отличное": "Excelente",
  "Отопление": "Aquecimento",
  "Офис": "Escritório",
  "Офис и администрация": "Escritório e administração",
  "Офисный переезд": "Mudança de escritório",
  "Оформление": "Vínculo empregatício",
  "Оформление, отпуск, что оплачивается.": "Vínculo, férias, o que é remunerado.",
  "Охрана": "Segurança",
  "Охрана и безопасность": "Segurança e vigilância",
  "Очки": "Óculos",
  "Палатки": "Barracas",
  "Панель": "Painel",
  "Парикмахерские услуги": "Serviços de cabeleireiro",
  "Парковка": "Estacionamento",
  "Парта": "Carteira escolar",
  "Парфюмерия": "Perfumaria",
  "Пеленальный столик": "Trocador de bebê",
  "Первое занятие бесплатно": "Primeira aula gratuita",
  "Перевозки и грузчики": "Fretes e ajudantes de mudança",
  "Передний": "Dianteiro",
  "Переуступка": "Cessão de direitos",
  "Печное": "A lenha",
  "Планшет": "Tablet",
  "Платформа": "Plataforma",
  "Платья": "Vestidos",
  "Плита": "Fogão",
  "Плитка": "Cerâmica",
  "Площадь": "Área",
  "Площадь дома": "Área da casa",
  "Площадь участка": "Área do terreno",
  "По ТК РФ": "Contrato formal (CLT)",
  "По договорённости": "A combinar",
  "По номеру заполним площадь, вид использования и границы. Можно пропустить.": "Pelo número preenchemos área, uso permitido e limites. Você pode pular esta etapa.",
  "Погрузчик": "Carregadeira",
  "Подвеска": "Suspensão",
  "Подготовка к ЕГЭ и ОГЭ": "Preparação para o vestibular",
  "Поддерживающая уборка": "Limpeza de manutenção",
  "Подработка": "Trabalho temporário",
  "Подростковое": "Adolescente",
  "Подходит студентам": "Ideal para estudantes",
  "Подъездная дорога": "Via de acesso",
  "Покажите вещь целиком и вблизи — фактуру и возможные дефекты.": "Mostre o item inteiro e de perto — a textura e possíveis defeitos.",
  "Покажите крепления и ремни — это первое, что смотрят родители.": "Mostre os encaixes e cintos — é a primeira coisa que os pais olham.",
  "Пол": "Sexo",
  "Полки": "Prateleiras",
  "Полная": "Tempo integral",
  "Полностью меблирована": "Totalmente mobiliada",
  "Полный": "Integral",
  "Полный комплект": "Kit completo",
  "Помощь по хозяйству": "Ajuda doméstica",
  "Порода": "Raça",
  "Портфолио повышает отклик в разы. Минимум 3 фото.": "Um portfólio multiplica as respostas. No mínimo 3 fotos.",
  "Портфолио — главный аргумент в этой категории.": "O portfólio é o principal argumento nesta categoria.",
  "Последнее место работы": "Último emprego",
  "Посудомоечная машина": "Lava-louças",
  "Посуточная аренда": "Aluguel por diária",
  "Посуточная аренда жилья": "Aluguel de imóveis por diária",
  "Посуточно": "Por diária",
  "Предложить услугу": "Oferecer serviço",
  "Предмет или направление": "Disciplina ou área",
  "Предоплата": "Pagamento antecipado",
  "Приборы для ухода": "Aparelhos de cuidado pessoal",
  "Прививки сделаны": "Vacinado",
  "Привод": "Tração",
  "Пробег": "Quilometragem",
  "Пробег затвора": "Contador de disparos",
  "Прогулочная коляска": "Carrinho de passeio",
  "Продажа": "Venda",
  "Продажа или отдам даром": "Venda ou doação",
  "Продажи и торговля": "Vendas e comércio",
  "Продать": "Vender",
  "Продолжительность": "Duração",
  "Проектор": "Projetor",
  "Проживание, питание, трансфер, входные билеты.": "Hospedagem, alimentação, transporte, ingressos.",
  "Производство": "Produção",
  "Профессия": "Profissão",
  "Процессор": "Processador",
  "Птицы": "Aves",
  "Путешествия": "Viagens",
  "Пылесос": "Aspirador de pó",
  "Работа": "Trabalho",
  "Работаю круглосуточно": "Atendo 24 horas",
  "Работаю по договору": "Trabalho com contrato",
  "Раз в месяц": "Uma vez por mês",
  "Развивающие": "Educativos",
  "Размер": "Tamanho",
  "Размер группы": "Tamanho do grupo",
  "Разместить вакансию": "Publicar vaga",
  "Разместить объявление": "Publicar anúncio",
  "Разместить объявление о продаже": "Publicar anúncio de venda",
  "Разместить объявление об аренде": "Publicar anúncio de aluguel",
  "Разместить предложение": "Publicar oferta",
  "Разместить резюме": "Publicar currículo",
  "Разместить своё объявление": "Publicar seu anúncio",
  "Разработка сайтов": "Desenvolvimento de sites",
  "Растения и саженцы": "Plantas e mudas",
  "Ремни": "Cintos",
  "Ремонт": "Reforma",
  "Ремонт и строительство": "Reforma e construção",
  "Ремонт и стройматериалы": "Reforma e materiais de construção",
  "Ремонт компьютеров": "Conserto de computadores",
  "Ремонт под ключ": "Reforma chave na mão",
  "Рента": "Renda",
  "Рестораны и гостиницы": "Restaurantes e hotéis",
  "Робот": "Robô",
  "Рубашки и блузки": "Camisas e blusas",
  "Русский язык": "Russo",
  "Рыбалка": "Pesca",
  "Рыбы": "Peixes",
  "Рюкзаки": "Mochilas",
  "С водителем": "Com motorista",
  "С выездом к клиенту": "Atendimento no local do cliente",
  "С выездом к ученику": "Atendimento na casa do aluno",
  "Сад и огород": "Jardim e horta",
  "Садовая мебель": "Móveis de jardim",
  "Садовая техника": "Equipamentos de jardinagem",
  "Садоводство (СНТ)": "Terreno para chácara (associação)",
  "Салон": "Salão",
  "Самозанятость": "Trabalho autônomo",
  "Сантехника": "Material hidráulico",
  "Сборка мебели": "Montagem de móveis",
  "Свет": "Iluminação",
  "Свитеры и кофты": "Suéteres e blusas de frio",
  "Свободное назначение": "Uso livre",
  "Свободный": "Livre",
  "Сдать": "Colocar para alugar",
  "Сдать в аренду": "Colocar para alugar",
  "Сдать жильё": "Anunciar aluguel de imóvel",
  "Седан": "Sedã",
  "Сельское хозяйство": "Agricultura",
  "Сельхозживотные": "Animais de criação",
  "Сельхозназначение": "Uso agrícola",
  "Серебристый": "Prata",
  "Серый": "Cinza",
  "Синий": "Azul",
  "Склад": "Galpão",
  "Скутер": "Scooter",
  "Сменный": "Por turnos",
  "Снимите со всех сторон — так вещь продаётся быстрее.": "Fotografe de todos os ângulos — assim o item vende mais rápido.",
  "Снять": "Alugar",
  "Со своими средствами и техникой": "Com materiais e equipamentos próprios",
  "Собаки": "Cachorros",
  "Собственность": "Propriedade",
  "Состояние": "Estado",
  "Состояние, история обслуживания, что менялось.": "Estado, histórico de manutenção, o que foi trocado.",
  "Спальники": "Sacos de dormir",
  "Сплав и походы": "Rafting e trilhas",
  "Спорт": "Esporte",
  "Спорт и отдых": "Esporte e lazer",
  "Спорт и фитнес": "Esporte e fitness",
  "Спортивная одежда": "Roupas esportivas",
  "Среднее": "Médio",
  "Среднее специальное": "Técnico",
  "Средний срок выполнения": "Prazo médio de execução",
  "Средняя школа": "Ensino fundamental II",
  "Срок аренды": "Prazo do aluguel",
  "Стаж вождения от": "Tempo mínimo de habilitação",
  "Стажировка": "Estágio",
  "Старшие классы": "Ensino médio",
  "Стекло": "Vidro",
  "Стерилизован": "Castrado",
  "Стиральная машина": "Máquina de lavar",
  "Стол": "Mesa",
  "Строительство и ремонт": "Construção e reforma",
  "Стройматериалы": "Materiais de construção",
  "Струнные смычковые": "Instrumentos de corda com arco",
  "Студенты": "Estudantes",
  "Студийное оборудование": "Equipamento de estúdio",
  "Студия": "Studio",
  "Стульчик для кормления": "Cadeira de alimentação",
  "Стулья": "Cadeiras",
  "Сумки": "Bolsas",
  "Сутки": "Diária",
  "Театр": "Teatro",
  "Телевизор": "Televisor",
  "Телевизоры и аудио": "TVs e áudio",
  "Телефоны": "Celulares",
  "Теплицы": "Estufas",
  "Тип": "Tipo",
  "Тип билета": "Tipo de ingresso",
  "Тип вещи": "Tipo de item",
  "Тип жилья": "Tipo de imóvel",
  "Тип запчасти": "Tipo de peça",
  "Тип игрушки": "Tipo de brinquedo",
  "Тип инструмента": "Tipo de ferramenta",
  "Тип мебели": "Tipo de móvel",
  "Тип объекта": "Tipo de imóvel",
  "Тип снаряжения": "Tipo de equipamento",
  "Тип техники": "Tipo de equipamento",
  "Тип товара": "Tipo de produto",
  "Тип топлива": "Tipo de combustível",
  "Тип устройства": "Tipo de dispositivo",
  "Ткань": "Tecido",
  "Товары для животных": "Produtos para animais",
  "Только грузчики": "Somente ajudantes",
  "Торговое": "Uso comercial",
  "Транспорт": "Veículos",
  "Транспорт и логистика": "Transporte e logística",
  "Трансфер включён": "Transfer incluído",
  "Требования": "Requisitos",
  "Требует ремонта": "Precisa de reforma",
  "Тренажёры": "Aparelhos de ginástica",
  "Тур, экскурсия или снаряжение": "Passeio, excursão ou equipamento",
  "Туризм и походы": "Turismo e trilhas",
  "Туристическое снаряжение": "Equipamento de camping",
  "Туры и экскурсии": "Passeios e excursões",
  "Туры, экскурсии, снаряжение": "Passeios, excursões e equipamentos",
  "Тягач": "Cavalo mecânico",
  "У преподавателя": "Na casa do professor",
  "Уборка и помощь по хозяйству": "Limpeza e ajuda doméstica",
  "Уборка после ремонта": "Limpeza pós-obra",
  "Удалённо": "Remoto",
  "Удалённость от города": "Distância da cidade",
  "Ударные": "Instrumentos de percussão",
  "Удовлетворительное": "Regular",
  "Украшения": "Joias e bijuterias",
  "Уличные игрушки": "Brinquedos para área externa",
  "Универсал": "Station wagon",
  "Универсальное": "Universal",
  "Унисекс": "Unissex",
  "Условия": "Condições",
  "Условия передачи": "Condições de entrega",
  "Услуги": "Serviços",
  "Уход и гигиена": "Cuidados e higiene",
  "Фестивали": "Festivais",
  "Физика": "Física",
  "Финансы и бухгалтерия": "Finanças e contabilidade",
  "Форма собственности": "Regime de propriedade",
  "Формат занятий": "Formato das aulas",
  "Формат работы": "Formato de trabalho",
  "Фото выполненных работ": "Fotos dos trabalhos realizados",
  "Фото и видеотехника": "Fotografia e vídeo",
  "Фото работ": "Fotos dos trabalhos",
  "Фотоаппарат": "Câmera fotográfica",
  "Фотографии": "Fotografias",
  "Фургон": "Furgão",
  "Характер, привычки, к чему приучен, почему передаёте.": "Temperamento, hábitos, o que já aprendeu, motivo da doação.",
  "Химия": "Química",
  "Химчистка мебели": "Limpeza a seco de estofados",
  "Хобби и отдых": "Hobbies e lazer",
  "Холодильник": "Geladeira",
  "Хорошее": "Bom",
  "Хостел": "Hostel",
  "Хэтчбек": "Hatch",
  "Цвет": "Cor",
  "Цена": "Preço",
  "Цена за билет": "Preço por ingresso",
  "Цена за занятие от": "Preço por aula a partir de",
  "Цена за месяц": "Preço por mês",
  "Цена за сутки": "Preço por diária",
  "Цена от": "Preço a partir de",
  "Цена с человека": "Preço por pessoa",
  "Час": "Hora",
  "Частичная": "Parcial",
  "Частично": "Parcialmente",
  "Частный мастер": "Profissional autônomo",
  "Частный специалист": "Especialista autônomo",
  "Часы": "Relógios",
  "Чем занимались, что умеете, чего ищете.": "O que você já fez, o que sabe fazer, o que procura.",
  "Что в комплекте, были ли ремонты, есть ли дефекты.": "O que está incluso, se houve reparos, se há defeitos.",
  "Что включено": "O que está incluído",
  "Что делаете, за какой срок, что входит в стоимость.": "O que você faz, em quanto tempo, o que está incluído no preço.",
  "Что продаёте": "O que você está vendendo",
  "Что рядом, как заселение, что входит в стоимость.": "O que há por perto, como é o check-in, o que está incluído no preço.",
  "Что человек будет делать каждый день.": "O que a pessoa vai fazer no dia a dia.",
  "Чтобы работа нашла вас": "Para o trabalho te encontrar",
  "Чёрный": "Preto",
  "Шины и диски": "Pneus e rodas",
  "Ширина": "Largura",
  "Шкаф": "Armário",
  "Штатив и стабилизаторы": "Tripé e estabilizadores",
  "Экскаватор": "Escavadeira",
  "Экскурсия": "Excursão",
  "Экшн-камера": "Câmera de ação",
  "Электрика": "Elétrica",
  "Электрическое": "Elétrico",
  "Электричество": "Eletricidade",
  "Электричество, газ": "Eletricidade, gás",
  "Электро": "Elétrico",
  "Электроника": "Eletrônicos",
  "Эндуро": "Enduro",
  "Эпиляция": "Depilação",
  "Этаж": "Andar",
  "Этажей": "Andares",
  "Этажей в доме": "Andares no prédio",
  "Юриспруденция": "Direito",

  // Единицы измерения (unit у полей категорий)
  "дней": "dias",
  "кадров": "disparos",
  "кг": "kg",
  "км": "km",
  "л": "L",
  "лет": "anos",
  "м": "m",
  "м²": "m²",
  "мес.": "meses",
  "мин": "min",
  "см": "cm",
  "см³": "cm³",
  "соток": "ares",
  "суток": "dias",
  "т": "t",
  "\"": "\"",
  "%": "%",
  "₽": "₽",
};
