export const labels: Record<string, string> = {
  "0–1 год": "0–1 yaş",
  "0–6 мес.": "0–6 ay",
  "1": "1",
  "1 ТБ": "1 TB",
  "100% от аренды": "Kira bedelinin %100’ü",
  "12+": "12+",
  "128 ГБ": "128 GB",
  "16 ГБ": "16 GB",
  "1–3 года": "1–3 yaş",
  "1–4 года": "1–4 yaş",
  "2": "2",
  "2/2": "2/2",
  "256 ГБ": "256 GB",
  "3": "3",
  "3 и более": "3 ve üzeri",
  "32 ГБ": "32 GB",
  "36": "36",
  "37": "37",
  "38": "38",
  "39": "39",
  "3–5 лет": "3–5 yaş",
  "3–6 лет": "3–6 yaş",
  "3–7 лет": "3–7 yaş",
  "4 ГБ": "4 GB",
  "4+": "4+",
  "40": "40",
  "41": "41",
  "42": "42",
  "43": "43",
  "44": "44",
  "45": "45",
  "4–7 лет": "4–7 yaş",
  "5/2": "5/2",
  "50% от аренды": "Kira bedelinin %50’si",
  "512 ГБ": "512 GB",
  "6/1": "6/1",
  "64 ГБ": "64 GB",
  "6–18 мес.": "6–18 ay",
  "7–12 лет": "7–12 yaş",
  "8 ГБ": "8 GB",
  "IT и интернет": "BT ve internet",
  "IT, реклама и дизайн": "BT, reklam ve tasarım",
  "L": "L",
  "M": "M",
  "Nintendo": "Nintendo",
  "PC": "PC",
  "PlayStation": "PlayStation",
  "S": "S",
  "SMM и реклама": "SMM ve reklam",
  "Smart TV": "Smart TV",
  "VIN или госномер": "Şasi no (VIN) veya plaka",
  "VR-гарнитура": "VR gözlük",
  "Wi-Fi": "Wi-Fi",
  "XL": "XL",
  "XS": "XS",
  "XXL": "XXL",
  "Xbox": "Xbox",
  "Ёмкости и баки": "Depolar ve tanklar",
  "Ёмкость аккумулятора": "Pil kapasitesi",
  "Авто": "Otomobil",
  "Авто и спецтехника напрокат": "Kiralık araç ve iş makinesi",
  "Автобус": "Otobüs",
  "Автокресло": "Oto koltuğu",
  "Автомат": "Otomatik",
  "Адрес": "Adres",
  "Адрес или район": "Adres veya semt",
  "Аквариумные": "Akvaryum canlıları",
  "Аквариумы": "Akvaryumlar",
  "Аксессуары": "Aksesuarlar",
  "Аксессуары и часы": "Aksesuar ve saat",
  "Амуниция": "Ekipman",
  "Английский язык": "İngilizce",
  "Антиквариат": "Antika",
  "Апартаменты": "Rezidans",
  "Аренда жилья и помещений": "Konut ve işyeri kiralama",
  "Арест": "Haciz",
  "Асфальт": "Asfalt",
  "Б/у": "İkinci el",
  "База отдыха": "Tatil köyü",
  "Балкон или лоджия": "Balkon veya kapalı balkon",
  "Без комиссии": "Komisyonsuz",
  "Без мебели": "Eşyasız",
  "Без опыта": "Deneyim gerekmez",
  "Без оформления": "Kayıt dışı",
  "Без предоплаты": "Ön ödemesiz",
  "Без ремонта": "Tadilatsız",
  "Без транспорта": "Araçsız",
  "Бездорожье": "Arazi",
  "Белый": "Beyaz",
  "Бензин": "Benzin",
  "Билеты на события": "Etkinlik biletleri",
  "Бокс": "Boks",
  "Более 15 человек": "15 kişiden fazla",
  "Более 5 лет": "5 yıldan fazla",
  "Более 6 лет": "6 yıldan fazla",
  "Бренд": "Marka",
  "Бригада": "Ekip",
  "Брови и ресницы": "Kaş ve kirpik",
  "Брюки": "Pantolon",
  "Брюки и джинсы": "Pantolon ve kot",
  "Бустер": "Yükseltici koltuk",
  "Бытовая техника": "Ev aletleri",
  "В вакансии — что предлагаете, в резюме — что ожидаете.": "İş ilanında ne sunduğunuzu, özgeçmişte ne beklediğinizi yazın.",
  "В добрые руки с договором": "Sözleşmeyle güvenilir bir yuvaya",
  "В месяц": "Aylık",
  "В офисе заказчика": "Müşterinin ofisinde",
  "В салоне": "Salonda",
  "В собственности": "Mülkiyette",
  "Вариатор": "CVT (Variatör)",
  "Вахта": "Vardiyalı çalışma",
  "Велосипеды": "Bisikletler",
  "Верхняя одежда": "Dış giyim",
  "Взрослые": "Yetişkinler",
  "Взять в аренду": "Kiralamak istiyorum",
  "Вид животного": "Hayvan türü",
  "Вид работ": "İş türü",
  "Вид разрешённого использования": "İzin verilen kullanım türü",
  "Вид услуги": "Hizmet türü",
  "Видеокамера": "Video kamera",
  "Владельцев по ПТС": "Ruhsattaki sahip sayısı",
  "Внедорожник": "Arazi aracı (SUV)",
  "Водительские права": "Sürücü belgesi",
  "Возможна доставка": "Teslimat mümkün",
  "Возможна ипотека": "Kredi ile alınabilir",
  "Возраст": "Yaş",
  "Возраст водителя от": "Sürücü yaşı en az",
  "Возрастная группа": "Yaş grubu",
  "Все вакансии": "Tüm iş ilanları",
  "Все комнаты, санузел и кухня. Минимум 5 фото.": "Tüm odalar, banyo ve mutfak. En az 5 fotoğraf.",
  "Все объекты в продаже": "Satılık tüm gayrimenkuller",
  "Все объявления": "Tüm ilanlar",
  "Все предложения услуг": "Tüm hizmet teklifleri",
  "Все резюме": "Tüm özgeçmişler",
  "Все центральные": "Tüm merkezi",
  "Встроенная память": "Dahili depolama",
  "Вывоз мусора": "Çöp/moloz taşıma",
  "Выезд к заказчику": "Müşteriye gidilir",
  "Выплаты": "Ödemeler",
  "Высота": "Yükseklik",
  "Высота потолков": "Tavan yüksekliği",
  "Выставки": "Sergiler",
  "Высшее": "Lisans/Üniversite",
  "Газ": "Doğalgaz",
  "Газель": "Kamyonet (Gazelle)",
  "Газоблок": "Gaz beton",
  "Газовое": "Gazlı",
  "Гараж": "Garaj",
  "Гараж и машиноместо": "Garaj ve otopark yeri",
  "Гаражи и машиноместа": "Garajlar ve otopark yerleri",
  "Гарантия действует": "Garanti geçerli",
  "Гарантия на работы": "İşçilik garantisi",
  "Гастротур": "Gastronomi turu",
  "Где принимаете": "Nerede hizmet veriyorsunuz",
  "Геймпад": "Oyun kolu",
  "Генеральная уборка": "Genel temizlik",
  "Гибрид": "Hibrit",
  "Гитары": "Gitarlar",
  "Глубина": "Derinlik",
  "Год выпуска": "Üretim yılı",
  "Год постройки": "Yapım yılı",
  "Головные уборы": "Şapka ve bere",
  "Горелки и посуда": "Ocaklar ve kamp mutfak eşyaları",
  "Город": "Şehir",
  "Город отправления": "Kalkış şehri",
  "Гостей": "Misafir sayısı",
  "Готов к переезду": "Taşınmaya hazır",
  "График": "Çalışma düzeni",
  "Грузовик": "Kamyon",
  "Грузовик до 5 т": "5 tona kadar kamyon",
  "Грузовик свыше 5 т": "5 tondan büyük kamyon",
  "Грузовики и спецтехника": "Kamyon ve iş makineleri",
  "Грузоподъёмность": "Taşıma kapasitesi",
  "Грузчики": "Nakliyeciler (hammal)",
  "Грунт": "Toprak zemin",
  "Грызуны": "Kemirgenler",
  "Да": "Evet",
  "Дата события": "Etkinlik tarihi",
  "Два раза в месяц": "Ayda iki kez",
  "Двери": "Kapılar",
  "Двигатель": "Motor",
  "Девочка": "Kız",
  "Дерево": "Ahşap",
  "Дети и детские услуги": "Çocuk ve çocuk hizmetleri",
  "Детская мебель": "Çocuk mobilyası",
  "Детская одежда и обувь": "Çocuk giyim ve ayakkabı",
  "Детское": "Çocuk",
  "Диагональ": "Ekran boyutu",
  "Диагональ экрана": "Ekran köşegeni",
  "Диван": "Kanepe",
  "Дизайн": "Tasarım",
  "Дизайнерский": "Tasarım ürünü",
  "Дизель": "Dizel",
  "Длительно (от года)": "Uzun süreli (1 yıldan itibaren)",
  "Длительность занятия": "Ders süresi",
  "Для дома": "Ev için",
  "Для кого": "Kimin için",
  "Для марки": "Marka için",
  "До 15 человек": "15 kişiye kadar",
  "До 5 человек": "5 kişiye kadar",
  "До года": "1 yaşına kadar",
  "Договор ГПХ": "Hizmet sözleşmesi",
  "Долевая собственность": "Hisseli mülkiyet",
  "Дом": "Ev",
  "Дом, дача, таунхаус": "Ev, yazlık, sıra ev",
  "Дома и дачи": "Evler ve yazlıklar",
  "Домашний кинотеатр": "Ev sineması",
  "Домашний персонал": "Ev personeli",
  "Домики и лежанки": "Kulübe ve yataklar",
  "Допустимый вес ребёнка": "İzin verilen çocuk ağırlığı",
  "Дорожный": "Yol tipi (touring)",
  "Доставка мебели": "Mobilya taşıma",
  "Дошкольники": "Okul öncesi",
  "Другая": "Diğer",
  "Другие языки": "Diğer diller",
  "Духовые": "Nefesli çalgılar",
  "Евроремонт": "Lüks tadilat (Avrupa standardı)",
  "Единица расчёта": "Hesaplama birimi",
  "Единоборства": "Dövüş sporları",
  "Ежедневно": "Her gün",
  "Еженедельно": "Her hafta",
  "Есть": "Var",
  "Есть автомобиль": "Aracı var",
  "Есть документы и родословная": "Belgeleri ve soy kütüğü var",
  "Есть сертификат или диплом": "Sertifika veya diploması var",
  "ЖКХ и благоустройство": "Site yönetimi ve çevre düzenleme",
  "Женское": "Kadın",
  "Животные": "Hayvanlar",
  "Живые фото питомца, а не изображения породы из интернета.": "İnternetten ırk fotoğrafı değil, hayvanın kendi gerçek fotoğrafını ekleyin.",
  "За два месяца": "İki ayda bir",
  "За заказ": "Sipariş başına",
  "За км": "Km başına",
  "За м²": "m² başına",
  "За месяц": "Ay başına",
  "За метр погонный": "Metretül başına",
  "За проект": "Proje başına",
  "За услугу": "Hizmet başına",
  "За час": "Saat başına",
  "Задний": "Arkadan çekiş",
  "Залог": "Depozito",
  "Занятость": "Çalışma şekli",
  "Заполним марку, модель, год и двигатель автоматически. Можно ввести данные вручную.": "Marka, model, yıl ve motoru otomatik dolduracağız. Verileri elle de girebilirsiniz.",
  "Запчасти и аксессуары": "Yedek parça ve aksesuar",
  "Зарплата от": "Maaş, en az",
  "Земельные участки": "Arsalar",
  "Земельный участок": "Arsa",
  "Зимний спорт": "Kış sporları",
  "Значки": "Rozetler",
  "ИЖС": "Bireysel konut inşaatı arsası",
  "Игра": "Oyun",
  "Игровая приставка": "Oyun konsolu",
  "Игрушки": "Oyuncaklar",
  "Игрушки и товары для игр": "Oyuncak ve oyun ürünleri",
  "Игры и приставки": "Oyunlar ve konsollar",
  "Индивидуально": "Bireysel",
  "Индивидуальный гид": "Özel rehber",
  "Инструменты": "Aletler",
  "Информатика": "Bilgisayar bilimi",
  "Ипотека": "Konut kredisi",
  "Искусство и творчество": "Sanat ve el sanatları",
  "Кадастровый номер": "Tapu (kadastro) numarası",
  "Каркас": "İskelet/Çerçeve",
  "Квартира": "Daire",
  "Квартирный переезд": "Ev taşıma",
  "Квартиры": "Daireler",
  "Кино": "Sinema",
  "Кирпич": "Tuğla",
  "Клавишные": "Tuşlu çalgılar",
  "Клетки и переноски": "Kafes ve taşıma çantası",
  "Клининговая компания": "Temizlik şirketi",
  "Книги": "Kitaplar",
  "Книги и коллекционирование": "Kitap ve koleksiyon",
  "Кожа": "Deri",
  "Количество билетов": "Bilet sayısı",
  "Колонки": "Hoparlörler",
  "Коляска 2 в 1": "2 in 1 bebek arabası",
  "Коляска 3 в 1": "3 in 1 bebek arabası",
  "Коляска-люлька": "Portbebe (ana kucağı) bebek arabası",
  "Коляски и автокресла": "Bebek arabaları ve oto koltukları",
  "Командные виды": "Takım sporları",
  "Комбинезоны": "Tulumlar",
  "Комиссия агента": "Emlakçı komisyonu",
  "Коммерческая недвижимость": "Ticari gayrimenkul",
  "Коммерческое": "Ticari",
  "Коммунальные включены": "Aidat dahil",
  "Коммуникации": "Altyapı (su-elektrik-doğalgaz)",
  "Комнат": "Oda sayısı",
  "Комната": "Oda",
  "Комод": "Şifonyer",
  "Компания": "Şirket",
  "Кондиционер": "Klima",
  "Конструкторы": "Yapı setleri (lego vb.)",
  "Концерты": "Konserler",
  "Копирайтинг": "Metin yazarlığı",
  "Корма": "Yemler",
  "Коробка передач": "Vites kutusu",
  "Коротко и по делу — это первое, что видит покупатель.": "Kısa ve net yazın — alıcının ilk göreceği şey bu.",
  "Коротко и по делу — это первое, что видит человек.": "Kısa ve net yazın — kullanıcının ilk göreceği şey bu.",
  "Косметика": "Kozmetik",
  "Косметический": "Kozmetik (hafif) tadilat",
  "Косметология": "Estetik/Cilt bakımı",
  "Кофты и футболки": "Kazak ve tişört",
  "Кошки": "Kediler",
  "Кран": "Vinç",
  "Красный": "Kırmızı",
  "Красота и здоровье": "Güzellik ve sağlık",
  "Кроватка": "Bebek karyolası",
  "Кровать": "Yatak",
  "Кровля": "Çatı",
  "Кросс": "Kros (motosiklet)",
  "Круизер": "Cruiser",
  "Кто оказывает услугу": "Hizmeti kim veriyor",
  "Кузов": "Kasa tipi",
  "Куклы": "Bebekler (oyuncak)",
  "Купе": "Coupe",
  "Купить": "Satın al",
  "Кухонный гарнитур": "Mutfak dolabı takımı",
  "ЛДСП": "Laminat yonga levha",
  "ЛПХ": "Şahsi tarım arazisi",
  "Легковые авто": "Binek araçlar",
  "Лимит пробега в сутки": "Günlük kilometre limiti",
  "Личные вещи": "Kişisel eşyalar",
  "Макияж": "Makyaj",
  "Мальчик": "Erkek",
  "Манеж": "Oyun parkı (bebek)",
  "Маникюр и педикюр": "Manikür ve pedikür",
  "Марка": "Marka",
  "Маркетинг и медиа": "Pazarlama ve medya",
  "Марки": "Pullar",
  "Массаж": "Masaj",
  "Математика": "Matematik",
  "Материал": "Malzeme",
  "Материал стен": "Duvar malzemesi",
  "Машинки": "Oyuncak arabalar",
  "Машиноместо": "Otopark yeri",
  "Мебель": "Mobilya",
  "Мебель и интерьер": "Mobilya ve dekorasyon",
  "Медиаплеер": "Medya oynatıcı",
  "Медицинские товары": "Medikal ürünler",
  "Междугородние перевозки": "Şehirler arası nakliye",
  "Менее года": "1 yıldan az",
  "Месяц": "Ay",
  "Металл": "Metal",
  "Механика": "Manuel vites",
  "Микроволновка": "Mikrodalga fırın",
  "Минивэн": "Minivan",
  "Минимальный срок": "Minimum süre",
  "Минимум 3 фото — объявления с фото смотрят в 4 раза чаще.": "En az 3 fotoğraf ekleyin — fotoğraflı ilanlar 4 kat daha çok görüntüleniyor.",
  "Минимум 3 фото, включая экран во включённом состоянии.": "Açık haldeki ekranı da gösteren en az 3 fotoğraf ekleyin.",
  "Минимум 3 фото.": "En az 3 fotoğraf.",
  "Минимум 3 фото: спереди, сзади, салон.": "En az 3 fotoğraf: ön, arka, iç mekan.",
  "Многодневный тур": "Çok günlük tur",
  "Мобильные приложения": "Mobil uygulamalar",
  "Модели и фигурки": "Maket ve figürler",
  "Модель": "Model",
  "Можно без опыта": "Deneyimsiz olabilir",
  "Можно с детьми": "Çocuklu ailelere uygun",
  "Можно с животными": "Evcil hayvana izin var",
  "Монеты": "Madeni paralar",
  "Моноблок": "All-in-one bilgisayar",
  "Морская прогулка": "Tekne turu",
  "Мотоциклы и мототехника": "Motosiklet ve moto araçlar",
  "Мужское": "Erkek",
  "Музыка": "Müzik",
  "Музыкальные инструменты": "Müzik aletleri",
  "Муниципальная": "Belediyeye ait",
  "Мытьё окон": "Cam silme",
  "Мягкие игрушки": "Peluş oyuncaklar",
  "На дому у мастера": "Ustanın evinde",
  "На месте": "Yerinde",
  "На несколько месяцев": "Birkaç ay için",
  "Навигация": "Navigasyon",
  "Навыки": "Beceriler",
  "Название компании": "Şirket adı",
  "Название объявления": "İlan başlığı",
  "Назначение": "Kullanım amacı",
  "Найти жильё": "Konut bul",
  "Найти исполнителя": "Hizmet sağlayıcı bul",
  "Найти питомца или товар": "Evcil hayvan veya ürün bul",
  "Найти работу": "İş bul",
  "Найти сотрудника": "Çalışan bul",
  "Найти тур или снаряжение": "Tur veya ekipman bul",
  "Найти человека в команду": "Ekibe kişi bul",
  "Накопитель": "Depolama birimi",
  "Напольные покрытия": "Zemin kaplamaları",
  "Направление": "Branş/Alan",
  "Например: 15 октября 2026": "Örnek: 15 Ekim 2026",
  "Населённый пункт": "Yerleşim yeri",
  "Настольные игры": "Masa oyunları",
  "Настольный компьютер": "Masaüstü bilgisayar",
  "Настройка сетей": "Ağ kurulumu",
  "Наука и инженерия": "Bilim ve mühendislik",
  "Наушники": "Kulaklık",
  "Начальная школа": "İlkokul",
  "Недвижимость": "Gayrimenkul",
  "Неделя": "Hafta",
  "Незаконченное высшее": "Yarım kalmış üniversite",
  "Необязательно. Требовать возраст в вакансиях запрещено законом.": "Zorunlu değil. İş ilanlarında yaş şartı aramak yasalarca yasaktır.",
  "Нет": "Hayır",
  "Новое": "Yeni",
  "Новое без бирки": "Yeni, etiketsiz",
  "Новое вскрытое": "Yeni, açılmış",
  "Новое запечатанное": "Yeni, ambalajlı",
  "Новое с биркой": "Yeni, etiketli",
  "Ноутбук": "Dizüstü bilgisayar",
  "Ноутбуки и компьютеры": "Dizüstü ve masaüstü bilgisayarlar",
  "О себе": "Hakkımda",
  "О себе и методике": "Hakkımda ve yöntemim",
  "Образование": "Eğitim",
  "Обременения": "Şerhler/İpotek",
  "Обувь": "Ayakkabı",
  "Обучение и репетиторы": "Eğitim ve özel ders",
  "Объектив": "Lens",
  "Объём двигателя": "Motor hacmi",
  "Обязанности": "Sorumluluklar",
  "Огорожен": "Çevrili (çitli)",
  "Одежда для походов": "Doğa yürüyüşü giysileri",
  "Одежда и обувь": "Giyim ve ayakkabı",
  "Окна": "Pencereler",
  "Окна и двери": "Pencere ve kapılar",
  "Онлайн": "Online",
  "Оперативная память": "RAM",
  "Описание": "Açıklama",
  "Описание маршрута": "Güzergah açıklaması",
  "Описание услуги": "Hizmet açıklaması",
  "Описание услуги и портфолио": "Hizmet açıklaması ve portfolyo",
  "Опыт преподавания": "Öğretmenlik deneyimi",
  "Опыт работы": "İş deneyimi",
  "Оставьте пустым, если залога нет.": "Depozito yoksa boş bırakın.",
  "Оставьте пустым, если отдаёте даром.": "Ücretsiz veriyorsanız boş bırakın.",
  "Отдам даром": "Ücretsiz veriyorum",
  "Отделочные работы": "İnce işçilik",
  "Отдельный вход": "Ayrı giriş",
  "Открытки": "Kartpostallar",
  "Отличное": "Mükemmel",
  "Отопление": "Isıtma",
  "Офис": "Ofis",
  "Офис и администрация": "Ofis ve idari işler",
  "Офисный переезд": "Ofis taşıma",
  "Оформление": "Resmi kayıt",
  "Оформление, отпуск, что оплачивается.": "Sözleşme türü, izin ve ücretli olan haklar.",
  "Охрана": "Güvenlik",
  "Охрана и безопасность": "Güvenlik ve emniyet",
  "Очки": "Gözlük",
  "Палатки": "Çadırlar",
  "Панель": "Panel",
  "Парикмахерские услуги": "Kuaförlük hizmetleri",
  "Парковка": "Otopark",
  "Парта": "Çalışma masası",
  "Парфюмерия": "Parfümeri",
  "Пеленальный столик": "Alt değiştirme masası",
  "Первое занятие бесплатно": "İlk ders ücretsiz",
  "Перевозки и грузчики": "Nakliye ve taşıma",
  "Передний": "Önden çekiş",
  "Переуступка": "Devir",
  "Печное": "Sobalı",
  "Планшет": "Tablet",
  "Платформа": "Platform",
  "Платья": "Elbiseler",
  "Плита": "Ocak",
  "Плитка": "Fayans",
  "Площадь": "Alan",
  "Площадь дома": "Ev alanı",
  "Площадь участка": "Arsa alanı",
  "По ТК РФ": "İş kanununa göre",
  "По договорённости": "Anlaşmaya göre",
  "По номеру заполним площадь, вид использования и границы. Можно пропустить.": "Numaraya göre alanı, kullanım türünü ve sınırları dolduracağız. Atlayabilirsiniz.",
  "Погрузчик": "Forklift/Yükleyici",
  "Подвеска": "Süspansiyon",
  "Подготовка к ЕГЭ и ОГЭ": "Sınav hazırlık (üniversite/lise giriş)",
  "Поддерживающая уборка": "Rutin temizlik",
  "Подработка": "Ek iş",
  "Подростковое": "Genç/Teen",
  "Подходит студентам": "Öğrenciler için uygun",
  "Подъездная дорога": "Giriş yolu",
  "Покажите вещь целиком и вблизи — фактуру и возможные дефекты.": "Ürünü hem bütün hem yakından gösterin — dokusunu ve varsa kusurlarını.",
  "Покажите крепления и ремни — это первое, что смотрят родители.": "Bağlantı ve kemerleri gösterin — ebeveynlerin ilk baktığı şey bu.",
  "Пол": "Cinsiyet",
  "Полки": "Raflar",
  "Полная": "Tam zamanlı",
  "Полностью меблирована": "Tamamen eşyalı",
  "Полный": "Tam (4x4)",
  "Полный комплект": "Tam takım",
  "Помощь по хозяйству": "Ev işlerine yardım",
  "Порода": "Irk/Cins",
  "Портфолио повышает отклик в разы. Минимум 3 фото.": "Portfolyo başvuruyu kat kat artırır. En az 3 fotoğraf.",
  "Портфолио — главный аргумент в этой категории.": "Bu kategoride en önemli unsur portfolyodur.",
  "Последнее место работы": "Son çalıştığı yer",
  "Посудомоечная машина": "Bulaşık makinesi",
  "Посуточная аренда": "Günlük kiralama",
  "Посуточная аренда жилья": "Günlük kiralık konut",
  "Посуточно": "Günlük",
  "Предложить услугу": "Hizmet sun",
  "Предмет или направление": "Ders veya alan",
  "Предоплата": "Ön ödeme",
  "Приборы для ухода": "Bakım cihazları",
  "Прививки сделаны": "Aşıları yapıldı",
  "Привод": "Çekiş",
  "Пробег": "Kilometre",
  "Пробег затвора": "Deklanşör sayacı",
  "Прогулочная коляска": "Gezinti tipi bebek arabası",
  "Продажа": "Satış",
  "Продажа или отдам даром": "Satılık veya ücretsiz",
  "Продажи и торговля": "Satış ve ticaret",
  "Продать": "Sat",
  "Продолжительность": "Süre",
  "Проектор": "Projeksiyon",
  "Проживание, питание, трансфер, входные билеты.": "Konaklama, yemek, transfer, giriş biletleri.",
  "Производство": "Üretim",
  "Профессия": "Meslek",
  "Процессор": "İşlemci",
  "Птицы": "Kuşlar",
  "Путешествия": "Seyahat",
  "Пылесос": "Elektrikli süpürge",
  "Работа": "İş",
  "Работаю круглосуточно": "7/24 çalışıyorum",
  "Работаю по договору": "Sözleşmeli çalışıyorum",
  "Раз в месяц": "Ayda bir",
  "Развивающие": "Eğitici (gelişim)",
  "Размер": "Beden",
  "Размер группы": "Grup büyüklüğü",
  "Разместить вакансию": "İş ilanı ver",
  "Разместить объявление": "İlan ver",
  "Разместить объявление о продаже": "Satış ilanı ver",
  "Разместить объявление об аренде": "Kiralık ilanı ver",
  "Разместить предложение": "Teklif ver",
  "Разместить резюме": "Özgeçmiş yayınla",
  "Разместить своё объявление": "Kendi ilanını ver",
  "Разработка сайтов": "Web sitesi geliştirme",
  "Растения и саженцы": "Bitki ve fideler",
  "Ремни": "Kemerler",
  "Ремонт": "Tadilat",
  "Ремонт и строительство": "Tadilat ve inşaat",
  "Ремонт и стройматериалы": "Tadilat ve yapı malzemeleri",
  "Ремонт компьютеров": "Bilgisayar tamiri",
  "Ремонт под ключ": "Anahtar teslim tadilat",
  "Рента": "Rant/Kira geliri",
  "Рестораны и гостиницы": "Restoran ve otelcilik",
  "Робот": "Robot",
  "Рубашки и блузки": "Gömlek ve bluz",
  "Русский язык": "Rusça",
  "Рыбалка": "Balıkçılık",
  "Рыбы": "Balıklar",
  "Рюкзаки": "Sırt çantaları",
  "С водителем": "Şoförlü",
  "С выездом к клиенту": "Müşteriye gidilerek",
  "С выездом к ученику": "Öğrenciye gidilerek",
  "Сад и огород": "Bahçe ve sebze bahçesi",
  "Садовая мебель": "Bahçe mobilyası",
  "Садовая техника": "Bahçe makineleri",
  "Садоводство (СНТ)": "Bahçe kooperatifi arazisi",
  "Салон": "Salon",
  "Самозанятость": "Serbest meslek",
  "Сантехника": "Tesisat",
  "Сборка мебели": "Mobilya montajı",
  "Свет": "Aydınlatma",
  "Свитеры и кофты": "Kazak ve süveter",
  "Свободное назначение": "Serbest kullanım",
  "Свободный": "Boş/Müsait",
  "Сдать": "Kirala (ver)",
  "Сдать в аренду": "Kiraya ver",
  "Сдать жильё": "Konut kirala (ver)",
  "Седан": "Sedan",
  "Сельское хозяйство": "Tarım",
  "Сельхозживотные": "Çiftlik hayvanları",
  "Сельхозназначение": "Tarımsal amaçlı",
  "Серебристый": "Gümüş",
  "Серый": "Gri",
  "Синий": "Mavi",
  "Склад": "Depo",
  "Скутер": "Skuter",
  "Сменный": "Vardiyalı",
  "Снимите со всех сторон — так вещь продаётся быстрее.": "Her açıdan fotoğraf çekin — ürün böylece daha hızlı satılır.",
  "Снять": "Kirala",
  "Со своими средствами и техникой": "Kendi malzeme ve ekipmanıyla",
  "Собаки": "Köpekler",
  "Собственность": "Mülkiyet",
  "Состояние": "Durum",
  "Состояние, история обслуживания, что менялось.": "Durumu, bakım geçmişi, değişen parçalar.",
  "Спальники": "Uyku tulumları",
  "Сплав и походы": "Rafting ve doğa yürüyüşü",
  "Спорт": "Spor",
  "Спорт и отдых": "Spor ve eğlence",
  "Спорт и фитнес": "Spor ve fitness",
  "Спортивная одежда": "Spor giyim",
  "Среднее": "Lise",
  "Среднее специальное": "Meslek yüksekokulu",
  "Средний срок выполнения": "Ortalama tamamlanma süresi",
  "Средняя школа": "Ortaokul",
  "Срок аренды": "Kiralama süresi",
  "Стаж вождения от": "Sürücü deneyimi, en az",
  "Стажировка": "Staj",
  "Старшие классы": "Lise sınıfları",
  "Стекло": "Cam",
  "Стерилизован": "Kısırlaştırılmış",
  "Стиральная машина": "Çamaşır makinesi",
  "Стол": "Masa",
  "Строительство и ремонт": "İnşaat ve tadilat",
  "Стройматериалы": "Yapı malzemeleri",
  "Струнные смычковые": "Yaylı çalgılar",
  "Студенты": "Öğrenciler",
  "Студийное оборудование": "Stüdyo ekipmanı",
  "Студия": "Stüdyo daire",
  "Стульчик для кормления": "Mama sandalyesi",
  "Стулья": "Sandalyeler",
  "Сумки": "Çantalar",
  "Сутки": "Gün (24 saat)",
  "Театр": "Tiyatro",
  "Телевизор": "Televizyon",
  "Телевизоры и аудио": "Televizyon ve ses sistemleri",
  "Телефоны": "Telefonlar",
  "Теплицы": "Seralar",
  "Тип": "Tür",
  "Тип билета": "Bilet türü",
  "Тип вещи": "Ürün türü",
  "Тип жилья": "Konut türü",
  "Тип запчасти": "Parça türü",
  "Тип игрушки": "Oyuncak türü",
  "Тип инструмента": "Alet türü",
  "Тип мебели": "Mobilya türü",
  "Тип объекта": "Gayrimenkul türü",
  "Тип снаряжения": "Ekipman türü",
  "Тип техники": "Makine türü",
  "Тип товара": "Ürün türü",
  "Тип топлива": "Yakıt türü",
  "Тип устройства": "Cihaz türü",
  "Ткань": "Kumaş",
  "Товары для животных": "Evcil hayvan ürünleri",
  "Только грузчики": "Sadece nakliyeciler",
  "Торговое": "Ticari",
  "Транспорт": "Ulaşım araçları",
  "Транспорт и логистика": "Ulaştırma ve lojistik",
  "Трансфер включён": "Transfer dahil",
  "Требования": "Gereksinimler",
  "Требует ремонта": "Tadilat gerektiriyor",
  "Тренажёры": "Fitness aletleri",
  "Тур, экскурсия или снаряжение": "Tur, gezi veya ekipman",
  "Туризм и походы": "Turizm ve doğa yürüyüşü",
  "Туристическое снаряжение": "Kamp ve outdoor ekipmanı",
  "Туры и экскурсии": "Turlar ve geziler",
  "Туры, экскурсии, снаряжение": "Turlar, geziler, ekipman",
  "Тягач": "Çekici",
  "У преподавателя": "Öğretmenin yerinde",
  "Уборка и помощь по хозяйству": "Temizlik ve ev işleri yardımı",
  "Уборка после ремонта": "Tadilat sonrası temizlik",
  "Удалённо": "Uzaktan",
  "Удалённость от города": "Şehre uzaklık",
  "Ударные": "Vurmalı çalgılar",
  "Удовлетворительное": "Orta (kabul edilebilir)",
  "Украшения": "Takılar",
  "Уличные игрушки": "Bahçe/dış mekan oyuncakları",
  "Универсал": "Station wagon",
  "Универсальное": "Çok amaçlı",
  "Унисекс": "Unisex",
  "Условия": "Koşullar",
  "Условия передачи": "Teslim koşulları",
  "Услуги": "Hizmetler",
  "Уход и гигиена": "Bakım ve hijyen",
  "Фестивали": "Festivaller",
  "Физика": "Fizik",
  "Финансы и бухгалтерия": "Finans ve muhasebe",
  "Форма собственности": "Mülkiyet türü",
  "Формат занятий": "Ders formatı",
  "Формат работы": "Çalışma formatı",
  "Фото выполненных работ": "Yapılan işlerin fotoğrafları",
  "Фото и видеотехника": "Fotoğraf ve video ekipmanı",
  "Фото работ": "İş fotoğrafları",
  "Фотоаппарат": "Fotoğraf makinesi",
  "Фотографии": "Fotoğraflar",
  "Фургон": "Panelvan",
  "Характер, привычки, к чему приучен, почему передаёте.": "Karakteri, alışkanlıkları, neye alıştırıldığı ve neden verildiği.",
  "Химия": "Kimya",
  "Химчистка мебели": "Mobilya kuru temizleme",
  "Хобби и отдых": "Hobi ve eğlence",
  "Холодильник": "Buzdolabı",
  "Хорошее": "İyi",
  "Хостел": "Hostel",
  "Хэтчбек": "Hatchback",
  "Цвет": "Renk",
  "Цена": "Fiyat",
  "Цена за билет": "Bilet fiyatı",
  "Цена за занятие от": "Ders başı fiyat, en az",
  "Цена за месяц": "Aylık fiyat",
  "Цена за сутки": "Günlük fiyat",
  "Цена от": "Fiyat, en az",
  "Цена с человека": "Kişi başı fiyat",
  "Час": "Saat",
  "Частичная": "Yarı zamanlı",
  "Частично": "Kısmen",
  "Частный мастер": "Bağımsız usta",
  "Частный специалист": "Bağımsız uzman",
  "Часы": "Saatler",
  "Чем занимались, что умеете, чего ищете.": "Ne ile uğraştığınız, neler bildiğiniz, ne aradığınız.",
  "Что в комплекте, были ли ремонты, есть ли дефекты.": "Neler dahil, onarım geçirdi mi, kusur var mı.",
  "Что включено": "Nelerin dahil olduğu",
  "Что делаете, за какой срок, что входит в стоимость.": "Ne yaptığınız, ne kadar sürede, fiyata neler dahil.",
  "Что продаёте": "Ne sattığınız",
  "Что рядом, как заселение, что входит в стоимость.": "Yakında neler var, giriş nasıl yapılıyor, fiyata neler dahil.",
  "Что человек будет делать каждый день.": "Kişinin her gün ne yapacağı.",
  "Чтобы работа нашла вас": "İş sizi bulsun",
  "Чёрный": "Siyah",
  "Шины и диски": "Lastik ve jant",
  "Ширина": "Genişlik",
  "Шкаф": "Dolap",
  "Штатив и стабилизаторы": "Tripod ve stabilizatör",
  "Экскаватор": "Ekskavatör",
  "Экскурсия": "Gezi",
  "Экшн-камера": "Aksiyon kamerası",
  "Электрика": "Elektrik tesisatı",
  "Электрическое": "Elektrikli",
  "Электричество": "Elektrik",
  "Электричество, газ": "Elektrik, doğalgaz",
  "Электро": "Elektrikli",
  "Электроника": "Elektronik",
  "Эндуро": "Enduro",
  "Эпиляция": "Epilasyon",
  "Этаж": "Kat",
  "Этажей": "Kat sayısı",
  "Этажей в доме": "Binadaki kat sayısı",
  "Юриспруденция": "Hukuk",

  // Единицы измерения (unit у полей категорий)
  "дней": "gün",
  "кадров": "çekim",
  "кг": "kg",
  "км": "km",
  "л": "L",
  "лет": "yıl",
  "м": "m",
  "м²": "m²",
  "мес.": "ay",
  "мин": "dk",
  "см": "cm",
  "см³": "cm³",
  "соток": "ar",
  "суток": "gün",
  "т": "t",
  "\"": "\"",
  "%": "%",
  "₽": "₽",
};
